// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	nvcav1alpha1 "github.com/NVIDIA/nvcf/src/compute-plane-services/nvca/pkg/apis/nvca/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// MiniServiceLister helps list MiniServices.
// All objects returned here must be treated as read-only.
type MiniServiceLister interface {
	// List lists all MiniServices in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*nvcav1alpha1.MiniService, err error)
	// MiniServices returns an object that can list and get MiniServices.
	MiniServices(namespace string) MiniServiceNamespaceLister
	MiniServiceListerExpansion
}

// miniServiceLister implements the MiniServiceLister interface.
type miniServiceLister struct {
	listers.ResourceIndexer[*nvcav1alpha1.MiniService]
}

// NewMiniServiceLister returns a new MiniServiceLister.
func NewMiniServiceLister(indexer cache.Indexer) MiniServiceLister {
	return &miniServiceLister{listers.New[*nvcav1alpha1.MiniService](indexer, nvcav1alpha1.Resource("miniservice"))}
}

// MiniServices returns an object that can list and get MiniServices.
func (s *miniServiceLister) MiniServices(namespace string) MiniServiceNamespaceLister {
	return miniServiceNamespaceLister{listers.NewNamespaced[*nvcav1alpha1.MiniService](s.ResourceIndexer, namespace)}
}

// MiniServiceNamespaceLister helps list and get MiniServices.
// All objects returned here must be treated as read-only.
type MiniServiceNamespaceLister interface {
	// List lists all MiniServices in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*nvcav1alpha1.MiniService, err error)
	// Get retrieves the MiniService from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*nvcav1alpha1.MiniService, error)
	MiniServiceNamespaceListerExpansion
}

// miniServiceNamespaceLister implements the MiniServiceNamespaceLister
// interface.
type miniServiceNamespaceLister struct {
	listers.ResourceIndexer[*nvcav1alpha1.MiniService]
}
