/*
SPDX-FileCopyrightText: Copyright (c) NVIDIA CORPORATION & AFFILIATES. All rights reserved.
SPDX-License-Identifier: Apache-2.0

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by mockery v2.39.2. DO NOT EDIT.

package mocks

import (
	jose "github.com/go-jose/go-jose/v4"
	mock "github.com/stretchr/testify/mock"
)

// JOSEEncryption is an autogenerated mock type for the Encrypter type
type JOSEEncryption struct {
	mock.Mock
}

// Encrypt provides a mock function with given fields: plaintext
func (_m *JOSEEncryption) Encrypt(plaintext []byte) (*jose.JSONWebEncryption, error) {
	ret := _m.Called(plaintext)

	if len(ret) == 0 {
		panic("no return value specified for Encrypt")
	}

	var r0 *jose.JSONWebEncryption
	var r1 error
	if rf, ok := ret.Get(0).(func([]byte) (*jose.JSONWebEncryption, error)); ok {
		return rf(plaintext)
	}
	if rf, ok := ret.Get(0).(func([]byte) *jose.JSONWebEncryption); ok {
		r0 = rf(plaintext)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*jose.JSONWebEncryption)
		}
	}

	if rf, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = rf(plaintext)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EncryptWithAuthData provides a mock function with given fields: plaintext, aad
func (_m *JOSEEncryption) EncryptWithAuthData(plaintext []byte, aad []byte) (*jose.JSONWebEncryption, error) {
	ret := _m.Called(plaintext, aad)

	if len(ret) == 0 {
		panic("no return value specified for EncryptWithAuthData")
	}

	var r0 *jose.JSONWebEncryption
	var r1 error
	if rf, ok := ret.Get(0).(func([]byte, []byte) (*jose.JSONWebEncryption, error)); ok {
		return rf(plaintext, aad)
	}
	if rf, ok := ret.Get(0).(func([]byte, []byte) *jose.JSONWebEncryption); ok {
		r0 = rf(plaintext, aad)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*jose.JSONWebEncryption)
		}
	}

	if rf, ok := ret.Get(1).(func([]byte, []byte) error); ok {
		r1 = rf(plaintext, aad)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Options provides a mock function with given fields:
func (_m *JOSEEncryption) Options() jose.EncrypterOptions {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Options")
	}

	var r0 jose.EncrypterOptions
	if rf, ok := ret.Get(0).(func() jose.EncrypterOptions); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(jose.EncrypterOptions)
	}

	return r0
}

// NewJOSEEncryption creates a new instance of JOSEEncryption. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewJOSEEncryption(t interface {
	mock.TestingT
	Cleanup(func())
}) *JOSEEncryption {
	mock := &JOSEEncryption{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
