# SPDX-FileCopyrightText: Copyright (c) 2023-2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
        # Health check
        server {

        {{- if (.Values.traces).enabled }}
            # Enable traces
            otel_trace on;
            otel_trace_context propagate;
        {{- end }}
            listen 13129;
            access_log  off;
            # Health check endpoint
            location /healthz {
                add_header Content-Type text/plain;
                return 200 "The Container Caching Proxy is running!";
            }

            # reload nginx
            location /reload {
                allow 127.0.0.1;
                deny all;
                content_by_lua_block {
                    local resty_signal = require "resty.signal"
                    local file, err = io.open("/var/run/nginx.pid", "r")
                    if file == nil then
                        ngx.status = 500
                        ngx.say("Failed to reload nginx process: ", err)
                        ngx.exit(ngx.status)
                    end
                    local pid = file:read("*n")
                    file:close()
                    ngx.say("Nginx PID", pid)
                    ngx.say("Reloading nginx", pid)
                    local ok, err = resty_signal.kill(pid, "HUP")
                    if not ok then
                        ngx.log(ngx.ERR, "failed to reload nginx process of pid ", pid, ": ", err)
                        ngx.say("Failed to reload nginx process: ", err)
                        ngx.status = 500
                        ngx.exit(ngx.status)
                    end
                }
            }
        }

        # Metrics
        server {
            listen 9145;
            access_log off;
            location /cache_metrics {
                content_by_lua_block {
                    metric_connections:set(ngx.var.connections_reading, {"reading"})
                    metric_connections:set(ngx.var.connections_waiting, {"waiting"})
                    metric_connections:set(ngx.var.connections_writing, {"writing"})
                    prometheus:collect()
                }
            }

            location = /metrics {
                return 404;
            }

            location /nginx_status {
                stub_status on;
                allow 127.0.0.1;
                allow ::1;
                deny all;
            }
        }
