# SPDX-FileCopyrightText: Copyright (c) 2023-2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
    # The caching layer for Nucleus/LFT
    server {
        # Reuse all existing configuration
        set $docker_proxy_request_type "nvcf-proxy-cache-nucleus";
        include  /etc/nginx/conf.d/sites/proxy-common.conf;
        access_log /dev/stdout nucleus_log buffer=256k flush=10s;

        listen 14129 ssl default_server reuseport;
        http2 {{ $.Values.cache.http2 | default "off" }};

        # Reusing the proxy_s3 cache by default
        proxy_cache proxy_s3;

        # Cache Lock
        proxy_cache_lock_timeout 3s;
        proxy_cache_lock_age 10s;

        # Handle /omni/lft locations directly
        location /omni/lft {
            # DNS resolver for Nucleus requests - moderate caching for internal service
            resolver nvcf-unbound.dns-proxy.svc.cluster.local valid=900s;  # 15min cache - internal services less stable than CDNs
            proxy_set_header   Host $http_host;
            # Client library knows what slices to use and we trust it with http_range
            proxy_set_header   Range $http_range;
            # Required headers for Nucleus LFT
            proxy_set_header   X-OV-URI $http_x_ov_uri;
            proxy_set_header   Omniverse-Proxy-Scheme $http_omniverse_proxy_scheme;
            proxy_set_header   Omniverse-Content-Uid $http_omniverse_content_uid;
            # JWT for Nucleus Bridge
            proxy_set_header   Omni-Tenant-Token $http_omni_tenant_token;

            proxy_pass_request_headers on;
            proxy_socket_keepalive on;

            # Cache key includes NCA ID and OVC 1 cache parameters
            proxy_cache_key $http_nvcf_nca_id|$request_method|$http_omniverse_content_uid|$http_range;
            proxy_pass https://$host;

            # From OVC 1
            add_header "Access-Control-Allow-Origin" "*";
            add_header "Access-Control-Allow-Headers" "*";
            add_header "Access-Control-Allow-Methods" "*";
        }

        # Handle generic forward proxy for Nucleus/LFT requests
        location / {
            # Do not cache requests that have auth headers - forward proxy can be used by multi-tenants.
            # Consider removing this restriction when nvcf_nca_id is passed down to the cache layer, which enables tenant specific caching.
            proxy_cache_bypass $http_authorization_present;

            # Remove the JWT Tenant Token - will not go through the bridge
            proxy_set_header Omni-Tenant-Token "";

            # Use Host header
            proxy_set_header   Host $http_host;
            # Use Range Header
            proxy_set_header   Range $http_range;
            proxy_pass_request_headers on;

            # Cache key includes NCA ID and generic uri with optional omniverse content uid and range
            proxy_cache_key $http_nvcf_nca_id|$request_method|$host|$request_uri|$http_omniverse_content_uid|$http_range;
            proxy_pass https://$http_host;
        }
    }
