# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

{{- if and .Values.nvcfGatewayRoutes.enabled .Values.nvcfGatewayRoutes.routes.llmInvocation.enabled }}
# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Values.nvcfGatewayRoutes.routes.llmInvocation.name }}
  namespace: {{ .Values.nvcfGatewayRoutes.gateways.shared.namespace }}
  labels:
    {{- include "nvcf-gateway.labels" . | nindent 4 }}
    app.kubernetes.io/component: llm-invocation-route
  annotations:
    {{- toYaml .Values.nvcfGatewayRoutes.routes.llmInvocation.routeAnnotations | nindent 4 }}
spec:
  parentRefs:
    - name: {{ .Values.nvcfGatewayRoutes.gateways.shared.name }}
      namespace: {{ .Values.nvcfGatewayRoutes.gateways.shared.namespace }}
      sectionName: {{ .Values.nvcfGatewayRoutes.gateways.shared.listenerName }}

  hostnames:
    {{- range .Values.nvcfGatewayRoutes.routes.llmInvocation.hostnames }}
    - {{ tpl . $ | quote }}
    {{- end }}

  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: {{ .Values.nvcfGatewayRoutes.routes.llmInvocation.backend.name }}
          namespace: {{ .Values.nvcfGatewayRoutes.routes.llmInvocation.backend.namespace }}
          port: {{ .Values.nvcfGatewayRoutes.routes.llmInvocation.backend.port }}
{{- end }}
