// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.3
// source: nvcf.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Worker_ConnectOnce_FullMethodName                             = "/nvcf.Worker/ConnectOnce"
	Worker_RefreshLargeUploadCredentials_FullMethodName           = "/nvcf.Worker/RefreshLargeUploadCredentials"
	Worker_RefreshAssetDownloadCredentials_FullMethodName         = "/nvcf.Worker/RefreshAssetDownloadCredentials"
	Worker_MultipartLargeUploadCredentials_FullMethodName         = "/nvcf.Worker/MultipartLargeUploadCredentials"
	Worker_RequestArtifacts_FullMethodName                        = "/nvcf.Worker/RequestArtifacts"
	Worker_StreamArtifacts_FullMethodName                         = "/nvcf.Worker/StreamArtifacts"
	Worker_RequestInstanceCredentials_FullMethodName              = "/nvcf.Worker/RequestInstanceCredentials"
	Worker_RequestSecretCredentials_FullMethodName                = "/nvcf.Worker/RequestSecretCredentials"
	Worker_RequestFunctionMetadataCredentials_FullMethodName      = "/nvcf.Worker/RequestFunctionMetadataCredentials"
	Worker_ProvisionRegionalWorker_FullMethodName                 = "/nvcf.Worker/ProvisionRegionalWorker"
	Worker_RequestLargeResponseDownloadCredentials_FullMethodName = "/nvcf.Worker/RequestLargeResponseDownloadCredentials"
)

// WorkerClient is the client API for Worker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WorkerClient interface {
	ConnectOnce(ctx context.Context, in *WorkerConnect, opts ...grpc.CallOption) (*WorkerConnectOnceResponse, error)
	RefreshLargeUploadCredentials(ctx context.Context, in *RefreshLargeUploadCredentialsRequest, opts ...grpc.CallOption) (*RefreshLargeUploadCredentialsResponse, error)
	RefreshAssetDownloadCredentials(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[RefreshAssetDownloadCredentialsRequest, RefreshAssetDownloadCredentialsResponse], error)
	MultipartLargeUploadCredentials(ctx context.Context, in *MultipartLargeUploadCredentialsRequest, opts ...grpc.CallOption) (*MultipartLargeUploadCredentialsResponse, error)
	// Deprecated: Use StreamArtifacts instead for streaming behavior
	RequestArtifacts(ctx context.Context, in *ArtifactsRequest, opts ...grpc.CallOption) (*ArtifactsResponse, error)
	StreamArtifacts(ctx context.Context, in *ArtifactsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamedArtifactFile], error)
	RequestInstanceCredentials(ctx context.Context, in *InstanceCredentialsRequest, opts ...grpc.CallOption) (*InstanceCredentialsResponse, error)
	RequestSecretCredentials(ctx context.Context, in *SecretCredentialsRequest, opts ...grpc.CallOption) (*SecretCredentialsResponse, error)
	RequestFunctionMetadataCredentials(ctx context.Context, in *FunctionMetadataCredentialsRequest, opts ...grpc.CallOption) (*FunctionMetadataCredentialsResponse, error)
	ProvisionRegionalWorker(ctx context.Context, in *ProvisionWorkerRequest, opts ...grpc.CallOption) (*ProvisionWorkerResponse, error)
	// the worker is now responsible for creating the full 302 redirect response for large responses, so it needs a way to retrieve the presigned download url
	RequestLargeResponseDownloadCredentials(ctx context.Context, in *LargeResponseDownloadCredentialsRequest, opts ...grpc.CallOption) (*LargeResponseDownloadCredentialsResponse, error)
}

type workerClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkerClient(cc grpc.ClientConnInterface) WorkerClient {
	return &workerClient{cc}
}

func (c *workerClient) ConnectOnce(ctx context.Context, in *WorkerConnect, opts ...grpc.CallOption) (*WorkerConnectOnceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkerConnectOnceResponse)
	err := c.cc.Invoke(ctx, Worker_ConnectOnce_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerClient) RefreshLargeUploadCredentials(ctx context.Context, in *RefreshLargeUploadCredentialsRequest, opts ...grpc.CallOption) (*RefreshLargeUploadCredentialsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RefreshLargeUploadCredentialsResponse)
	err := c.cc.Invoke(ctx, Worker_RefreshLargeUploadCredentials_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerClient) RefreshAssetDownloadCredentials(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[RefreshAssetDownloadCredentialsRequest, RefreshAssetDownloadCredentialsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Worker_ServiceDesc.Streams[0], Worker_RefreshAssetDownloadCredentials_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RefreshAssetDownloadCredentialsRequest, RefreshAssetDownloadCredentialsResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Worker_RefreshAssetDownloadCredentialsClient = grpc.BidiStreamingClient[RefreshAssetDownloadCredentialsRequest, RefreshAssetDownloadCredentialsResponse]

func (c *workerClient) MultipartLargeUploadCredentials(ctx context.Context, in *MultipartLargeUploadCredentialsRequest, opts ...grpc.CallOption) (*MultipartLargeUploadCredentialsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MultipartLargeUploadCredentialsResponse)
	err := c.cc.Invoke(ctx, Worker_MultipartLargeUploadCredentials_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerClient) RequestArtifacts(ctx context.Context, in *ArtifactsRequest, opts ...grpc.CallOption) (*ArtifactsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ArtifactsResponse)
	err := c.cc.Invoke(ctx, Worker_RequestArtifacts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerClient) StreamArtifacts(ctx context.Context, in *ArtifactsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamedArtifactFile], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Worker_ServiceDesc.Streams[1], Worker_StreamArtifacts_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ArtifactsRequest, StreamedArtifactFile]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Worker_StreamArtifactsClient = grpc.ServerStreamingClient[StreamedArtifactFile]

func (c *workerClient) RequestInstanceCredentials(ctx context.Context, in *InstanceCredentialsRequest, opts ...grpc.CallOption) (*InstanceCredentialsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InstanceCredentialsResponse)
	err := c.cc.Invoke(ctx, Worker_RequestInstanceCredentials_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerClient) RequestSecretCredentials(ctx context.Context, in *SecretCredentialsRequest, opts ...grpc.CallOption) (*SecretCredentialsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SecretCredentialsResponse)
	err := c.cc.Invoke(ctx, Worker_RequestSecretCredentials_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerClient) RequestFunctionMetadataCredentials(ctx context.Context, in *FunctionMetadataCredentialsRequest, opts ...grpc.CallOption) (*FunctionMetadataCredentialsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FunctionMetadataCredentialsResponse)
	err := c.cc.Invoke(ctx, Worker_RequestFunctionMetadataCredentials_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerClient) ProvisionRegionalWorker(ctx context.Context, in *ProvisionWorkerRequest, opts ...grpc.CallOption) (*ProvisionWorkerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProvisionWorkerResponse)
	err := c.cc.Invoke(ctx, Worker_ProvisionRegionalWorker_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerClient) RequestLargeResponseDownloadCredentials(ctx context.Context, in *LargeResponseDownloadCredentialsRequest, opts ...grpc.CallOption) (*LargeResponseDownloadCredentialsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LargeResponseDownloadCredentialsResponse)
	err := c.cc.Invoke(ctx, Worker_RequestLargeResponseDownloadCredentials_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorkerServer is the server API for Worker service.
// All implementations must embed UnimplementedWorkerServer
// for forward compatibility.
type WorkerServer interface {
	ConnectOnce(context.Context, *WorkerConnect) (*WorkerConnectOnceResponse, error)
	RefreshLargeUploadCredentials(context.Context, *RefreshLargeUploadCredentialsRequest) (*RefreshLargeUploadCredentialsResponse, error)
	RefreshAssetDownloadCredentials(grpc.BidiStreamingServer[RefreshAssetDownloadCredentialsRequest, RefreshAssetDownloadCredentialsResponse]) error
	MultipartLargeUploadCredentials(context.Context, *MultipartLargeUploadCredentialsRequest) (*MultipartLargeUploadCredentialsResponse, error)
	// Deprecated: Use StreamArtifacts instead for streaming behavior
	RequestArtifacts(context.Context, *ArtifactsRequest) (*ArtifactsResponse, error)
	StreamArtifacts(*ArtifactsRequest, grpc.ServerStreamingServer[StreamedArtifactFile]) error
	RequestInstanceCredentials(context.Context, *InstanceCredentialsRequest) (*InstanceCredentialsResponse, error)
	RequestSecretCredentials(context.Context, *SecretCredentialsRequest) (*SecretCredentialsResponse, error)
	RequestFunctionMetadataCredentials(context.Context, *FunctionMetadataCredentialsRequest) (*FunctionMetadataCredentialsResponse, error)
	ProvisionRegionalWorker(context.Context, *ProvisionWorkerRequest) (*ProvisionWorkerResponse, error)
	// the worker is now responsible for creating the full 302 redirect response for large responses, so it needs a way to retrieve the presigned download url
	RequestLargeResponseDownloadCredentials(context.Context, *LargeResponseDownloadCredentialsRequest) (*LargeResponseDownloadCredentialsResponse, error)
	mustEmbedUnimplementedWorkerServer()
}

// UnimplementedWorkerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWorkerServer struct{}

func (UnimplementedWorkerServer) ConnectOnce(context.Context, *WorkerConnect) (*WorkerConnectOnceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConnectOnce not implemented")
}
func (UnimplementedWorkerServer) RefreshLargeUploadCredentials(context.Context, *RefreshLargeUploadCredentialsRequest) (*RefreshLargeUploadCredentialsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RefreshLargeUploadCredentials not implemented")
}
func (UnimplementedWorkerServer) RefreshAssetDownloadCredentials(grpc.BidiStreamingServer[RefreshAssetDownloadCredentialsRequest, RefreshAssetDownloadCredentialsResponse]) error {
	return status.Error(codes.Unimplemented, "method RefreshAssetDownloadCredentials not implemented")
}
func (UnimplementedWorkerServer) MultipartLargeUploadCredentials(context.Context, *MultipartLargeUploadCredentialsRequest) (*MultipartLargeUploadCredentialsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MultipartLargeUploadCredentials not implemented")
}
func (UnimplementedWorkerServer) RequestArtifacts(context.Context, *ArtifactsRequest) (*ArtifactsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestArtifacts not implemented")
}
func (UnimplementedWorkerServer) StreamArtifacts(*ArtifactsRequest, grpc.ServerStreamingServer[StreamedArtifactFile]) error {
	return status.Error(codes.Unimplemented, "method StreamArtifacts not implemented")
}
func (UnimplementedWorkerServer) RequestInstanceCredentials(context.Context, *InstanceCredentialsRequest) (*InstanceCredentialsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestInstanceCredentials not implemented")
}
func (UnimplementedWorkerServer) RequestSecretCredentials(context.Context, *SecretCredentialsRequest) (*SecretCredentialsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestSecretCredentials not implemented")
}
func (UnimplementedWorkerServer) RequestFunctionMetadataCredentials(context.Context, *FunctionMetadataCredentialsRequest) (*FunctionMetadataCredentialsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestFunctionMetadataCredentials not implemented")
}
func (UnimplementedWorkerServer) ProvisionRegionalWorker(context.Context, *ProvisionWorkerRequest) (*ProvisionWorkerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ProvisionRegionalWorker not implemented")
}
func (UnimplementedWorkerServer) RequestLargeResponseDownloadCredentials(context.Context, *LargeResponseDownloadCredentialsRequest) (*LargeResponseDownloadCredentialsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestLargeResponseDownloadCredentials not implemented")
}
func (UnimplementedWorkerServer) mustEmbedUnimplementedWorkerServer() {}
func (UnimplementedWorkerServer) testEmbeddedByValue()                {}

// UnsafeWorkerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkerServer will
// result in compilation errors.
type UnsafeWorkerServer interface {
	mustEmbedUnimplementedWorkerServer()
}

func RegisterWorkerServer(s grpc.ServiceRegistrar, srv WorkerServer) {
	// If the following call panics, it indicates UnimplementedWorkerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Worker_ServiceDesc, srv)
}

func _Worker_ConnectOnce_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkerConnect)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServer).ConnectOnce(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Worker_ConnectOnce_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServer).ConnectOnce(ctx, req.(*WorkerConnect))
	}
	return interceptor(ctx, in, info, handler)
}

func _Worker_RefreshLargeUploadCredentials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshLargeUploadCredentialsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServer).RefreshLargeUploadCredentials(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Worker_RefreshLargeUploadCredentials_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServer).RefreshLargeUploadCredentials(ctx, req.(*RefreshLargeUploadCredentialsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Worker_RefreshAssetDownloadCredentials_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(WorkerServer).RefreshAssetDownloadCredentials(&grpc.GenericServerStream[RefreshAssetDownloadCredentialsRequest, RefreshAssetDownloadCredentialsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Worker_RefreshAssetDownloadCredentialsServer = grpc.BidiStreamingServer[RefreshAssetDownloadCredentialsRequest, RefreshAssetDownloadCredentialsResponse]

func _Worker_MultipartLargeUploadCredentials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MultipartLargeUploadCredentialsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServer).MultipartLargeUploadCredentials(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Worker_MultipartLargeUploadCredentials_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServer).MultipartLargeUploadCredentials(ctx, req.(*MultipartLargeUploadCredentialsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Worker_RequestArtifacts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArtifactsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServer).RequestArtifacts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Worker_RequestArtifacts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServer).RequestArtifacts(ctx, req.(*ArtifactsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Worker_StreamArtifacts_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ArtifactsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WorkerServer).StreamArtifacts(m, &grpc.GenericServerStream[ArtifactsRequest, StreamedArtifactFile]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Worker_StreamArtifactsServer = grpc.ServerStreamingServer[StreamedArtifactFile]

func _Worker_RequestInstanceCredentials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstanceCredentialsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServer).RequestInstanceCredentials(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Worker_RequestInstanceCredentials_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServer).RequestInstanceCredentials(ctx, req.(*InstanceCredentialsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Worker_RequestSecretCredentials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SecretCredentialsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServer).RequestSecretCredentials(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Worker_RequestSecretCredentials_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServer).RequestSecretCredentials(ctx, req.(*SecretCredentialsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Worker_RequestFunctionMetadataCredentials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FunctionMetadataCredentialsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServer).RequestFunctionMetadataCredentials(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Worker_RequestFunctionMetadataCredentials_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServer).RequestFunctionMetadataCredentials(ctx, req.(*FunctionMetadataCredentialsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Worker_ProvisionRegionalWorker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProvisionWorkerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServer).ProvisionRegionalWorker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Worker_ProvisionRegionalWorker_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServer).ProvisionRegionalWorker(ctx, req.(*ProvisionWorkerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Worker_RequestLargeResponseDownloadCredentials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LargeResponseDownloadCredentialsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServer).RequestLargeResponseDownloadCredentials(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Worker_RequestLargeResponseDownloadCredentials_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServer).RequestLargeResponseDownloadCredentials(ctx, req.(*LargeResponseDownloadCredentialsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Worker_ServiceDesc is the grpc.ServiceDesc for Worker service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Worker_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nvcf.Worker",
	HandlerType: (*WorkerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ConnectOnce",
			Handler:    _Worker_ConnectOnce_Handler,
		},
		{
			MethodName: "RefreshLargeUploadCredentials",
			Handler:    _Worker_RefreshLargeUploadCredentials_Handler,
		},
		{
			MethodName: "MultipartLargeUploadCredentials",
			Handler:    _Worker_MultipartLargeUploadCredentials_Handler,
		},
		{
			MethodName: "RequestArtifacts",
			Handler:    _Worker_RequestArtifacts_Handler,
		},
		{
			MethodName: "RequestInstanceCredentials",
			Handler:    _Worker_RequestInstanceCredentials_Handler,
		},
		{
			MethodName: "RequestSecretCredentials",
			Handler:    _Worker_RequestSecretCredentials_Handler,
		},
		{
			MethodName: "RequestFunctionMetadataCredentials",
			Handler:    _Worker_RequestFunctionMetadataCredentials_Handler,
		},
		{
			MethodName: "ProvisionRegionalWorker",
			Handler:    _Worker_ProvisionRegionalWorker_Handler,
		},
		{
			MethodName: "RequestLargeResponseDownloadCredentials",
			Handler:    _Worker_RequestLargeResponseDownloadCredentials_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RefreshAssetDownloadCredentials",
			Handler:       _Worker_RefreshAssetDownloadCredentials_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "StreamArtifacts",
			Handler:       _Worker_StreamArtifacts_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "nvcf.proto",
}

const (
	Proxy_AuthStatefulWork_FullMethodName = "/nvcf.Proxy/AuthStatefulWork"
)

// ProxyClient is the client API for Proxy service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProxyClient interface {
	AuthStatefulWork(ctx context.Context, in *ProxyAuthRequest, opts ...grpc.CallOption) (*ProxyAuthResponse, error)
}

type proxyClient struct {
	cc grpc.ClientConnInterface
}

func NewProxyClient(cc grpc.ClientConnInterface) ProxyClient {
	return &proxyClient{cc}
}

func (c *proxyClient) AuthStatefulWork(ctx context.Context, in *ProxyAuthRequest, opts ...grpc.CallOption) (*ProxyAuthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProxyAuthResponse)
	err := c.cc.Invoke(ctx, Proxy_AuthStatefulWork_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProxyServer is the server API for Proxy service.
// All implementations must embed UnimplementedProxyServer
// for forward compatibility.
type ProxyServer interface {
	AuthStatefulWork(context.Context, *ProxyAuthRequest) (*ProxyAuthResponse, error)
	mustEmbedUnimplementedProxyServer()
}

// UnimplementedProxyServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProxyServer struct{}

func (UnimplementedProxyServer) AuthStatefulWork(context.Context, *ProxyAuthRequest) (*ProxyAuthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AuthStatefulWork not implemented")
}
func (UnimplementedProxyServer) mustEmbedUnimplementedProxyServer() {}
func (UnimplementedProxyServer) testEmbeddedByValue()               {}

// UnsafeProxyServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProxyServer will
// result in compilation errors.
type UnsafeProxyServer interface {
	mustEmbedUnimplementedProxyServer()
}

func RegisterProxyServer(s grpc.ServiceRegistrar, srv ProxyServer) {
	// If the following call panics, it indicates UnimplementedProxyServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Proxy_ServiceDesc, srv)
}

func _Proxy_AuthStatefulWork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProxyAuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyServer).AuthStatefulWork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Proxy_AuthStatefulWork_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyServer).AuthStatefulWork(ctx, req.(*ProxyAuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Proxy_ServiceDesc is the grpc.ServiceDesc for Proxy service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Proxy_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nvcf.Proxy",
	HandlerType: (*ProxyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AuthStatefulWork",
			Handler:    _Proxy_AuthStatefulWork_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nvcf.proto",
}

const (
	Invocation_AuthClientInvocation_FullMethodName = "/nvcf.Invocation/AuthClientInvocation"
)

// InvocationClient is the client API for Invocation service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InvocationClient interface {
	AuthClientInvocation(ctx context.Context, in *ClientInvokeRequest, opts ...grpc.CallOption) (*ClientInvokeResponse, error)
}

type invocationClient struct {
	cc grpc.ClientConnInterface
}

func NewInvocationClient(cc grpc.ClientConnInterface) InvocationClient {
	return &invocationClient{cc}
}

func (c *invocationClient) AuthClientInvocation(ctx context.Context, in *ClientInvokeRequest, opts ...grpc.CallOption) (*ClientInvokeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClientInvokeResponse)
	err := c.cc.Invoke(ctx, Invocation_AuthClientInvocation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InvocationServer is the server API for Invocation service.
// All implementations must embed UnimplementedInvocationServer
// for forward compatibility.
type InvocationServer interface {
	AuthClientInvocation(context.Context, *ClientInvokeRequest) (*ClientInvokeResponse, error)
	mustEmbedUnimplementedInvocationServer()
}

// UnimplementedInvocationServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInvocationServer struct{}

func (UnimplementedInvocationServer) AuthClientInvocation(context.Context, *ClientInvokeRequest) (*ClientInvokeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AuthClientInvocation not implemented")
}
func (UnimplementedInvocationServer) mustEmbedUnimplementedInvocationServer() {}
func (UnimplementedInvocationServer) testEmbeddedByValue()                    {}

// UnsafeInvocationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InvocationServer will
// result in compilation errors.
type UnsafeInvocationServer interface {
	mustEmbedUnimplementedInvocationServer()
}

func RegisterInvocationServer(s grpc.ServiceRegistrar, srv InvocationServer) {
	// If the following call panics, it indicates UnimplementedInvocationServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Invocation_ServiceDesc, srv)
}

func _Invocation_AuthClientInvocation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientInvokeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InvocationServer).AuthClientInvocation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Invocation_AuthClientInvocation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InvocationServer).AuthClientInvocation(ctx, req.(*ClientInvokeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Invocation_ServiceDesc is the grpc.ServiceDesc for Invocation service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Invocation_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nvcf.Invocation",
	HandlerType: (*InvocationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AuthClientInvocation",
			Handler:    _Invocation_AuthClientInvocation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nvcf.proto",
}

const (
	Skyway_AuthGetLogs_FullMethodName        = "/nvcf.Skyway/AuthGetLogs"
	Skyway_AuthExecuteCommand_FullMethodName = "/nvcf.Skyway/AuthExecuteCommand"
	Skyway_AuthListInstances_FullMethodName  = "/nvcf.Skyway/AuthListInstances"
)

// SkywayClient is the client API for Skyway service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SkywayClient interface {
	AuthGetLogs(ctx context.Context, in *SkywayAuthRequest, opts ...grpc.CallOption) (*SkywayAuthResponse, error)
	AuthExecuteCommand(ctx context.Context, in *SkywayAuthRequest, opts ...grpc.CallOption) (*SkywayAuthResponse, error)
	AuthListInstances(ctx context.Context, in *SkywayAuthRequest, opts ...grpc.CallOption) (*SkywayAuthResponse, error)
}

type skywayClient struct {
	cc grpc.ClientConnInterface
}

func NewSkywayClient(cc grpc.ClientConnInterface) SkywayClient {
	return &skywayClient{cc}
}

func (c *skywayClient) AuthGetLogs(ctx context.Context, in *SkywayAuthRequest, opts ...grpc.CallOption) (*SkywayAuthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SkywayAuthResponse)
	err := c.cc.Invoke(ctx, Skyway_AuthGetLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *skywayClient) AuthExecuteCommand(ctx context.Context, in *SkywayAuthRequest, opts ...grpc.CallOption) (*SkywayAuthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SkywayAuthResponse)
	err := c.cc.Invoke(ctx, Skyway_AuthExecuteCommand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *skywayClient) AuthListInstances(ctx context.Context, in *SkywayAuthRequest, opts ...grpc.CallOption) (*SkywayAuthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SkywayAuthResponse)
	err := c.cc.Invoke(ctx, Skyway_AuthListInstances_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SkywayServer is the server API for Skyway service.
// All implementations must embed UnimplementedSkywayServer
// for forward compatibility.
type SkywayServer interface {
	AuthGetLogs(context.Context, *SkywayAuthRequest) (*SkywayAuthResponse, error)
	AuthExecuteCommand(context.Context, *SkywayAuthRequest) (*SkywayAuthResponse, error)
	AuthListInstances(context.Context, *SkywayAuthRequest) (*SkywayAuthResponse, error)
	mustEmbedUnimplementedSkywayServer()
}

// UnimplementedSkywayServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSkywayServer struct{}

func (UnimplementedSkywayServer) AuthGetLogs(context.Context, *SkywayAuthRequest) (*SkywayAuthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AuthGetLogs not implemented")
}
func (UnimplementedSkywayServer) AuthExecuteCommand(context.Context, *SkywayAuthRequest) (*SkywayAuthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AuthExecuteCommand not implemented")
}
func (UnimplementedSkywayServer) AuthListInstances(context.Context, *SkywayAuthRequest) (*SkywayAuthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AuthListInstances not implemented")
}
func (UnimplementedSkywayServer) mustEmbedUnimplementedSkywayServer() {}
func (UnimplementedSkywayServer) testEmbeddedByValue()                {}

// UnsafeSkywayServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SkywayServer will
// result in compilation errors.
type UnsafeSkywayServer interface {
	mustEmbedUnimplementedSkywayServer()
}

func RegisterSkywayServer(s grpc.ServiceRegistrar, srv SkywayServer) {
	// If the following call panics, it indicates UnimplementedSkywayServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Skyway_ServiceDesc, srv)
}

func _Skyway_AuthGetLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SkywayAuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkywayServer).AuthGetLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Skyway_AuthGetLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkywayServer).AuthGetLogs(ctx, req.(*SkywayAuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Skyway_AuthExecuteCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SkywayAuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkywayServer).AuthExecuteCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Skyway_AuthExecuteCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkywayServer).AuthExecuteCommand(ctx, req.(*SkywayAuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Skyway_AuthListInstances_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SkywayAuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkywayServer).AuthListInstances(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Skyway_AuthListInstances_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkywayServer).AuthListInstances(ctx, req.(*SkywayAuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Skyway_ServiceDesc is the grpc.ServiceDesc for Skyway service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Skyway_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nvcf.Skyway",
	HandlerType: (*SkywayServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AuthGetLogs",
			Handler:    _Skyway_AuthGetLogs_Handler,
		},
		{
			MethodName: "AuthExecuteCommand",
			Handler:    _Skyway_AuthExecuteCommand_Handler,
		},
		{
			MethodName: "AuthListInstances",
			Handler:    _Skyway_AuthListInstances_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nvcf.proto",
}

const (
	RateLimit_RateLimitPolicy_FullMethodName = "/nvcf.RateLimit/RateLimitPolicy"
)

// RateLimitClient is the client API for RateLimit service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RateLimitClient interface {
	RateLimitPolicy(ctx context.Context, in *RateLimitPolicyRequest, opts ...grpc.CallOption) (*RateLimitPolicyResponse, error)
}

type rateLimitClient struct {
	cc grpc.ClientConnInterface
}

func NewRateLimitClient(cc grpc.ClientConnInterface) RateLimitClient {
	return &rateLimitClient{cc}
}

func (c *rateLimitClient) RateLimitPolicy(ctx context.Context, in *RateLimitPolicyRequest, opts ...grpc.CallOption) (*RateLimitPolicyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RateLimitPolicyResponse)
	err := c.cc.Invoke(ctx, RateLimit_RateLimitPolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RateLimitServer is the server API for RateLimit service.
// All implementations must embed UnimplementedRateLimitServer
// for forward compatibility.
type RateLimitServer interface {
	RateLimitPolicy(context.Context, *RateLimitPolicyRequest) (*RateLimitPolicyResponse, error)
	mustEmbedUnimplementedRateLimitServer()
}

// UnimplementedRateLimitServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRateLimitServer struct{}

func (UnimplementedRateLimitServer) RateLimitPolicy(context.Context, *RateLimitPolicyRequest) (*RateLimitPolicyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RateLimitPolicy not implemented")
}
func (UnimplementedRateLimitServer) mustEmbedUnimplementedRateLimitServer() {}
func (UnimplementedRateLimitServer) testEmbeddedByValue()                   {}

// UnsafeRateLimitServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RateLimitServer will
// result in compilation errors.
type UnsafeRateLimitServer interface {
	mustEmbedUnimplementedRateLimitServer()
}

func RegisterRateLimitServer(s grpc.ServiceRegistrar, srv RateLimitServer) {
	// If the following call panics, it indicates UnimplementedRateLimitServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RateLimit_ServiceDesc, srv)
}

func _RateLimit_RateLimitPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RateLimitPolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RateLimitServer).RateLimitPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RateLimit_RateLimitPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RateLimitServer).RateLimitPolicy(ctx, req.(*RateLimitPolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RateLimit_ServiceDesc is the grpc.ServiceDesc for RateLimit service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RateLimit_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nvcf.RateLimit",
	HandlerType: (*RateLimitServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RateLimitPolicy",
			Handler:    _RateLimit_RateLimitPolicy_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nvcf.proto",
}

const (
	Autoscaler_RequestDeploymentConfiguration_FullMethodName = "/nvcf.Autoscaler/RequestDeploymentConfiguration"
)

// AutoscalerClient is the client API for Autoscaler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AutoscalerClient interface {
	RequestDeploymentConfiguration(ctx context.Context, in *DeploymentConfigurationRequest, opts ...grpc.CallOption) (*DeploymentConfigurationResponse, error)
}

type autoscalerClient struct {
	cc grpc.ClientConnInterface
}

func NewAutoscalerClient(cc grpc.ClientConnInterface) AutoscalerClient {
	return &autoscalerClient{cc}
}

func (c *autoscalerClient) RequestDeploymentConfiguration(ctx context.Context, in *DeploymentConfigurationRequest, opts ...grpc.CallOption) (*DeploymentConfigurationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeploymentConfigurationResponse)
	err := c.cc.Invoke(ctx, Autoscaler_RequestDeploymentConfiguration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AutoscalerServer is the server API for Autoscaler service.
// All implementations must embed UnimplementedAutoscalerServer
// for forward compatibility.
type AutoscalerServer interface {
	RequestDeploymentConfiguration(context.Context, *DeploymentConfigurationRequest) (*DeploymentConfigurationResponse, error)
	mustEmbedUnimplementedAutoscalerServer()
}

// UnimplementedAutoscalerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAutoscalerServer struct{}

func (UnimplementedAutoscalerServer) RequestDeploymentConfiguration(context.Context, *DeploymentConfigurationRequest) (*DeploymentConfigurationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestDeploymentConfiguration not implemented")
}
func (UnimplementedAutoscalerServer) mustEmbedUnimplementedAutoscalerServer() {}
func (UnimplementedAutoscalerServer) testEmbeddedByValue()                    {}

// UnsafeAutoscalerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AutoscalerServer will
// result in compilation errors.
type UnsafeAutoscalerServer interface {
	mustEmbedUnimplementedAutoscalerServer()
}

func RegisterAutoscalerServer(s grpc.ServiceRegistrar, srv AutoscalerServer) {
	// If the following call panics, it indicates UnimplementedAutoscalerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Autoscaler_ServiceDesc, srv)
}

func _Autoscaler_RequestDeploymentConfiguration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeploymentConfigurationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutoscalerServer).RequestDeploymentConfiguration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Autoscaler_RequestDeploymentConfiguration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutoscalerServer).RequestDeploymentConfiguration(ctx, req.(*DeploymentConfigurationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Autoscaler_ServiceDesc is the grpc.ServiceDesc for Autoscaler service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Autoscaler_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nvcf.Autoscaler",
	HandlerType: (*AutoscalerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestDeploymentConfiguration",
			Handler:    _Autoscaler_RequestDeploymentConfiguration_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nvcf.proto",
}
