# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

version: "2"
run:
  modules-download-mode: vendor
  tests: false
  allow-parallel-runners: true
linters:
  enable:
    - goheader
  settings:
    goheader:
      template-path: .goheader.tmpl
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
      - vendor$
issues:
  fix: true
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: zz_generated\..*\.go
      linters:
        - goheader
    - path: generated\..*\.go
      linters:
        - goheader
    - path: vendor/
      linters:
        - goheader
formatters:
  enable:
    - gci
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/NVIDIA/nvcf/src/compute-plane-services/image-credential-helper)
        - blank
        - dot
        - alias
        - localmodule
      no-inline-comments: true
      no-prefix-comments: true
      custom-order: true
      no-lex-order: true
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
      - vendor$
