#! /usr/bin/env bash

# This script exit non-zero if docs codegen creates uncommitted changes.
set -eu -o pipefail
repo_root="$(cd "$(dirname "$0")/.." && pwd)"
cd "${repo_root}"
make docs-update
git status
git diff --ignore-space-at-eol --exit-code
