#! /usr/bin/env bash
#
# This script exit non-zero if openapi generated code has uncommitted changes.
set -eu -o pipefail
repo_root="$(cd "$(dirname "$0")/.." && pwd)"
cd "${repo_root}"
make openapigen-update
git status
git diff --ignore-space-at-eol --exit-code
