//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// SPDX-FileCopyrightText: Copyright (c) NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by deepcopy-gen. DO NOT EDIT.

package common

import (
	json "encoding/json"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CacheLaunchSpecification) DeepCopyInto(out *CacheLaunchSpecification) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CacheLaunchSpecification.
func (in *CacheLaunchSpecification) DeepCopy() *CacheLaunchSpecification {
	if in == nil {
		return nil
	}
	out := new(CacheLaunchSpecification)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CreationQueueMessageMetadata) DeepCopyInto(out *CreationQueueMessageMetadata) {
	*out = *in
	if in.TraceState != nil {
		in, out := &in.TraceState, &out.TraceState
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CreationQueueMessageMetadata.
func (in *CreationQueueMessageMetadata) DeepCopy() *CreationQueueMessageMetadata {
	if in == nil {
		return nil
	}
	out := new(CreationQueueMessageMetadata)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HelmAuthConfig) DeepCopyInto(out *HelmAuthConfig) {
	*out = *in
	if in.K8sSecrets != nil {
		in, out := &in.K8sSecrets, &out.K8sSecrets
		*out = make([]RegistryAuthSecret, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HelmAuthConfig.
func (in *HelmAuthConfig) DeepCopy() *HelmAuthConfig {
	if in == nil {
		return nil
	}
	out := new(HelmAuthConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HelmChartLaunchSpecification) DeepCopyInto(out *HelmChartLaunchSpecification) {
	*out = *in
	if in.Values != nil {
		in, out := &in.Values, &out.Values
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HelmChartLaunchSpecification.
func (in *HelmChartLaunchSpecification) DeepCopy() *HelmChartLaunchSpecification {
	if in == nil {
		return nil
	}
	out := new(HelmChartLaunchSpecification)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HelmConfig) DeepCopyInto(out *HelmConfig) {
	*out = *in
	if in.ServicePort != nil {
		in, out := &in.ServicePort, &out.ServicePort
		*out = new(int32)
		**out = **in
	}
	if in.Values != nil {
		in, out := &in.Values, &out.Values
		*out = make(json.RawMessage, len(*in))
		copy(*out, *in)
	}
	in.AuthConfig.DeepCopyInto(&out.AuthConfig)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HelmConfig.
func (in *HelmConfig) DeepCopy() *HelmConfig {
	if in == nil {
		return nil
	}
	out := new(HelmConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RegistryAuth) DeepCopyInto(out *RegistryAuth) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RegistryAuth.
func (in *RegistryAuth) DeepCopy() *RegistryAuth {
	if in == nil {
		return nil
	}
	out := new(RegistryAuth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RegistryAuthConfig) DeepCopyInto(out *RegistryAuthConfig) {
	*out = *in
	if in.K8sSecrets != nil {
		in, out := &in.K8sSecrets, &out.K8sSecrets
		*out = make([]RegistryAuthSecret, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RegistryAuthConfig.
func (in *RegistryAuthConfig) DeepCopy() *RegistryAuthConfig {
	if in == nil {
		return nil
	}
	out := new(RegistryAuthConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RegistryAuthSecret) DeepCopyInto(out *RegistryAuthSecret) {
	*out = *in
	if in.Auths != nil {
		in, out := &in.Auths, &out.Auths
		*out = make(map[string]RegistryAuth, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RegistryAuthSecret.
func (in *RegistryAuthSecret) DeepCopy() *RegistryAuthSecret {
	if in == nil {
		return nil
	}
	out := new(RegistryAuthSecret)
	in.DeepCopyInto(out)
	return out
}
