# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

# Notary Service values for standalone installation
# Replace <REGISTRY> and <REPOSITORY> with your container registry settings.

notary:
  fullnameOverride: notary-service
  image:
    registry: "<REGISTRY>"
    repository: "<REPOSITORY>/notary-service"

  # Uncomment for node selectors
  # nodeSelector:
  #   nvcf.nvidia.com/workload: control-plane
