/*
SPDX-FileCopyrightText: Copyright (c) NVIDIA CORPORATION & AFFILIATES. All rights reserved.
SPDX-License-Identifier: Apache-2.0

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by mockery v2.16.0. DO NOT EDIT.

package auth

import mock "github.com/stretchr/testify/mock"

// MockAuthnRefresher is an autogenerated mock type for the AuthnRefresher type
type MockAuthnRefresher struct {
	mock.Mock
}

// Update provides a mock function with given fields: creds
func (_m *MockAuthnRefresher) Update(creds *ClientCredentials) {
	_m.Called(creds)
}

type mockConstructorTestingTNewMockAuthnRefresher interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockAuthnRefresher creates a new instance of MockAuthnRefresher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockAuthnRefresher(t mockConstructorTestingTNewMockAuthnRefresher) *MockAuthnRefresher {
	mock := &MockAuthnRefresher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
