// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	nvcfv1 "github.com/NVIDIA/nvcf/src/compute-plane-services/nvca/pkg/apis/nvcf/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// NVCFBackendLister helps list NVCFBackends.
// All objects returned here must be treated as read-only.
type NVCFBackendLister interface {
	// List lists all NVCFBackends in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*nvcfv1.NVCFBackend, err error)
	// NVCFBackends returns an object that can list and get NVCFBackends.
	NVCFBackends(namespace string) NVCFBackendNamespaceLister
	NVCFBackendListerExpansion
}

// nVCFBackendLister implements the NVCFBackendLister interface.
type nVCFBackendLister struct {
	listers.ResourceIndexer[*nvcfv1.NVCFBackend]
}

// NewNVCFBackendLister returns a new NVCFBackendLister.
func NewNVCFBackendLister(indexer cache.Indexer) NVCFBackendLister {
	return &nVCFBackendLister{listers.New[*nvcfv1.NVCFBackend](indexer, nvcfv1.Resource("nvcfbackend"))}
}

// NVCFBackends returns an object that can list and get NVCFBackends.
func (s *nVCFBackendLister) NVCFBackends(namespace string) NVCFBackendNamespaceLister {
	return nVCFBackendNamespaceLister{listers.NewNamespaced[*nvcfv1.NVCFBackend](s.ResourceIndexer, namespace)}
}

// NVCFBackendNamespaceLister helps list and get NVCFBackends.
// All objects returned here must be treated as read-only.
type NVCFBackendNamespaceLister interface {
	// List lists all NVCFBackends in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*nvcfv1.NVCFBackend, err error)
	// Get retrieves the NVCFBackend from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*nvcfv1.NVCFBackend, error)
	NVCFBackendNamespaceListerExpansion
}

// nVCFBackendNamespaceLister implements the NVCFBackendNamespaceLister
// interface.
type nVCFBackendNamespaceLister struct {
	listers.ResourceIndexer[*nvcfv1.NVCFBackend]
}
