/*
SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
SPDX-License-Identifier: Apache-2.0

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package metrics

import (
	"github.com/NVIDIA/nvcf/src/libraries/go/worker/metrics"

	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promauto"
)

const (
	NgcClientNamespace = metrics.NvctRootNamespace + "_ngc_client"
)

var (
	ResultCounter = promauto.NewCounter(
		prometheus.CounterOpts{
			Namespace: metrics.NvctRootNamespace,
			Name:      "result_total",
			Help:      "total result generated by task container",
		})

	ResultUploadBytesCounter = promauto.NewCounter(
		prometheus.CounterOpts{
			Namespace: metrics.NvctRootNamespace,
			Name:      "upload_bytes_total",
			Help:      "total size of all uploaded results",
		})

	ResultUploadFailureCounter = promauto.NewCounter(
		prometheus.CounterOpts{
			Namespace: metrics.NvctRootNamespace,
			Name:      "upload_failure_total",
			Help:      "total number of uploading results failures",
		})

	NgcClientResponseCodeCounter = promauto.NewCounterVec(
		prometheus.CounterOpts{
			Namespace: NgcClientNamespace,
			Name:      "response_code_total",
			Help:      "total number of NGC API response codes by action name",
		}, []string{"status_code", "action"})
)
