// SPDX-FileCopyrightText: Copyright (c) NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestRunWritesExpectedLocalOutputs(t *testing.T) {
	tmp := t.TempDir()

	writeTestFile(t, filepath.Join(tmp, "imports.yaml"), `imports:
  - path: app
    repo: https://example.com/app.git
`)

	writeTestFile(t, filepath.Join(tmp, "app", "go.mod"), `module example.com/app

go 1.22

require github.com/pkg/errors v0.9.1
`)
	writeTestFile(t, filepath.Join(tmp, "app", "vendor", "modules.txt"), `# github.com/pkg/errors v0.9.1
## explicit
`)
	writeTestFile(t, filepath.Join(tmp, "app", "vendor", "github.com", "pkg", "errors", "LICENSE"), "BSD 2-Clause License\n")

	writeTestFile(t, filepath.Join(tmp, "app", "Cargo.toml"), `[dependencies]
serde = "1"
serde_json = { version = "1.0" }
`)

	writeTestFile(t, filepath.Join(tmp, "app", "pyproject.toml"), `[project]
dependencies = ["Requests>=2.0"]

[project.optional-dependencies]
dev = ["PyYAML==6.0"]
`)

	writeTestFile(t, filepath.Join(tmp, "app", "pom.xml"), `<project>
  <modelVersion>4.0.0</modelVersion>
  <properties>
    <jackson.version>2.17.0</jackson.version>
  </properties>
  <dependencies>
    <dependency>
      <groupId>com.fasterxml.jackson.core</groupId>
      <artifactId>jackson-databind</artifactId>
      <version>${jackson.version}</version>
    </dependency>
    <dependency>
      <groupId>org.example</groupId>
      <artifactId>skip-test</artifactId>
      <version>1.0.0</version>
      <scope>test</scope>
    </dependency>
  </dependencies>
</project>
`)

	writeTestFile(t, filepath.Join(tmp, "app", "Chart.yaml"), `apiVersion: v2
name: app
version: 0.1.0
dependencies:
  - name: chart-from-yaml
    version: 1.0.0
    repository: https://charts.example.com
`)
	writeTestFile(t, filepath.Join(tmp, "app", "Chart.lock"), `dependencies:
  - name: chart-from-lock
    version: 2.0.0
    repository: https://charts.example.com
`)
	writeTestFile(t, filepath.Join(tmp, "dependencies-java.md"), "manual-java-snapshot\n")

	t.Setenv("REPO_ROOT", tmp)
	t.Setenv("COLLECT_DEPS_NO_PYPI", "1")
	t.Setenv("COLLECT_DEPS_NO_CRATES_IO", "1")
	t.Setenv("COLLECT_DEPS_NO_MAVEN_CENTRAL", "1")
	t.Setenv("COLLECT_DEPS_NO_HELM_SHOW", "1")
	t.Setenv("COLLECT_DEPS_NO_GITHUB", "1")
	t.Setenv("COLLECT_DEPS_NO_GO_LIST", "1")
	t.Setenv("COLLECT_DEPS_NO_GO_MOD_DOWNLOAD", "1")

	oldArgs := os.Args
	t.Cleanup(func() { os.Args = oldArgs })
	os.Args = []string{"collect-dependencies", "--language", "all"}

	resetGlobalsForTest()
	if err := run(); err != nil {
		t.Fatalf("run failed: %v", err)
	}

	assertFileContains(t, filepath.Join(tmp, "dependencies.md"), "Generated by `go run ./tools/collect-dependencies`.")
	assertFileContains(t, filepath.Join(tmp, "dependencies.md"), "See [`tools/collect-dependencies/README.md`](tools/collect-dependencies/README.md) for license caveats.")
	assertFileContains(t, filepath.Join(tmp, "dependencies.md"), "## BSD-2-Clause")
	assertFileContains(t, filepath.Join(tmp, "dependencies.md"), "- `Go`: `github.com/pkg/errors`")
	assertFileContains(t, filepath.Join(tmp, "dependencies.md"), "## Unresolved")
	assertFileContains(t, filepath.Join(tmp, "dependencies.md"), "- `Rust`: `serde 1` - _(no license resolved - install `cargo` for `cargo metadata`, or allow crates.io fallback; see tools/collect-dependencies/README.md)_")
	assertFileContains(t, filepath.Join(tmp, "dependencies.md"), "- `Rust`: `serde_json 1.0` - _(no license resolved - install `cargo` for `cargo metadata`, or allow crates.io fallback; see tools/collect-dependencies/README.md)_")
	assertFileContains(t, filepath.Join(tmp, "dependencies.md"), "- `Python`: `PyYAML==6.0` - _(PyPI lookup disabled)_")
	assertFileContains(t, filepath.Join(tmp, "dependencies.md"), "- `Python`: `Requests>=2.0` - _(PyPI lookup disabled)_")
	assertFileContains(t, filepath.Join(tmp, "dependencies.md"), "- `Java`: `com.fasterxml.jackson.core:jackson-databind:2.17.0` - _(Maven Central lookup disabled)_")
	assertFileContains(t, filepath.Join(tmp, "dependencies.md"), "- `Helm`: `chart-from-lock 2.0.0 @ https://charts.example.com` - _(no license resolved - set `COLLECT_DEPS_NO_HELM_SHOW=1` to skip `helm show chart`, or provide chart metadata / source repo license hints)_")

	assertFileEquals(t, filepath.Join(tmp, "dependencies-java.md"), "manual-java-snapshot\n")
	assertFileNotContains(t, filepath.Join(tmp, "dependencies.md"), "chart-from-yaml")
	assertFileMissing(t, filepath.Join(tmp, "dependencies-go.md"))
	assertFileMissing(t, filepath.Join(tmp, "dependencies-rust.md"))
	assertFileMissing(t, filepath.Join(tmp, "dependencies-python.md"))
	assertFileMissing(t, filepath.Join(tmp, "dependencies-helm.md"))
}

func TestNormalizeLicenseGroupKeepsMPLVersion(t *testing.T) {
	if got := normalizeLicenseGroup("Mozilla Public License 1.1"); got != "MPL-1.1" {
		t.Fatalf("normalizeLicenseGroup returned %q, want MPL-1.1", got)
	}
	if got := normalizeLicenseGroup("MPL 2.0"); got != "MPL-2.0" {
		t.Fatalf("normalizeLicenseGroup returned %q, want MPL-2.0", got)
	}
}

func TestLicenseFromPlainDirSkipsNonLicenseFallbackText(t *testing.T) {
	tmp := t.TempDir()
	writeTestFile(t, filepath.Join(tmp, "LICENSE"), "Permalink:\nhttps://example.com/license\n")

	if got := licenseFromPlainDir(tmp); got != "" {
		t.Fatalf("licenseFromPlainDir returned %q, want empty string", got)
	}
}

func TestLicenseFromPlainDirKeepsLicenseLikeFallbackText(t *testing.T) {
	tmp := t.TempDir()
	writeTestFile(t, filepath.Join(tmp, "LICENSE"), "BSD 2-Clause License\n")

	if got := licenseFromPlainDir(tmp); got != "BSD-2-Clause" {
		t.Fatalf("licenseFromPlainDir returned %q, want BSD-2-Clause", got)
	}
}

func TestImportPathsFromManifestIncludesNativeRoots(t *testing.T) {
	tmp := t.TempDir()
	repoRoot = tmp

	writeTestFile(t, filepath.Join(tmp, "imports.yaml"), `imports:
  - path: src/libraries/go/lib
    authoritative_source: native
  - path: src/services/demo
    repo: https://example.com/demo.git
    commit: deadbeef
`)

	got, err := importPathsFromManifest(filepath.Join(tmp, "imports.yaml"))
	if err != nil {
		t.Fatalf("importPathsFromManifest failed: %v", err)
	}

	want := []string{
		filepath.Join(tmp, "src/libraries/go/lib"),
		filepath.Join(tmp, "src/services/demo"),
	}
	if len(got) != len(want) {
		t.Fatalf("importPathsFromManifest returned %d paths, want %d (%v)", len(got), len(want), got)
	}
	for i := range want {
		if got[i] != want[i] {
			t.Fatalf("importPathsFromManifest path[%d] = %q, want %q", i, got[i], want[i])
		}
	}
}

func writeTestFile(t *testing.T, path, content string) {
	t.Helper()
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatalf("mkdir %s: %v", path, err)
	}
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatalf("write %s: %v", path, err)
	}
}

func assertFileContains(t *testing.T, path, needle string) {
	t.Helper()
	raw, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read %s: %v", path, err)
	}
	if !strings.Contains(string(raw), needle) {
		t.Fatalf("%s does not contain %q\n%s", path, needle, string(raw))
	}
}

func assertFileNotContains(t *testing.T, path, needle string) {
	t.Helper()
	raw, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read %s: %v", path, err)
	}
	if strings.Contains(string(raw), needle) {
		t.Fatalf("%s unexpectedly contains %q\n%s", path, needle, string(raw))
	}
}

func assertFileMissing(t *testing.T, path string) {
	t.Helper()
	if _, err := os.Stat(path); !os.IsNotExist(err) {
		t.Fatalf("expected %s to be missing, got err=%v", path, err)
	}
}

func assertFileEquals(t *testing.T, path, want string) {
	t.Helper()
	raw, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read %s: %v", path, err)
	}
	if string(raw) != want {
		t.Fatalf("%s content mismatch\nwant:\n%s\ngot:\n%s", path, want, string(raw))
	}
}

func resetGlobalsForTest() {
	repoRoot = ""
	cargoMissingLogged = false
	githubLicenseWarned = false
	githubAuthLogged = false
	goListHintLogged = false
	goModDownloadHintLogged = false
	helmMissingLogged = false
}
