// SPDX-FileCopyrightText: Copyright (c) NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package main

import (
	"flag"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
)

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func run() error {
	parsed, err := parseArgs(os.Args[1:])
	if err != nil {
		return err
	}

	repoRoot, err = findRepoRoot()
	if err != nil {
		return err
	}

	requestedLangs := requestedLanguages(parsed.Language)
	langs := map[string]bool{}
	for lang := range requestedLangs {
		langs[lang] = true
	}

	manifestPath := filepath.Join(repoRoot, "imports.yaml")
	importRoots, err := importPathsFromManifest(manifestPath)
	if err != nil {
		return err
	}

	all := dependencyScan{
		Go:     map[string]struct{}{},
		Rust:   map[string]struct{}{},
		Python: map[string]struct{}{},
		Java:   map[string]struct{}{},
		Helm:   map[string]struct{}{},
	}

	for _, root := range importRoots {
		scan, err := scanTree(root, langs)
		if err != nil {
			return err
		}
		mergeSet(all.Go, scan.Go)
		mergeSet(all.Rust, scan.Rust)
		mergeSet(all.Python, scan.Python)
		mergeSet(all.Java, scan.Java)
	}

	if langs["helm"] {
		helmDeps, err := collectHelmDependencies(importRoots)
		if err != nil {
			return err
		}
		mergeSet(all.Helm, helmDeps)
	}

	goLicenses := map[string]map[string]struct{}{}
	if langs["go"] {
		maybeVendorGoModules(importRoots)
		for _, root := range importRoots {
			mergeLicenseMap(goLicenses, collectGoLicensesFromVendor(root))
		}
		goModuleDirs := findGoModuleDirs(importRoots)
		enrichGoLicensesFromGoModuleList(all.Go, goLicenses, goModuleDirs)
		enrichGoLicensesFromGoModDownload(all.Go, goLicenses, goModuleDirs)
		enrichGoLicensesFromGitHub(all.Go, goLicenses)
	}

	rustLicenses := map[string]map[string]struct{}{}
	if langs["rust"] {
		rustLicenses = collectRustLicenses(importRoots)
		if !envBool("COLLECT_DEPS_NO_CRATES_IO") {
			cratesCache := map[string]*string{}
			for _, stem := range sortedCrateStems(all.Rust) {
				if rustLicenseForCrate(rustLicenses, stem) != nil {
					continue
				}
				if lic := cratesIOLicense(stem, cratesCache); lic != "" {
					for _, key := range rustNameKeys(stem) {
						addLicense(rustLicenses, key, lic)
					}
				}
			}
		}
	}

	usePyPI := langs["python"] && !envBool("COLLECT_DEPS_NO_PYPI")
	pypiCache := map[string]*string{}

	useMavenCentral := langs["java"] && !envBool("COLLECT_DEPS_NO_MAVEN_CENTRAL")
	mavenSearchCache := map[string]*string{}
	mavenPOMCache := map[string]*string{}

	helmLicenses := map[string]map[string]struct{}{}
	if langs["helm"] {
		helmLicenses = collectHelmLicenses(all.Helm)
	}

	header := "Generated by `go run ./tools/collect-dependencies`. Refresh: `go run ./tools/collect-dependencies`. See [`tools/collect-dependencies/README.md`](tools/collect-dependencies/README.md) for license caveats.\n\n"

	summary := []string{}
	nonJavaRows := []dependencyRow{}
	nonJavaSummary := []string{}
	if langs["go"] {
		rows := buildGoRows(all.Go, goLicenses)
		nonJavaRows = append(nonJavaRows, rows...)
		nonJavaSummary = append(nonJavaSummary, fmt.Sprintf("Go %d modules", len(rows)))
	}

	if langs["rust"] {
		rows, rowCount := buildRustRows(all.Rust, rustLicenses)
		nonJavaRows = append(nonJavaRows, rows...)
		nonJavaSummary = append(nonJavaSummary, fmt.Sprintf("Rust %d crates (%d Cargo.toml lines)", rowCount, len(all.Rust)))
	}

	if langs["python"] {
		rows, rowCount := buildPythonRows(all.Python, usePyPI, pypiCache)
		nonJavaRows = append(nonJavaRows, rows...)
		nonJavaSummary = append(nonJavaSummary, fmt.Sprintf("Python %d packages (%d requirement lines)", rowCount, len(all.Python)))
	}

	if langs["java"] {
		rows, rowCount := buildJavaRows(all.Java, useMavenCentral, mavenSearchCache, mavenPOMCache)
		nonJavaRows = append(nonJavaRows, rows...)
		nonJavaSummary = append(nonJavaSummary, fmt.Sprintf("Java %d coordinates (%d POM lines)", rowCount, len(all.Java)))
	}

	if langs["helm"] {
		rows, rowCount := buildHelmRows(all.Helm, helmLicenses)
		nonJavaRows = append(nonJavaRows, rows...)
		nonJavaSummary = append(nonJavaSummary, fmt.Sprintf("Helm %d charts (%d dependency specs)", rowCount, len(all.Helm)))
	}

	if len(nonJavaRows) > 0 {
		lines := renderGroupedDependencyRows(nonJavaRows)
		if err := writeMarkdown(filepath.Join(repoRoot, "dependencies.md"), header, lines); err != nil {
			return err
		}
		summary = append(summary, fmt.Sprintf("dependencies.md (%s)", strings.Join(nonJavaSummary, "; ")))
	}

	if len(summary) > 0 {
		fmt.Fprintf(os.Stderr, "wrote %s\n", strings.Join(summary, "; "))
	}
	return nil
}

func parseArgs(argv []string) (args, error) {
	fs := flag.NewFlagSet("collect-dependencies", flag.ContinueOnError)
	fs.SetOutput(io.Discard)
	lang := fs.String("language", "all", "")
	fs.StringVar(lang, "l", "all", "")
	if err := fs.Parse(argv); err != nil {
		return args{}, fmt.Errorf("parse args: %w", err)
	}
	switch *lang {
	case "go", "rust", "python", "java", "helm", "all":
		return args{Language: *lang}, nil
	default:
		return args{}, fmt.Errorf("invalid language %q", *lang)
	}
}

func requestedLanguages(lang string) map[string]bool {
	if lang == "all" {
		return map[string]bool{"go": true, "rust": true, "python": true, "java": true, "helm": true}
	}
	return map[string]bool{lang: true}
}

func findRepoRoot() (string, error) {
	if override := strings.TrimSpace(os.Getenv("REPO_ROOT")); override != "" {
		return override, nil
	}
	wd, err := os.Getwd()
	if err != nil {
		return "", err
	}
	dir := wd
	for {
		candidate := filepath.Join(dir, "imports.yaml")
		if st, err := os.Stat(candidate); err == nil && !st.IsDir() {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("imports.yaml not found (started from %s)", wd)
		}
		dir = parent
	}
}
