# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

# NATS values for standalone installation
# Replace <REGISTRY> and <REPOSITORY> with your container registry settings.
#
# Example:
#   REGISTRY: nvcr.io
#   REPOSITORY: YOUR_ORG/YOUR_TEAM

nats:
  container:
    image:
      registry: "<REGISTRY>"
      repository: "<REPOSITORY>/nats-server"

  reloader:
    image:
      registry: "<REGISTRY>"
      repository: "<REPOSITORY>/nats-server-config-reloader"

  natsBox:
    container:
      image:
        registry: "<REGISTRY>"
        repository: "<REPOSITORY>/nats-box"

  nkeyJob:
    image:
      registry: "<REGISTRY>"
      repository: "<REPOSITORY>/alpine-k8s"

  # Uncomment and set if using node selectors
  # podTemplate:
  #   merge:
  #     spec:
  #       nodeSelector:
  #         nvcf.nvidia.com/workload: control-plane

  # Uncomment and set to configure storage class for JetStream
  # config:
  #   jetstream:
  #     fileStore:
  #       pvc:
  #         storageClassName: "<STORAGE_CLASS>"
