# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

# Reval values for standalone installation
# Replace <REGISTRY> and <REPOSITORY> with your container registry settings.

reval:
  fullnameOverride: reval
  image:
    registry: "<REGISTRY>"
    repository: "<REPOSITORY>/reval-server"

  # Uncomment for node selectors
  # nodeSelector:
  #   nvcf.nvidia.com/workload: control-plane
