// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	nvcav1alpha1 "github.com/NVIDIA/nvcf/src/compute-plane-services/nvca/pkg/apis/nvca/v1alpha1"
	scheme "github.com/NVIDIA/nvcf/src/compute-plane-services/nvca/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// MiniServicesGetter has a method to return a MiniServiceInterface.
// A group's client should implement this interface.
type MiniServicesGetter interface {
	MiniServices(namespace string) MiniServiceInterface
}

// MiniServiceInterface has methods to work with MiniService resources.
type MiniServiceInterface interface {
	Create(ctx context.Context, miniService *nvcav1alpha1.MiniService, opts v1.CreateOptions) (*nvcav1alpha1.MiniService, error)
	Update(ctx context.Context, miniService *nvcav1alpha1.MiniService, opts v1.UpdateOptions) (*nvcav1alpha1.MiniService, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, miniService *nvcav1alpha1.MiniService, opts v1.UpdateOptions) (*nvcav1alpha1.MiniService, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*nvcav1alpha1.MiniService, error)
	List(ctx context.Context, opts v1.ListOptions) (*nvcav1alpha1.MiniServiceList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *nvcav1alpha1.MiniService, err error)
	MiniServiceExpansion
}

// miniServices implements MiniServiceInterface
type miniServices struct {
	*gentype.ClientWithList[*nvcav1alpha1.MiniService, *nvcav1alpha1.MiniServiceList]
}

// newMiniServices returns a MiniServices
func newMiniServices(c *NvcaV1alpha1Client, namespace string) *miniServices {
	return &miniServices{
		gentype.NewClientWithList[*nvcav1alpha1.MiniService, *nvcav1alpha1.MiniServiceList](
			"miniservices",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *nvcav1alpha1.MiniService { return &nvcav1alpha1.MiniService{} },
			func() *nvcav1alpha1.MiniServiceList { return &nvcav1alpha1.MiniServiceList{} },
		),
	}
}
