// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v2beta1

import (
	nvcav2beta1 "github.com/NVIDIA/nvcf/src/compute-plane-services/nvca/pkg/apis/nvca/v2beta1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// ICMSRequestLister helps list ICMSRequests.
// All objects returned here must be treated as read-only.
type ICMSRequestLister interface {
	// List lists all ICMSRequests in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*nvcav2beta1.ICMSRequest, err error)
	// ICMSRequests returns an object that can list and get ICMSRequests.
	ICMSRequests(namespace string) ICMSRequestNamespaceLister
	ICMSRequestListerExpansion
}

// iCMSRequestLister implements the ICMSRequestLister interface.
type iCMSRequestLister struct {
	listers.ResourceIndexer[*nvcav2beta1.ICMSRequest]
}

// NewICMSRequestLister returns a new ICMSRequestLister.
func NewICMSRequestLister(indexer cache.Indexer) ICMSRequestLister {
	return &iCMSRequestLister{listers.New[*nvcav2beta1.ICMSRequest](indexer, nvcav2beta1.Resource("icmsrequest"))}
}

// ICMSRequests returns an object that can list and get ICMSRequests.
func (s *iCMSRequestLister) ICMSRequests(namespace string) ICMSRequestNamespaceLister {
	return iCMSRequestNamespaceLister{listers.NewNamespaced[*nvcav2beta1.ICMSRequest](s.ResourceIndexer, namespace)}
}

// ICMSRequestNamespaceLister helps list and get ICMSRequests.
// All objects returned here must be treated as read-only.
type ICMSRequestNamespaceLister interface {
	// List lists all ICMSRequests in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*nvcav2beta1.ICMSRequest, err error)
	// Get retrieves the ICMSRequest from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*nvcav2beta1.ICMSRequest, error)
	ICMSRequestNamespaceListerExpansion
}

// iCMSRequestNamespaceLister implements the ICMSRequestNamespaceLister
// interface.
type iCMSRequestNamespaceLister struct {
	listers.ResourceIndexer[*nvcav2beta1.ICMSRequest]
}
