// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1

import (
	corev1 "k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountConfig) DeepCopyInto(out *AccountConfig) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountConfig.
func (in *AccountConfig) DeepCopy() *AccountConfig {
	if in == nil {
		return nil
	}
	out := new(AccountConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentConfig) DeepCopyInto(out *AgentConfig) {
	*out = *in
	if in.AgentResources != nil {
		in, out := &in.AgentResources, &out.AgentResources
		*out = new(corev1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.WebhookResources != nil {
		in, out := &in.WebhookResources, &out.WebhookResources
		*out = new(corev1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.OTelCollectorResources != nil {
		in, out := &in.OTelCollectorResources, &out.OTelCollectorResources
		*out = new(corev1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.ByooResources != nil {
		in, out := &in.ByooResources, &out.ByooResources
		*out = new(corev1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.OTelCollectorConfig != nil {
		in, out := &in.OTelCollectorConfig, &out.OTelCollectorConfig
		*out = new(OTelCollectorConfig)
		**out = **in
	}
	if in.NATSURL != nil {
		in, out := &in.NATSURL, &out.NATSURL
		*out = new(string)
		**out = **in
	}
	in.DeploymentConfig.DeepCopyInto(&out.DeploymentConfig)
	out.NVCFWorkerConfig = in.NVCFWorkerConfig
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentConfig.
func (in *AgentConfig) DeepCopy() *AgentConfig {
	if in == nil {
		return nil
	}
	out := new(AgentConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterConfig) DeepCopyInto(out *ClusterConfig) {
	*out = *in
	in.GPUDiscovery.DeepCopyInto(&out.GPUDiscovery)
	if in.MiniService != nil {
		in, out := &in.MiniService, &out.MiniService
		*out = new(MiniServiceConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.FNDService != nil {
		in, out := &in.FNDService, &out.FNDService
		*out = new(FNDServiceConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Attributes != nil {
		in, out := &in.Attributes, &out.Attributes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.K8sClusterNetworkCIDRs != nil {
		in, out := &in.K8sClusterNetworkCIDRs, &out.K8sClusterNetworkCIDRs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterConfig.
func (in *ClusterConfig) DeepCopy() *ClusterConfig {
	if in == nil {
		return nil
	}
	out := new(ClusterConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeploymentConfig) DeepCopyInto(out *DeploymentConfig) {
	*out = *in
	if in.AdditionalImagePullSecrets != nil {
		in, out := &in.AdditionalImagePullSecrets, &out.AdditionalImagePullSecrets
		*out = make([]corev1.LocalObjectReference, len(*in))
		copy(*out, *in)
	}
	if in.OverrideEnvironmentVars != nil {
		in, out := &in.OverrideEnvironmentVars, &out.OverrideEnvironmentVars
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]corev1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeploymentConfig.
func (in *DeploymentConfig) DeepCopy() *DeploymentConfig {
	if in == nil {
		return nil
	}
	out := new(DeploymentConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DynamicGPUDiscoveryConfig) DeepCopyInto(out *DynamicGPUDiscoveryConfig) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DynamicGPUDiscoveryConfig.
func (in *DynamicGPUDiscoveryConfig) DeepCopy() *DynamicGPUDiscoveryConfig {
	if in == nil {
		return nil
	}
	out := new(DynamicGPUDiscoveryConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FNDServiceConfig) DeepCopyInto(out *FNDServiceConfig) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FNDServiceConfig.
func (in *FNDServiceConfig) DeepCopy() *FNDServiceConfig {
	if in == nil {
		return nil
	}
	out := new(FNDServiceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FeatureGate) DeepCopyInto(out *FeatureGate) {
	*out = *in
	if in.SharedStorage != nil {
		in, out := &in.SharedStorage, &out.SharedStorage
		*out = new(SharedStorageSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.InternalPersistentStorage != nil {
		in, out := &in.InternalPersistentStorage, &out.InternalPersistentStorage
		*out = new(InternalPersistentStorageSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.OTELConfig != nil {
		in, out := &in.OTELConfig, &out.OTELConfig
		*out = new(OTELConfig)
		**out = **in
	}
	if in.Values != nil {
		in, out := &in.Values, &out.Values
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FeatureGate.
func (in *FeatureGate) DeepCopy() *FeatureGate {
	if in == nil {
		return nil
	}
	out := new(FeatureGate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUDiscoveryConfig) DeepCopyInto(out *GPUDiscoveryConfig) {
	*out = *in
	if in.Dynamic != nil {
		in, out := &in.Dynamic, &out.Dynamic
		*out = new(DynamicGPUDiscoveryConfig)
		**out = **in
	}
	if in.Static != nil {
		in, out := &in.Static, &out.Static
		*out = new(StaticGPUDiscoveryConfig)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUDiscoveryConfig.
func (in *GPUDiscoveryConfig) DeepCopy() *GPUDiscoveryConfig {
	if in == nil {
		return nil
	}
	out := new(GPUDiscoveryConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUResource) DeepCopyInto(out *GPUResource) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUResource.
func (in *GPUResource) DeepCopy() *GPUResource {
	if in == nil {
		return nil
	}
	out := new(GPUResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ICMSConfig) DeepCopyInto(out *ICMSConfig) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ICMSConfig.
func (in *ICMSConfig) DeepCopy() *ICMSConfig {
	if in == nil {
		return nil
	}
	out := new(ICMSConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageConfig) DeepCopyInto(out *ImageConfig) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageConfig.
func (in *ImageConfig) DeepCopy() *ImageConfig {
	if in == nil {
		return nil
	}
	out := new(ImageConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageCredHelperConfig) DeepCopyInto(out *ImageCredHelperConfig) {
	*out = *in
	out.ImageConfig = in.ImageConfig
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageCredHelperConfig.
func (in *ImageCredHelperConfig) DeepCopy() *ImageCredHelperConfig {
	if in == nil {
		return nil
	}
	out := new(ImageCredHelperConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InternalPersistentStorageResourceQuotaSpec) DeepCopyInto(out *InternalPersistentStorageResourceQuotaSpec) {
	*out = *in
	if in.Hard != nil {
		in, out := &in.Hard, &out.Hard
		*out = make(corev1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InternalPersistentStorageResourceQuotaSpec.
func (in *InternalPersistentStorageResourceQuotaSpec) DeepCopy() *InternalPersistentStorageResourceQuotaSpec {
	if in == nil {
		return nil
	}
	out := new(InternalPersistentStorageResourceQuotaSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InternalPersistentStorageSpec) DeepCopyInto(out *InternalPersistentStorageSpec) {
	*out = *in
	in.ResourceQuota.DeepCopyInto(&out.ResourceQuota)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InternalPersistentStorageSpec.
func (in *InternalPersistentStorageSpec) DeepCopy() *InternalPersistentStorageSpec {
	if in == nil {
		return nil
	}
	out := new(InternalPersistentStorageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MiniServiceConfig) DeepCopyInto(out *MiniServiceConfig) {
	*out = *in
	if in.CacheDirSize != nil {
		in, out := &in.CacheDirSize, &out.CacheDirSize
		x := (*in).DeepCopy()
		*out = &x
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MiniServiceConfig.
func (in *MiniServiceConfig) DeepCopy() *MiniServiceConfig {
	if in == nil {
		return nil
	}
	out := new(MiniServiceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NVCFBackend) DeepCopyInto(out *NVCFBackend) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NVCFBackend.
func (in *NVCFBackend) DeepCopy() *NVCFBackend {
	if in == nil {
		return nil
	}
	out := new(NVCFBackend)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NVCFBackend) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NVCFBackendList) DeepCopyInto(out *NVCFBackendList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NVCFBackend, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NVCFBackendList.
func (in *NVCFBackendList) DeepCopy() *NVCFBackendList {
	if in == nil {
		return nil
	}
	out := new(NVCFBackendList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NVCFBackendList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NVCFBackendSpec) DeepCopyInto(out *NVCFBackendSpec) {
	*out = *in
	in.NVCFBackendSpecT.DeepCopyInto(&out.NVCFBackendSpecT)
	if in.Overrides != nil {
		in, out := &in.Overrides, &out.Overrides
		*out = new(NVCFBackendSpecT)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NVCFBackendSpec.
func (in *NVCFBackendSpec) DeepCopy() *NVCFBackendSpec {
	if in == nil {
		return nil
	}
	out := new(NVCFBackendSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NVCFBackendSpecT) DeepCopyInto(out *NVCFBackendSpecT) {
	*out = *in
	out.NVCAImageConfig = in.NVCAImageConfig
	out.AccountConfig = in.AccountConfig
	in.ClusterConfig.DeepCopyInto(&out.ClusterConfig)
	in.FeatureGate.DeepCopyInto(&out.FeatureGate)
	out.OAuthConfig = in.OAuthConfig
	out.ICMSConfig = in.ICMSConfig
	out.VaultConfig = in.VaultConfig
	out.WebhookConfig = in.WebhookConfig
	in.AgentConfig.DeepCopyInto(&out.AgentConfig)
	if in.ImageCredHelper != nil {
		in, out := &in.ImageCredHelper, &out.ImageCredHelper
		*out = new(ImageCredHelperConfig)
		**out = **in
	}
	if in.SharedStorageImage != nil {
		in, out := &in.SharedStorageImage, &out.SharedStorageImage
		*out = new(ImageConfig)
		**out = **in
	}
	if in.OTelCollector != nil {
		in, out := &in.OTelCollector, &out.OTelCollector
		*out = new(OTelCollectorConfig)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NVCFBackendSpecT.
func (in *NVCFBackendSpecT) DeepCopy() *NVCFBackendSpecT {
	if in == nil {
		return nil
	}
	out := new(NVCFBackendSpecT)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NVCFBackendStatus) DeepCopyInto(out *NVCFBackendStatus) {
	*out = *in
	in.NVCFBackendSpecT.DeepCopyInto(&out.NVCFBackendSpecT)
	if in.GPUUsage != nil {
		in, out := &in.GPUUsage, &out.GPUUsage
		*out = make(map[GPUName]GPUResource, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.LastUpdated != nil {
		in, out := &in.LastUpdated, &out.LastUpdated
		*out = (*in).DeepCopy()
	}
	if in.LastUpdatedAgentStatus != nil {
		in, out := &in.LastUpdatedAgentStatus, &out.LastUpdatedAgentStatus
		*out = (*in).DeepCopy()
	}
	if in.DDCSIPAllowList != nil {
		in, out := &in.DDCSIPAllowList, &out.DDCSIPAllowList
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.K8sClusterNetworkCIDRs != nil {
		in, out := &in.K8sClusterNetworkCIDRs, &out.K8sClusterNetworkCIDRs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.AgentConfig.DeepCopyInto(&out.AgentConfig)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NVCFBackendStatus.
func (in *NVCFBackendStatus) DeepCopy() *NVCFBackendStatus {
	if in == nil {
		return nil
	}
	out := new(NVCFBackendStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NVCFWorkerConfig) DeepCopyInto(out *NVCFWorkerConfig) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NVCFWorkerConfig.
func (in *NVCFWorkerConfig) DeepCopy() *NVCFWorkerConfig {
	if in == nil {
		return nil
	}
	out := new(NVCFWorkerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OAuthConfig) DeepCopyInto(out *OAuthConfig) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OAuthConfig.
func (in *OAuthConfig) DeepCopy() *OAuthConfig {
	if in == nil {
		return nil
	}
	out := new(OAuthConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OTELConfig) DeepCopyInto(out *OTELConfig) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OTELConfig.
func (in *OTELConfig) DeepCopy() *OTELConfig {
	if in == nil {
		return nil
	}
	out := new(OTELConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OTelCollectorConfig) DeepCopyInto(out *OTelCollectorConfig) {
	*out = *in
	out.ImageConfig = in.ImageConfig
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OTelCollectorConfig.
func (in *OTelCollectorConfig) DeepCopy() *OTelCollectorConfig {
	if in == nil {
		return nil
	}
	out := new(OTelCollectorConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SharedStorageServerSpec) DeepCopyInto(out *SharedStorageServerSpec) {
	*out = *in
	if in.SMBServerContainerResources != nil {
		in, out := &in.SMBServerContainerResources, &out.SMBServerContainerResources
		*out = new(corev1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SharedStorageServerSpec.
func (in *SharedStorageServerSpec) DeepCopy() *SharedStorageServerSpec {
	if in == nil {
		return nil
	}
	out := new(SharedStorageServerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SharedStorageSpec) DeepCopyInto(out *SharedStorageSpec) {
	*out = *in
	if in.Server != nil {
		in, out := &in.Server, &out.Server
		*out = new(SharedStorageServerSpec)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SharedStorageSpec.
func (in *SharedStorageSpec) DeepCopy() *SharedStorageSpec {
	if in == nil {
		return nil
	}
	out := new(SharedStorageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StaticGPUDiscoveryConfig) DeepCopyInto(out *StaticGPUDiscoveryConfig) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StaticGPUDiscoveryConfig.
func (in *StaticGPUDiscoveryConfig) DeepCopy() *StaticGPUDiscoveryConfig {
	if in == nil {
		return nil
	}
	out := new(StaticGPUDiscoveryConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultConfig) DeepCopyInto(out *VaultConfig) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultConfig.
func (in *VaultConfig) DeepCopy() *VaultConfig {
	if in == nil {
		return nil
	}
	out := new(VaultConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebhookConfig) DeepCopyInto(out *WebhookConfig) {
	*out = *in
	out.ImageConfig = in.ImageConfig
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebhookConfig.
func (in *WebhookConfig) DeepCopy() *WebhookConfig {
	if in == nil {
		return nil
	}
	out := new(WebhookConfig)
	in.DeepCopyInto(out)
	return out
}
