// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package nvcaconfig

import (
	v1 "k8s.io/api/core/v1"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentConfig) DeepCopyInto(out *AgentConfig) {
	*out = *in
	out.AgentTimeConfig = in.AgentTimeConfig
	if in.FeatureFlags != nil {
		in, out := &in.FeatureFlags, &out.FeatureFlags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.SharedStorage.DeepCopyInto(&out.SharedStorage)
	in.InternalPersistentStorage.DeepCopyInto(&out.InternalPersistentStorage)
	if in.NamespaceLabels != nil {
		in, out := &in.NamespaceLabels, &out.NamespaceLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.CSIVolumeMountOptions != nil {
		in, out := &in.CSIVolumeMountOptions, &out.CSIVolumeMountOptions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]v1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.UtilsResources != nil {
		in, out := &in.UtilsResources, &out.UtilsResources
		*out = make(ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
	if in.AdditionalResourceOverhead != nil {
		in, out := &in.AdditionalResourceOverhead, &out.AdditionalResourceOverhead
		*out = make(ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
	in.BYOOResources.DeepCopyInto(&out.BYOOResources)
	in.BYOOFluentBitResources.DeepCopyInto(&out.BYOOFluentBitResources)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentConfig.
func (in *AgentConfig) DeepCopy() *AgentConfig {
	if in == nil {
		return nil
	}
	out := new(AgentConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentTimeConfig) DeepCopyInto(out *AgentTimeConfig) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentTimeConfig.
func (in *AgentTimeConfig) DeepCopy() *AgentTimeConfig {
	if in == nil {
		return nil
	}
	out := new(AgentTimeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AllowedExtraKubernetesTypeConfig) DeepCopyInto(out *AllowedExtraKubernetesTypeConfig) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AllowedExtraKubernetesTypeConfig.
func (in *AllowedExtraKubernetesTypeConfig) DeepCopy() *AllowedExtraKubernetesTypeConfig {
	if in == nil {
		return nil
	}
	out := new(AllowedExtraKubernetesTypeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthzConfig) DeepCopyInto(out *AuthzConfig) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthzConfig.
func (in *AuthzConfig) DeepCopy() *AuthzConfig {
	if in == nil {
		return nil
	}
	out := new(AuthzConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Config) DeepCopyInto(out *Config) {
	*out = *in
	in.Cluster.DeepCopyInto(&out.Cluster)
	in.Agent.DeepCopyInto(&out.Agent)
	in.Webhook.DeepCopyInto(&out.Webhook)
	in.Workload.DeepCopyInto(&out.Workload)
	out.Authz = in.Authz
	out.Tracing = in.Tracing
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Config.
func (in *Config) DeepCopy() *Config {
	if in == nil {
		return nil
	}
	out := new(Config)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InternalPersistentStorageConfig) DeepCopyInto(out *InternalPersistentStorageConfig) {
	*out = *in
	if in.HardResourceQuota != nil {
		in, out := &in.HardResourceQuota, &out.HardResourceQuota
		*out = make(ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InternalPersistentStorageConfig.
func (in *InternalPersistentStorageConfig) DeepCopy() *InternalPersistentStorageConfig {
	if in == nil {
		return nil
	}
	out := new(InternalPersistentStorageConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NVCFClusterConfig) DeepCopyInto(out *NVCFClusterConfig) {
	*out = *in
	if in.Attributes != nil {
		in, out := &in.Attributes, &out.Attributes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ValidationPolicy != nil {
		in, out := &in.ValidationPolicy, &out.ValidationPolicy
		*out = new(ValidationPolicyConfig)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NVCFClusterConfig.
func (in *NVCFClusterConfig) DeepCopy() *NVCFClusterConfig {
	if in == nil {
		return nil
	}
	out := new(NVCFClusterConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in ResourceList) DeepCopyInto(out *ResourceList) {
	{
		in := &in
		*out = make(ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
		return
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceList.
func (in ResourceList) DeepCopy() ResourceList {
	if in == nil {
		return nil
	}
	out := new(ResourceList)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceRequirements) DeepCopyInto(out *ResourceRequirements) {
	*out = *in
	if in.Limits != nil {
		in, out := &in.Limits, &out.Limits
		*out = make(ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
	if in.Requests != nil {
		in, out := &in.Requests, &out.Requests
		*out = make(ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
	if in.Claims != nil {
		in, out := &in.Claims, &out.Claims
		*out = make([]v1.ResourceClaim, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceRequirements.
func (in *ResourceRequirements) DeepCopy() *ResourceRequirements {
	if in == nil {
		return nil
	}
	out := new(ResourceRequirements)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SharedStorageConfig) DeepCopyInto(out *SharedStorageConfig) {
	*out = *in
	in.Server.DeepCopyInto(&out.Server)
	in.TaskData.DeepCopyInto(&out.TaskData)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SharedStorageConfig.
func (in *SharedStorageConfig) DeepCopy() *SharedStorageConfig {
	if in == nil {
		return nil
	}
	out := new(SharedStorageConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SharedStorageServerConfig) DeepCopyInto(out *SharedStorageServerConfig) {
	*out = *in
	in.ContainerResources.DeepCopyInto(&out.ContainerResources)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SharedStorageServerConfig.
func (in *SharedStorageServerConfig) DeepCopy() *SharedStorageServerConfig {
	if in == nil {
		return nil
	}
	out := new(SharedStorageServerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SharedStorageTaskDataConfig) DeepCopyInto(out *SharedStorageTaskDataConfig) {
	*out = *in
	if in.StorageClassName != nil {
		in, out := &in.StorageClassName, &out.StorageClassName
		*out = new(string)
		**out = **in
	}
	if in.PVMountOptions != nil {
		in, out := &in.PVMountOptions, &out.PVMountOptions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.StorageCapacity = in.StorageCapacity.DeepCopy()
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SharedStorageTaskDataConfig.
func (in *SharedStorageTaskDataConfig) DeepCopy() *SharedStorageTaskDataConfig {
	if in == nil {
		return nil
	}
	out := new(SharedStorageTaskDataConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TracingConfig) DeepCopyInto(out *TracingConfig) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TracingConfig.
func (in *TracingConfig) DeepCopy() *TracingConfig {
	if in == nil {
		return nil
	}
	out := new(TracingConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ValidationPolicyConfig) DeepCopyInto(out *ValidationPolicyConfig) {
	*out = *in
	if in.AllowedExtraKubernetesTypes != nil {
		in, out := &in.AllowedExtraKubernetesTypes, &out.AllowedExtraKubernetesTypes
		*out = make([]AllowedExtraKubernetesTypeConfig, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ValidationPolicyConfig.
func (in *ValidationPolicyConfig) DeepCopy() *ValidationPolicyConfig {
	if in == nil {
		return nil
	}
	out := new(ValidationPolicyConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebhookConfig) DeepCopyInto(out *WebhookConfig) {
	*out = *in
	if in.DCGMAnnotations != nil {
		in, out := &in.DCGMAnnotations, &out.DCGMAnnotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebhookConfig.
func (in *WebhookConfig) DeepCopy() *WebhookConfig {
	if in == nil {
		return nil
	}
	out := new(WebhookConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadConfig) DeepCopyInto(out *WorkloadConfig) {
	*out = *in
	out.WorkloadTimeConfig = in.WorkloadTimeConfig
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]v1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.FunctionEnvOverrides != nil {
		in, out := &in.FunctionEnvOverrides, &out.FunctionEnvOverrides
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.TaskEnvOverrides != nil {
		in, out := &in.TaskEnvOverrides, &out.TaskEnvOverrides
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadConfig.
func (in *WorkloadConfig) DeepCopy() *WorkloadConfig {
	if in == nil {
		return nil
	}
	out := new(WorkloadConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadTimeConfig) DeepCopyInto(out *WorkloadTimeConfig) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadTimeConfig.
func (in *WorkloadTimeConfig) DeepCopy() *WorkloadTimeConfig {
	if in == nil {
		return nil
	}
	out := new(WorkloadTimeConfig)
	in.DeepCopyInto(out)
	return out
}
