# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: ConfigMap
metadata:
  # referenced in Values under the key `initDBConfigMap`
  name: cassandra-init-cql
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "1"
data:
  keyspace.cql: |-
    CREATE KEYSPACE IF NOT EXISTS schema_migrations WITH replication = {'class': 'NetworkTopologyStrategy', 'ncp': '{{ .Values.cassandra.replicaCount }}' } AND durable_writes = true;
    ALTER KEYSPACE system_auth WITH replication = {'class': 'NetworkTopologyStrategy', 'ncp': '{{ .Values.cassandra.replicaCount }}' } AND durable_writes = true;
    ALTER KEYSPACE system_distributed WITH replication = {'class': 'NetworkTopologyStrategy', 'ncp': '{{ .Values.cassandra.replicaCount }}' } AND durable_writes = true;
    ALTER KEYSPACE system_traces WITH replication = {'class': 'NetworkTopologyStrategy', 'ncp': '1' } AND durable_writes = true;
    CONSISTENCY ALL;
    SELECT * FROM system_auth.roles;
    SELECT * FROM system_auth.role_permissions;
