// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v2beta1

import (
	function "github.com/NVIDIA/nvcf/src/libraries/go/lib/pkg/icms-translate/translate/function"
	task "github.com/NVIDIA/nvcf/src/libraries/go/lib/pkg/icms-translate/translate/task"
	v1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ICMSCreationMessageInfo) DeepCopyInto(out *ICMSCreationMessageInfo) {
	*out = *in
	in.CreationQueueMessageMetadata.DeepCopyInto(&out.CreationQueueMessageMetadata)
	if in.LaunchArtifacts != nil {
		in, out := &in.LaunchArtifacts, &out.LaunchArtifacts
		*out = make(function.LaunchArtifacts, len(*in))
		copy(*out, *in)
	}
	if in.FunctionLaunchSpecification != nil {
		in, out := &in.FunctionLaunchSpecification, &out.FunctionLaunchSpecification
		*out = new(function.LaunchSpecification)
		(*in).DeepCopyInto(*out)
	}
	if in.TaskLaunchSpecification != nil {
		in, out := &in.TaskLaunchSpecification, &out.TaskLaunchSpecification
		*out = new(task.LaunchSpecification)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ICMSCreationMessageInfo.
func (in *ICMSCreationMessageInfo) DeepCopy() *ICMSCreationMessageInfo {
	if in == nil {
		return nil
	}
	out := new(ICMSCreationMessageInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ICMSRequest) DeepCopyInto(out *ICMSRequest) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ICMSRequest.
func (in *ICMSRequest) DeepCopy() *ICMSRequest {
	if in == nil {
		return nil
	}
	out := new(ICMSRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ICMSRequest) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ICMSRequestList) DeepCopyInto(out *ICMSRequestList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ICMSRequest, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ICMSRequestList.
func (in *ICMSRequestList) DeepCopy() *ICMSRequestList {
	if in == nil {
		return nil
	}
	out := new(ICMSRequestList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ICMSRequestList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ICMSRequestSpanContextConfig) DeepCopyInto(out *ICMSRequestSpanContextConfig) {
	*out = *in
	in.StartTime.DeepCopyInto(&out.StartTime)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ICMSRequestSpanContextConfig.
func (in *ICMSRequestSpanContextConfig) DeepCopy() *ICMSRequestSpanContextConfig {
	if in == nil {
		return nil
	}
	out := new(ICMSRequestSpanContextConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ICMSRequestSpec) DeepCopyInto(out *ICMSRequestSpec) {
	*out = *in
	in.CreationMsgInfo.DeepCopyInto(&out.CreationMsgInfo)
	in.TerminationMsgInfo.DeepCopyInto(&out.TerminationMsgInfo)
	out.FunctionDetails = in.FunctionDetails
	out.TaskDetails = in.TaskDetails
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ICMSRequestSpec.
func (in *ICMSRequestSpec) DeepCopy() *ICMSRequestSpec {
	if in == nil {
		return nil
	}
	out := new(ICMSRequestSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ICMSRequestStatus) DeepCopyInto(out *ICMSRequestStatus) {
	*out = *in
	if in.LastStatusUpdated != nil {
		in, out := &in.LastStatusUpdated, &out.LastStatusUpdated
		*out = (*in).DeepCopy()
	}
	if in.LastObservedAllTerminatedInstances != nil {
		in, out := &in.LastObservedAllTerminatedInstances, &out.LastObservedAllTerminatedInstances
		*out = (*in).DeepCopy()
	}
	if in.LastACKTimestamp != nil {
		in, out := &in.LastACKTimestamp, &out.LastACKTimestamp
		*out = (*in).DeepCopy()
	}
	if in.Instances != nil {
		in, out := &in.Instances, &out.Instances
		*out = make(map[string]InstanceStatus, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.RequestStatusTraceContexts != nil {
		in, out := &in.RequestStatusTraceContexts, &out.RequestStatusTraceContexts
		*out = make(map[RequestStatus]ICMSRequestSpanContextConfig, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ICMSRequestStatus.
func (in *ICMSRequestStatus) DeepCopy() *ICMSRequestStatus {
	if in == nil {
		return nil
	}
	out := new(ICMSRequestStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ICMSRequestTraceContextConfig) DeepCopyInto(out *ICMSRequestTraceContextConfig) {
	*out = *in
	if in.TraceState != nil {
		in, out := &in.TraceState, &out.TraceState
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ICMSRequestTraceContextConfig.
func (in *ICMSRequestTraceContextConfig) DeepCopy() *ICMSRequestTraceContextConfig {
	if in == nil {
		return nil
	}
	out := new(ICMSRequestTraceContextConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ICMSTerminationMessageInfo) DeepCopyInto(out *ICMSTerminationMessageInfo) {
	*out = *in
	if in.InstanceIds != nil {
		in, out := &in.InstanceIds, &out.InstanceIds
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ICMSTerminationMessageInfo.
func (in *ICMSTerminationMessageInfo) DeepCopy() *ICMSTerminationMessageInfo {
	if in == nil {
		return nil
	}
	out := new(ICMSTerminationMessageInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceStatus) DeepCopyInto(out *InstanceStatus) {
	*out = *in
	if in.LastReportedTimestamp != nil {
		in, out := &in.LastReportedTimestamp, &out.LastReportedTimestamp
		*out = (*in).DeepCopy()
	}
	if in.Attributes != nil {
		in, out := &in.Attributes, &out.Attributes
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceStatus.
func (in *InstanceStatus) DeepCopy() *InstanceStatus {
	if in == nil {
		return nil
	}
	out := new(InstanceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InternalPersistentStorageResourceQuotaSpec) DeepCopyInto(out *InternalPersistentStorageResourceQuotaSpec) {
	*out = *in
	if in.Hard != nil {
		in, out := &in.Hard, &out.Hard
		*out = make(v1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InternalPersistentStorageResourceQuotaSpec.
func (in *InternalPersistentStorageResourceQuotaSpec) DeepCopy() *InternalPersistentStorageResourceQuotaSpec {
	if in == nil {
		return nil
	}
	out := new(InternalPersistentStorageResourceQuotaSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InternalPersistentStorageSpec) DeepCopyInto(out *InternalPersistentStorageSpec) {
	*out = *in
	in.ResourceQuota.DeepCopyInto(&out.ResourceQuota)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InternalPersistentStorageSpec.
func (in *InternalPersistentStorageSpec) DeepCopy() *InternalPersistentStorageSpec {
	if in == nil {
		return nil
	}
	out := new(InternalPersistentStorageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InternalPersistentStorageStatus) DeepCopyInto(out *InternalPersistentStorageStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InternalPersistentStorageStatus.
func (in *InternalPersistentStorageStatus) DeepCopy() *InternalPersistentStorageStatus {
	if in == nil {
		return nil
	}
	out := new(InternalPersistentStorageStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelCacheEncryption) DeepCopyInto(out *ModelCacheEncryption) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelCacheEncryption.
func (in *ModelCacheEncryption) DeepCopy() *ModelCacheEncryption {
	if in == nil {
		return nil
	}
	out := new(ModelCacheEncryption)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelCacheSpec) DeepCopyInto(out *ModelCacheSpec) {
	*out = *in
	if in.Encryption != nil {
		in, out := &in.Encryption, &out.Encryption
		*out = new(ModelCacheEncryption)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelCacheSpec.
func (in *ModelCacheSpec) DeepCopy() *ModelCacheSpec {
	if in == nil {
		return nil
	}
	out := new(ModelCacheSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelCacheStatus) DeepCopyInto(out *ModelCacheStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelCacheStatus.
func (in *ModelCacheStatus) DeepCopy() *ModelCacheStatus {
	if in == nil {
		return nil
	}
	out := new(ModelCacheStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SharedStorageServerSpec) DeepCopyInto(out *SharedStorageServerSpec) {
	*out = *in
	if in.SMBServerContainerResources != nil {
		in, out := &in.SMBServerContainerResources, &out.SMBServerContainerResources
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.SMBServerPodNodeAffinity != nil {
		in, out := &in.SMBServerPodNodeAffinity, &out.SMBServerPodNodeAffinity
		*out = new(v1.Affinity)
		(*in).DeepCopyInto(*out)
	}
	if in.SMBServerPodTolerations != nil {
		in, out := &in.SMBServerPodTolerations, &out.SMBServerPodTolerations
		*out = make([]v1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SharedStorageServerSpec.
func (in *SharedStorageServerSpec) DeepCopy() *SharedStorageServerSpec {
	if in == nil {
		return nil
	}
	out := new(SharedStorageServerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SharedStorageSpec) DeepCopyInto(out *SharedStorageSpec) {
	*out = *in
	if in.WorkerPullSecretNames != nil {
		in, out := &in.WorkerPullSecretNames, &out.WorkerPullSecretNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.Size = in.Size.DeepCopy()
	if in.Server != nil {
		in, out := &in.Server, &out.Server
		*out = new(SharedStorageServerSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.TaskData != nil {
		in, out := &in.TaskData, &out.TaskData
		*out = new(SharedStorageTaskDataSpec)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SharedStorageSpec.
func (in *SharedStorageSpec) DeepCopy() *SharedStorageSpec {
	if in == nil {
		return nil
	}
	out := new(SharedStorageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SharedStorageStatus) DeepCopyInto(out *SharedStorageStatus) {
	*out = *in
	in.KNS.DeepCopyInto(&out.KNS)
	in.Secrets.DeepCopyInto(&out.Secrets)
	if in.TaskData != nil {
		in, out := &in.TaskData, &out.TaskData
		*out = new(SharedStorageTypeStatus)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SharedStorageStatus.
func (in *SharedStorageStatus) DeepCopy() *SharedStorageStatus {
	if in == nil {
		return nil
	}
	out := new(SharedStorageStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SharedStorageTaskDataSpec) DeepCopyInto(out *SharedStorageTaskDataSpec) {
	*out = *in
	if in.StorageClassName != nil {
		in, out := &in.StorageClassName, &out.StorageClassName
		*out = new(string)
		**out = **in
	}
	if in.PVMountOptions != nil {
		in, out := &in.PVMountOptions, &out.PVMountOptions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.Size = in.Size.DeepCopy()
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SharedStorageTaskDataSpec.
func (in *SharedStorageTaskDataSpec) DeepCopy() *SharedStorageTaskDataSpec {
	if in == nil {
		return nil
	}
	out := new(SharedStorageTaskDataSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SharedStorageTypeStatus) DeepCopyInto(out *SharedStorageTypeStatus) {
	*out = *in
	out.StorageCapacity = in.StorageCapacity.DeepCopy()
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SharedStorageTypeStatus.
func (in *SharedStorageTypeStatus) DeepCopy() *SharedStorageTypeStatus {
	if in == nil {
		return nil
	}
	out := new(SharedStorageTypeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageRequest) DeepCopyInto(out *StorageRequest) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageRequest.
func (in *StorageRequest) DeepCopy() *StorageRequest {
	if in == nil {
		return nil
	}
	out := new(StorageRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StorageRequest) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageRequestList) DeepCopyInto(out *StorageRequestList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]StorageRequest, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageRequestList.
func (in *StorageRequestList) DeepCopy() *StorageRequestList {
	if in == nil {
		return nil
	}
	out := new(StorageRequestList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StorageRequestList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageRequestSpec) DeepCopyInto(out *StorageRequestSpec) {
	*out = *in
	if in.ModelCache != nil {
		in, out := &in.ModelCache, &out.ModelCache
		*out = new(ModelCacheSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.SharedStorage != nil {
		in, out := &in.SharedStorage, &out.SharedStorage
		*out = new(SharedStorageSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.InternalPersistentStorage != nil {
		in, out := &in.InternalPersistentStorage, &out.InternalPersistentStorage
		*out = new(InternalPersistentStorageSpec)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageRequestSpec.
func (in *StorageRequestSpec) DeepCopy() *StorageRequestSpec {
	if in == nil {
		return nil
	}
	out := new(StorageRequestSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageRequestStatus) DeepCopyInto(out *StorageRequestStatus) {
	*out = *in
	if in.LastPhaseTransitionTime != nil {
		in, out := &in.LastPhaseTransitionTime, &out.LastPhaseTransitionTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ModelCache != nil {
		in, out := &in.ModelCache, &out.ModelCache
		*out = new(ModelCacheStatus)
		**out = **in
	}
	if in.SharedStorage != nil {
		in, out := &in.SharedStorage, &out.SharedStorage
		*out = new(SharedStorageStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.InternalPersistentStorage != nil {
		in, out := &in.InternalPersistentStorage, &out.InternalPersistentStorage
		*out = new(InternalPersistentStorageStatus)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageRequestStatus.
func (in *StorageRequestStatus) DeepCopy() *StorageRequestStatus {
	if in == nil {
		return nil
	}
	out := new(StorageRequestStatus)
	in.DeepCopyInto(out)
	return out
}
