// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v2beta1

import (
	context "context"

	nvcav2beta1 "github.com/NVIDIA/nvcf/src/compute-plane-services/nvca/pkg/apis/nvca/v2beta1"
	scheme "github.com/NVIDIA/nvcf/src/compute-plane-services/nvca/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// ICMSRequestsGetter has a method to return a ICMSRequestInterface.
// A group's client should implement this interface.
type ICMSRequestsGetter interface {
	ICMSRequests(namespace string) ICMSRequestInterface
}

// ICMSRequestInterface has methods to work with ICMSRequest resources.
type ICMSRequestInterface interface {
	Create(ctx context.Context, iCMSRequest *nvcav2beta1.ICMSRequest, opts v1.CreateOptions) (*nvcav2beta1.ICMSRequest, error)
	Update(ctx context.Context, iCMSRequest *nvcav2beta1.ICMSRequest, opts v1.UpdateOptions) (*nvcav2beta1.ICMSRequest, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, iCMSRequest *nvcav2beta1.ICMSRequest, opts v1.UpdateOptions) (*nvcav2beta1.ICMSRequest, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*nvcav2beta1.ICMSRequest, error)
	List(ctx context.Context, opts v1.ListOptions) (*nvcav2beta1.ICMSRequestList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *nvcav2beta1.ICMSRequest, err error)
	ICMSRequestExpansion
}

// iCMSRequests implements ICMSRequestInterface
type iCMSRequests struct {
	*gentype.ClientWithList[*nvcav2beta1.ICMSRequest, *nvcav2beta1.ICMSRequestList]
}

// newICMSRequests returns a ICMSRequests
func newICMSRequests(c *NvcaV2beta1Client, namespace string) *iCMSRequests {
	return &iCMSRequests{
		gentype.NewClientWithList[*nvcav2beta1.ICMSRequest, *nvcav2beta1.ICMSRequestList](
			"icmsrequests",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *nvcav2beta1.ICMSRequest { return &nvcav2beta1.ICMSRequest{} },
			func() *nvcav2beta1.ICMSRequestList { return &nvcav2beta1.ICMSRequestList{} },
		),
	}
}
