// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v2beta1

import (
	context "context"

	nvcav2beta1 "github.com/NVIDIA/nvcf/src/compute-plane-services/nvca/pkg/apis/nvca/v2beta1"
	scheme "github.com/NVIDIA/nvcf/src/compute-plane-services/nvca/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// StorageRequestsGetter has a method to return a StorageRequestInterface.
// A group's client should implement this interface.
type StorageRequestsGetter interface {
	StorageRequests(namespace string) StorageRequestInterface
}

// StorageRequestInterface has methods to work with StorageRequest resources.
type StorageRequestInterface interface {
	Create(ctx context.Context, storageRequest *nvcav2beta1.StorageRequest, opts v1.CreateOptions) (*nvcav2beta1.StorageRequest, error)
	Update(ctx context.Context, storageRequest *nvcav2beta1.StorageRequest, opts v1.UpdateOptions) (*nvcav2beta1.StorageRequest, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, storageRequest *nvcav2beta1.StorageRequest, opts v1.UpdateOptions) (*nvcav2beta1.StorageRequest, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*nvcav2beta1.StorageRequest, error)
	List(ctx context.Context, opts v1.ListOptions) (*nvcav2beta1.StorageRequestList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *nvcav2beta1.StorageRequest, err error)
	StorageRequestExpansion
}

// storageRequests implements StorageRequestInterface
type storageRequests struct {
	*gentype.ClientWithList[*nvcav2beta1.StorageRequest, *nvcav2beta1.StorageRequestList]
}

// newStorageRequests returns a StorageRequests
func newStorageRequests(c *NvcaV2beta1Client, namespace string) *storageRequests {
	return &storageRequests{
		gentype.NewClientWithList[*nvcav2beta1.StorageRequest, *nvcav2beta1.StorageRequestList](
			"storagerequests",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *nvcav2beta1.StorageRequest { return &nvcav2beta1.StorageRequest{} },
			func() *nvcav2beta1.StorageRequestList { return &nvcav2beta1.StorageRequestList{} },
		),
	}
}
