// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

//go:build ignore

// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/NVIDIA/nvcf/llm-api-gateway/templating/prompt (interfaces: TextTemplate)
//
// Generated by this command:
//
//	mockgen -package promptmock -destination promptmock/text_template.go . TextTemplate
//

// Package promptmock is a generated GoMock package.
package promptmock

import (
	reflect "reflect"

	models "github.com/NVIDIA/nvcf/llm-api-gateway/models"
	output "github.com/NVIDIA/nvcf/llm-api-gateway/templating/output"
	prompt "github.com/NVIDIA/nvcf/llm-api-gateway/templating/prompt"
	tools "github.com/NVIDIA/nvcf/llm-api-gateway/templating/tools"
	gomock "go.uber.org/mock/gomock"
)

// MockTextTemplate is a mock of TextTemplate interface.
type MockTextTemplate struct {
	ctrl     *gomock.Controller
	recorder *MockTextTemplateMockRecorder
	isgomock struct{}
}

// MockTextTemplateMockRecorder is the mock recorder for MockTextTemplate.
type MockTextTemplateMockRecorder struct {
	mock *MockTextTemplate
}

// NewMockTextTemplate creates a new mock instance.
func NewMockTextTemplate(ctrl *gomock.Controller) *MockTextTemplate {
	mock := &MockTextTemplate{ctrl: ctrl}
	mock.recorder = &MockTextTemplateMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTextTemplate) EXPECT() *MockTextTemplateMockRecorder {
	return m.recorder
}

// DropTokens mocks base method.
func (m *MockTextTemplate) DropTokens() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DropTokens")
	ret0, _ := ret[0].([]string)
	return ret0
}

// DropTokens indicates an expected call of DropTokens.
func (mr *MockTextTemplateMockRecorder) DropTokens() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DropTokens", reflect.TypeOf((*MockTextTemplate)(nil).DropTokens))
}

// GetForcedToolUsePrefix mocks base method.
func (m *MockTextTemplate) GetForcedToolUsePrefix(arg0 *models.ChatCompletionToolChoiceField) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetForcedToolUsePrefix", arg0)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetForcedToolUsePrefix indicates an expected call of GetForcedToolUsePrefix.
func (mr *MockTextTemplateMockRecorder) GetForcedToolUsePrefix(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetForcedToolUsePrefix", reflect.TypeOf((*MockTextTemplate)(nil).GetForcedToolUsePrefix), arg0)
}

// ReasoningConfig mocks base method.
func (m *MockTextTemplate) ReasoningConfig() output.ReasoningConfig {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReasoningConfig")
	ret0, _ := ret[0].(output.ReasoningConfig)
	return ret0
}

// ReasoningConfig indicates an expected call of ReasoningConfig.
func (mr *MockTextTemplateMockRecorder) ReasoningConfig() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReasoningConfig", reflect.TypeOf((*MockTextTemplate)(nil).ReasoningConfig))
}

// RenderText mocks base method.
func (m *MockTextTemplate) RenderText(arg0 []models.ChatMessage, arg1 tools.Params) (prompt.Prompt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RenderText", arg0, arg1)
	ret0, _ := ret[0].(prompt.Prompt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RenderText indicates an expected call of RenderText.
func (mr *MockTextTemplateMockRecorder) RenderText(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RenderText", reflect.TypeOf((*MockTextTemplate)(nil).RenderText), arg0, arg1)
}

// ToolParseConfig mocks base method.
func (m *MockTextTemplate) ToolParseConfig() tools.ParseConfig {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToolParseConfig")
	ret0, _ := ret[0].(tools.ParseConfig)
	return ret0
}

// ToolParseConfig indicates an expected call of ToolParseConfig.
func (mr *MockTextTemplateMockRecorder) ToolParseConfig() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToolParseConfig", reflect.TypeOf((*MockTextTemplate)(nil).ToolParseConfig))
}

// Version mocks base method.
func (m *MockTextTemplate) Version() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Version")
	ret0, _ := ret[0].(string)
	return ret0
}

// Version indicates an expected call of Version.
func (mr *MockTextTemplateMockRecorder) Version() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Version", reflect.TypeOf((*MockTextTemplate)(nil).Version))
}
