// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

//go:build ignore

// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/NVIDIA/nvcf/llm-api-gateway/templating/prompt (interfaces: TokenizedTemplate)
//
// Generated by this command:
//
//	mockgen -package promptmock -destination promptmock/tokenized_template.go . TokenizedTemplate
//

// Package promptmock is a generated GoMock package.
package promptmock

import (
	reflect "reflect"

	models "github.com/NVIDIA/nvcf/llm-api-gateway/models"
	output "github.com/NVIDIA/nvcf/llm-api-gateway/templating/output"
	token "github.com/NVIDIA/nvcf/llm-api-gateway/templating/token"
	tools "github.com/NVIDIA/nvcf/llm-api-gateway/templating/tools"
	gomock "go.uber.org/mock/gomock"
)

// MockTokenizedTemplate is a mock of TokenizedTemplate interface.
type MockTokenizedTemplate struct {
	ctrl     *gomock.Controller
	recorder *MockTokenizedTemplateMockRecorder
	isgomock struct{}
}

// MockTokenizedTemplateMockRecorder is the mock recorder for MockTokenizedTemplate.
type MockTokenizedTemplateMockRecorder struct {
	mock *MockTokenizedTemplate
}

// NewMockTokenizedTemplate creates a new mock instance.
func NewMockTokenizedTemplate(ctrl *gomock.Controller) *MockTokenizedTemplate {
	mock := &MockTokenizedTemplate{ctrl: ctrl}
	mock.recorder = &MockTokenizedTemplateMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenizedTemplate) EXPECT() *MockTokenizedTemplateMockRecorder {
	return m.recorder
}

// DropTokens mocks base method.
func (m *MockTokenizedTemplate) DropTokens() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DropTokens")
	ret0, _ := ret[0].([]string)
	return ret0
}

// DropTokens indicates an expected call of DropTokens.
func (mr *MockTokenizedTemplateMockRecorder) DropTokens() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DropTokens", reflect.TypeOf((*MockTokenizedTemplate)(nil).DropTokens))
}

// GetForcedToolUsePrefix mocks base method.
func (m *MockTokenizedTemplate) GetForcedToolUsePrefix(arg0 *models.ChatCompletionToolChoiceField) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetForcedToolUsePrefix", arg0)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetForcedToolUsePrefix indicates an expected call of GetForcedToolUsePrefix.
func (mr *MockTokenizedTemplateMockRecorder) GetForcedToolUsePrefix(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetForcedToolUsePrefix", reflect.TypeOf((*MockTokenizedTemplate)(nil).GetForcedToolUsePrefix), arg0)
}

// ReasoningConfig mocks base method.
func (m *MockTokenizedTemplate) ReasoningConfig() output.ReasoningConfig {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReasoningConfig")
	ret0, _ := ret[0].(output.ReasoningConfig)
	return ret0
}

// ReasoningConfig indicates an expected call of ReasoningConfig.
func (mr *MockTokenizedTemplateMockRecorder) ReasoningConfig() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReasoningConfig", reflect.TypeOf((*MockTokenizedTemplate)(nil).ReasoningConfig))
}

// RenderMessages mocks base method.
func (m *MockTokenizedTemplate) RenderMessages(arg0 []uint32) ([]models.ChatMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RenderMessages", arg0)
	ret0, _ := ret[0].([]models.ChatMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RenderMessages indicates an expected call of RenderMessages.
func (mr *MockTokenizedTemplateMockRecorder) RenderMessages(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RenderMessages", reflect.TypeOf((*MockTokenizedTemplate)(nil).RenderMessages), arg0)
}

// RenderTokens mocks base method.
func (m *MockTokenizedTemplate) RenderTokens(arg0 []models.ChatMessage, arg1 tools.Params) (token.Tokens, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RenderTokens", arg0, arg1)
	ret0, _ := ret[0].(token.Tokens)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// RenderTokens indicates an expected call of RenderTokens.
func (mr *MockTokenizedTemplateMockRecorder) RenderTokens(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RenderTokens", reflect.TypeOf((*MockTokenizedTemplate)(nil).RenderTokens), arg0, arg1)
}

// ToolParseConfig mocks base method.
func (m *MockTokenizedTemplate) ToolParseConfig() tools.ParseConfig {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToolParseConfig")
	ret0, _ := ret[0].(tools.ParseConfig)
	return ret0
}

// ToolParseConfig indicates an expected call of ToolParseConfig.
func (mr *MockTokenizedTemplateMockRecorder) ToolParseConfig() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToolParseConfig", reflect.TypeOf((*MockTokenizedTemplate)(nil).ToolParseConfig))
}

// Version mocks base method.
func (m *MockTokenizedTemplate) Version() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Version")
	ret0, _ := ret[0].(string)
	return ret0
}

// Version indicates an expected call of Version.
func (mr *MockTokenizedTemplateMockRecorder) Version() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Version", reflect.TypeOf((*MockTokenizedTemplate)(nil).Version))
}
