/*
SPDX-FileCopyrightText: Copyright (c) NVIDIA CORPORATION & AFFILIATES. All rights reserved.
SPDX-License-Identifier: Apache-2.0

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package tools

import (
	"iter"

	"github.com/NVIDIA/nvcf/llm-api-gateway/internal/ptr"
)

var (
	_ CallExtractor = (*Call)(nil)
	_ CallExtractor = (*SingleCall)(nil)
	_ CallExtractor = (*ParallelCalls)(nil)
)

type CallExtractor interface {
	ExtractCalls() []Call
	ExtractCallsIter() iter.Seq[Call]
	NumCalls() int
}

type Call struct {
	Name      string         `mapstructure:"name"`
	Arguments map[string]any `mapstructure:"arguments"`
	// Optional ID for if the model emits it.
	ID string
}

func (c *Call) ExtractCalls() []Call {
	return []Call{*c}
}

func (c *Call) ExtractCallsIter() iter.Seq[Call] {
	return func(yield func(Call) bool) {
		yield(ptr.Deref(c))
	}
}

func (c *Call) NumCalls() int {
	return 1
}

type CallParameters struct {
	Name       string         `mapstructure:"name"`
	Parameters map[string]any `mapstructure:"parameters"`
}

func (c *CallParameters) ExtractCalls() []Call {
	return []Call{
		{
			Name:      c.Name,
			Arguments: c.Parameters,
		},
	}
}

func (c *CallParameters) ExtractCallsIter() iter.Seq[Call] {
	return func(yield func(Call) bool) {
		yield(Call{
			Name:      c.Name,
			Arguments: c.Parameters,
		})
	}
}

func (c *CallParameters) NumCalls() int {
	return 1
}

// Tool call objects type generated by LLMs.
// These are used for parsing successful tool calls completions
// and converting them to models.ChatToolCall objects.
type callObject struct {
	ID         string         `mapstructure:"id"`
	Type       string         `mapstructure:"type"`
	Function   functionObject `mapstructure:"function"`
	Parameters map[string]any `mapstructure:"parameters"`
}

type functionObject struct {
	Name string `mapstructure:"name"`
}

type SingleCall struct {
	ToolCall callObject `mapstructure:"tool_call"`
}

func (c SingleCall) ExtractCalls() []Call {
	return []Call{
		{
			Name:      c.ToolCall.Function.Name,
			Arguments: c.ToolCall.Parameters,
		},
	}
}

func (c SingleCall) ExtractCallsIter() iter.Seq[Call] {
	return func(yield func(Call) bool) {
		yield(Call{
			Name:      c.ToolCall.Function.Name,
			Arguments: c.ToolCall.Parameters,
		})
	}
}

func (SingleCall) NumCalls() int {
	return 1
}

type ParallelCalls struct {
	ToolCalls []callObject `mapstructure:"tool_calls"`
}

func (c ParallelCalls) ExtractCalls() []Call {
	calls := make([]Call, 0, len(c.ToolCalls))
	for _, call := range c.ToolCalls {
		calls = append(calls, Call{
			Name:      call.Function.Name,
			Arguments: call.Parameters,
		})
	}
	return calls
}

func (c ParallelCalls) ExtractCallsIter() iter.Seq[Call] {
	return func(yield func(Call) bool) {
		for _, call := range c.ToolCalls {
			ok := yield(Call{
				Name:      call.Function.Name,
				Arguments: call.Parameters,
			})
			if !ok {
				break
			}
		}
	}
}

func (c ParallelCalls) NumCalls() int {
	return len(c.ToolCalls)
}
