// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	nvcav1 "github.com/NVIDIA/nvcf/src/compute-plane-services/nvca/pkg/apis/nvca/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// StorageRequestLister helps list StorageRequests.
// All objects returned here must be treated as read-only.
type StorageRequestLister interface {
	// List lists all StorageRequests in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*nvcav1.StorageRequest, err error)
	// StorageRequests returns an object that can list and get StorageRequests.
	StorageRequests(namespace string) StorageRequestNamespaceLister
	StorageRequestListerExpansion
}

// storageRequestLister implements the StorageRequestLister interface.
type storageRequestLister struct {
	listers.ResourceIndexer[*nvcav1.StorageRequest]
}

// NewStorageRequestLister returns a new StorageRequestLister.
func NewStorageRequestLister(indexer cache.Indexer) StorageRequestLister {
	return &storageRequestLister{listers.New[*nvcav1.StorageRequest](indexer, nvcav1.Resource("storagerequest"))}
}

// StorageRequests returns an object that can list and get StorageRequests.
func (s *storageRequestLister) StorageRequests(namespace string) StorageRequestNamespaceLister {
	return storageRequestNamespaceLister{listers.NewNamespaced[*nvcav1.StorageRequest](s.ResourceIndexer, namespace)}
}

// StorageRequestNamespaceLister helps list and get StorageRequests.
// All objects returned here must be treated as read-only.
type StorageRequestNamespaceLister interface {
	// List lists all StorageRequests in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*nvcav1.StorageRequest, err error)
	// Get retrieves the StorageRequest from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*nvcav1.StorageRequest, error)
	StorageRequestNamespaceListerExpansion
}

// storageRequestNamespaceLister implements the StorageRequestNamespaceLister
// interface.
type storageRequestNamespaceLister struct {
	listers.ResourceIndexer[*nvcav1.StorageRequest]
}
