# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

{{- if .Values.adminIssuerProxy.gateway.enabled }}
# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "admin-issuer-proxy.fullname" . }}
  namespace: {{ .Values.adminIssuerProxy.gateway.namespace }}
spec:
  parentRefs:
  - name: {{ .Values.adminIssuerProxy.gateway.gatewayRef.name }}
    namespace: {{ .Values.adminIssuerProxy.gateway.namespace }}
  hostnames:
  - {{ .Values.adminIssuerProxy.gateway.hostname }}
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: {{ .Values.adminIssuerProxy.gateway.path }}
    backendRefs:
    - name: {{ include "admin-issuer-proxy.fullname" . }}
      namespace: {{ .Release.Namespace }}
      port: {{ .Values.adminIssuerProxy.service.port }}
{{- end }}

