# SPDX-FileCopyrightText: Copyright (c) 2023-2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

{{- if and .Values.kyverno.enabled (not .Values.webhook.enabled) }}
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-unbound-dns
  annotations:
    pod-policies.kyverno.io/autogen-controllers: none
    policies.kyverno.io/title: Add Unbound DNS to all NVCF pods/helms
    policies.kyverno.io/category: Sample
    policies.kyverno.io/subject: Pod,Volume
    kyverno.io/kyverno-version: 1.6.0
    kyverno.io/kubernetes-version: "1.21"
    policies.kyverno.io/minversion: 1.5.0
    policies.kyverno.io/description:  Add Unbound DNS to all NVCF pods/helms
spec:
  background: false
  rules:
  - name: add-unbound-dns
    match:
      any:
      - resources:
          kinds:
          - Pod
          operations: ["CREATE"]
          namespaceSelector:
            matchExpressions:
              - key: "nvca.nvcf.nvidia.io/spot-instance-type"
                operator: In
                values:
                - pod_spec
                - helm_chart
                - miniservice
    mutate:
      patchStrategicMerge:
        spec:
          dnsPolicy: None
          dnsConfig:
            nameservers:
              - {{ $.Values.unbound.cluster_ip }} # IP of UnboundDNS
              - {{  $.Values.unbound.stub_nameserver }}  # IP of coreDNS
            searches:
              - "{{ `{{` }} request.namespace {{ `}}` }}.svc.cluster.local"
            options:
            - name: ndots
              value: "5"
            - name: timeout
              value: "1"
{{- end }}
