{{- if and .Values.otel.enabled (not (empty .Values.otel.lightstep.serviceName)) (not (empty .Values.otel.lightstep.accessToken)) }}
# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
apiVersion: v1
data:
  OTEL_EXPORTER: {{ "lightstep" | b64enc }}
  OTEL_ENDPOINT: {{ .Values.otel.endpoint | b64enc }}
  LS_SERVICE_NAME: {{ .Values.otel.lightstep.serviceName | b64enc }}
  LS_ACCESS_TOKEN: {{ .Values.otel.lightstep.accessToken | b64enc }}
kind: Secret
metadata:
  name: otel-{{ include "nvcaop.fullname" . }}-config
{{- end }}
