# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ $.Chart.Name }}-scripts-cm
  {{- if .Values.namespace }}
  namespace: {{ .Values.namespace }}
  {{- end }}
  labels:
{{ include "hb.labels.standard" . | indent 4 }}
{{- include "std-helm.labels" $ | nindent 4 }}
data:
  script.sh: |
    #The scripts can be used as commands in the Initcontainers or as container commands.
    #Size of script file can not exceed 1 MiB
  run.sh: |
    #!/bin/bash




    #cp -rf /tmp/model_repo/triton_tao_model_repo /opt/nvidia/deepstream/deepstream/samples/

    cd /workspace/deepstream-triton/ && gxe --app deepstream-triton.yaml --manifest deepstream-triton_manifest.yaml

  setup.sh: |
    #!/bin/bash


    cd /workspace/deepstream-triton/ && ./prepare_ds_triton_tao_model_repo.sh

    mkdir /tmp/triton_tao_model_repo

    cp -r /tmp/peoplesemsegnet_shuffle/ /tmp/triton_tao_model_repo

    cp -r /tmp/triton_tao_model_repo /tmp/model_repo

