// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/NVIDIA/nvcf/llm-api-gateway/ratelimit (interfaces: RateLimiter)
//
// Generated by this command:
//
//	mockgen -package ratelimitmock -destination ratelimitmock/rate_limiter.go . RateLimiter
//

// Package ratelimitmock is a generated GoMock package.
package ratelimitmock

import (
	context "context"
	reflect "reflect"

	ratelimit "github.com/NVIDIA/nvcf/llm-api-gateway/ratelimit"
	gomock "go.uber.org/mock/gomock"
)

// MockRateLimiter is a mock of RateLimiter interface.
type MockRateLimiter struct {
	ctrl     *gomock.Controller
	recorder *MockRateLimiterMockRecorder
	isgomock struct{}
}

// MockRateLimiterMockRecorder is the mock recorder for MockRateLimiter.
type MockRateLimiterMockRecorder struct {
	mock *MockRateLimiter
}

// NewMockRateLimiter creates a new mock instance.
func NewMockRateLimiter(ctrl *gomock.Controller) *MockRateLimiter {
	mock := &MockRateLimiter{ctrl: ctrl}
	mock.recorder = &MockRateLimiterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRateLimiter) EXPECT() *MockRateLimiterMockRecorder {
	return m.recorder
}

// CheckLimit mocks base method.
func (m *MockRateLimiter) CheckLimit(ctx context.Context, key string, l ratelimit.RateLimit, tokensRequested int64, testOnly bool, requestID string, mustConsume bool) (*ratelimit.RateLimitResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckLimit", ctx, key, l, tokensRequested, testOnly, requestID, mustConsume)
	ret0, _ := ret[0].(*ratelimit.RateLimitResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckLimit indicates an expected call of CheckLimit.
func (mr *MockRateLimiterMockRecorder) CheckLimit(ctx, key, l, tokensRequested, testOnly, requestID, mustConsume any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckLimit", reflect.TypeOf((*MockRateLimiter)(nil).CheckLimit), ctx, key, l, tokensRequested, testOnly, requestID, mustConsume)
}

// Reset mocks base method.
func (m *MockRateLimiter) Reset(ctx context.Context, key ...string) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range key {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Reset", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Reset indicates an expected call of Reset.
func (mr *MockRateLimiterMockRecorder) Reset(ctx any, key ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, key...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reset", reflect.TypeOf((*MockRateLimiter)(nil).Reset), varargs...)
}
