#!/bin/bash
# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

#
# Configure containerd for GPU checkpoint/restore
# This script configures containerd to:
#   1. Use forked CRIU for checkpoint operations
#   2. Set appropriate timeouts for large images
#   3. Enable checkpoint feature
#
# Usage:
#   ./configure-containerd.sh              # Run locally
#   ./configure-containerd.sh --remote IP  # Run on remote node
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

log_info()  { echo -e "${GREEN}[INFO]${NC} $*"; }
log_warn()  { echo -e "${YELLOW}[WARN]${NC} $*"; }
log_error() { echo -e "${RED}[ERROR]${NC} $*"; }

# Load credentials
load_credentials() {
    if [[ -f "$HOME/.nvsnap/credentials" ]]; then
        source "$HOME/.nvsnap/credentials"
    fi
}

# The actual configuration script to run on the node
configure_containerd() {
    cat << 'CONFIGURE_SCRIPT'
#!/bin/bash
set -e

echo "=== Configuring containerd for GPU checkpoint/restore ==="

# Backup current config
CONTAINERD_CONFIG="/etc/containerd/config.toml"
BACKUP_FILE="/etc/containerd/config.toml.backup.$(date +%Y%m%d_%H%M%S)"

if [[ -f "$CONTAINERD_CONFIG" ]]; then
    echo "Backing up current config to $BACKUP_FILE"
    cp "$CONTAINERD_CONFIG" "$BACKUP_FILE"
fi

# Check for forked CRIU
CRIU_PATH="/usr/local/sbin/criu"
if [[ ! -x "$CRIU_PATH" ]]; then
    echo "ERROR: Forked CRIU not found at $CRIU_PATH"
    exit 1
fi
echo "Found CRIU at $CRIU_PATH: $($CRIU_PATH --version 2>&1 | head -1)"

# Generate new containerd config
echo "Generating new containerd configuration..."

cat > "$CONTAINERD_CONFIG" << 'EOF'
# Containerd configuration for NVSNAP
# Generated by configure-containerd.sh
version = 3

# Root directory for containerd metadata
root = "/var/lib/containerd"
state = "/run/containerd"

# GRPC configuration
[grpc]
  address = "/run/containerd/containerd.sock"
  uid = 0
  gid = 0

# Timeouts - increased for large ML image checkpoints
[timeouts]
  "io.containerd.timeout.bolt.open" = "0s"
  "io.containerd.timeout.shim.cleanup" = "5s"
  "io.containerd.timeout.shim.load" = "5s"
  "io.containerd.timeout.shim.shutdown" = "3s"
  "io.containerd.timeout.task.state" = "2s"

[plugins]
  # CRI plugin configuration
  [plugins."io.containerd.cri.v1.runtime"]
    # Sandbox (pause) image
    sandbox_image = "registry.k8s.io/pause:3.10"
    
    # Enable CDI for GPU device injection
    enable_cdi = true
    cdi_spec_dirs = ["/etc/cdi", "/var/run/cdi"]
    
    [plugins."io.containerd.cri.v1.runtime".containerd]
      # Default to nvidia runtime for GPU support
      default_runtime_name = "nvidia"
      
      # Disable apparmor for checkpoint compatibility
      disable_apparmor = true
      
      [plugins."io.containerd.cri.v1.runtime".containerd.runtimes]
        # NVIDIA runtime configuration
        [plugins."io.containerd.cri.v1.runtime".containerd.runtimes.nvidia]
          runtime_type = "io.containerd.runc.v2"
          privileged_without_host_devices = false
          
          [plugins."io.containerd.cri.v1.runtime".containerd.runtimes.nvidia.options]
            BinaryName = "/usr/bin/nvidia-container-runtime"
            SystemdCgroup = true
        
        # Standard runc runtime (fallback)
        [plugins."io.containerd.cri.v1.runtime".containerd.runtimes.runc]
          runtime_type = "io.containerd.runc.v2"
          [plugins."io.containerd.cri.v1.runtime".containerd.runtimes.runc.options]
            SystemdCgroup = true

  # Internal plugin for checkpoint functionality
  [plugins."io.containerd.internal.v1.opt"]
    path = "/opt/containerd"

  # Transfer service configuration
  [plugins."io.containerd.transfer.v1.local"]
    # Increase max concurrent downloads for large images
    max_concurrent_downloads = 3
    max_concurrent_uploaded_layers = 3

# Debug/logging
[debug]
  level = "info"
EOF

echo "Configuration written to $CONTAINERD_CONFIG"

# Create CRIU config directory
CRIU_CONFIG_DIR="/etc/criu"
mkdir -p "$CRIU_CONFIG_DIR"

# Create CRIU default configuration
cat > "$CRIU_CONFIG_DIR/default.conf" << 'EOF'
# CRIU default configuration for NVSNAP
# Timeout for checkpoint operations (in seconds)
timeout 300

# Enable TCP connection handling
tcp-established

# Skip in-flight TCP connections (they'll need to be re-established)
skip-in-flight

# Enable shell-job mode for containers
shell-job

# Logging
verbosity 1
log-file /var/log/criu.log
EOF

echo "CRIU config written to $CRIU_CONFIG_DIR/default.conf"

# Create log directory
mkdir -p /var/log/criu
chmod 755 /var/log/criu

# Restart containerd to apply changes
echo "Restarting containerd..."
systemctl daemon-reload
systemctl restart containerd

# Wait for containerd to be ready
sleep 5

# Verify containerd is running
if systemctl is-active --quiet containerd; then
    echo "containerd restarted successfully"
else
    echo "ERROR: containerd failed to start"
    systemctl status containerd
    exit 1
fi

# Verify crictl can connect
echo "Verifying crictl connection..."
crictl info > /dev/null 2>&1 && echo "crictl connected successfully" || echo "WARNING: crictl connection failed"

echo ""
echo "=== Configuration Complete ==="
echo "containerd is configured to use:"
echo "  - NVIDIA container runtime as default"
echo "  - Forked CRIU at $CRIU_PATH"
echo "  - Extended timeouts for large images"
echo ""
echo "Next: Test checkpoint with 'crictl checkpoint <container-id>'"
CONFIGURE_SCRIPT
}

# Run on remote node
run_remote() {
    local node="$1"
    load_credentials
    
    if [[ -z "${SSH_USER:-}" || -z "${SSH_PASS:-}" ]]; then
        log_error "SSH_USER and SSH_PASS required. Set in ~/.nvsnap/credentials"
        exit 1
    fi
    
    log_info "Configuring containerd on $node..."
    
    # Create temp script
    local temp_script
    temp_script=$(mktemp)
    configure_containerd > "$temp_script"
    chmod +x "$temp_script"
    
    # Copy and execute
    sshpass -p "$SSH_PASS" scp -o StrictHostKeyChecking=no -o PubkeyAuthentication=no \
        "$temp_script" "${SSH_USER}@${node}:/tmp/configure_containerd.sh"
    
    sshpass -p "$SSH_PASS" ssh -o StrictHostKeyChecking=no -o PubkeyAuthentication=no \
        "${SSH_USER}@${node}" "sudo bash /tmp/configure_containerd.sh"
    
    rm -f "$temp_script"
    log_info "Configuration complete on $node"
}

# Run locally
run_local() {
    if [[ $EUID -ne 0 ]]; then
        log_error "This script must be run as root"
        exit 1
    fi
    configure_containerd | bash
}

# Main
main() {
    echo "╔═══════════════════════════════════════════════════════════════╗"
    echo "║     Configure containerd for GPU Checkpoint/Restore           ║"
    echo "╚═══════════════════════════════════════════════════════════════╝"
    echo ""
    
    if [[ "${1:-}" == "--remote" && -n "${2:-}" ]]; then
        run_remote "$2"
    elif [[ "${1:-}" == "--all" ]]; then
        load_credentials
        if [[ -f "$HOME/.nvsnap/cluster.yaml" ]]; then
            # Get nodes from cluster config
            nodes=$(grep -E "^\s+-?\s*ip:" "$HOME/.nvsnap/cluster.yaml" | awk '{print $NF}')
            for node in $nodes; do
                run_remote "$node"
                echo ""
            done
        else
            log_error "No cluster config found at ~/.nvsnap/cluster.yaml"
            exit 1
        fi
    else
        run_local
    fi
}

main "$@"
