# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

# API Keys values for standalone installation
# Replace <REGISTRY> and <REPOSITORY> with your container registry settings.

apikeys:
  fullnameOverride: api-keys
  image:
    registry: "<REGISTRY>"
    repository: "<REPOSITORY>/nv-api-keys"

  # Uncomment for node selectors
  # nodeSelector:
  #   nvcf.nvidia.com/workload: control-plane
