# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

# ESS API values for standalone installation
# Replace <REGISTRY> and <REPOSITORY> with your container registry settings.

ess:
  fullnameOverride: ess-api
  image:
    registry: "<REGISTRY>"
    repository: "<REPOSITORY>/ess-api"
