// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.29.1
// source: ratelimiter.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RateLimitResult int32

const (
	RateLimitResult_ALLOW    RateLimitResult = 0
	RateLimitResult_DISALLOW RateLimitResult = 1
)

// Enum value maps for RateLimitResult.
var (
	RateLimitResult_name = map[int32]string{
		0: "ALLOW",
		1: "DISALLOW",
	}
	RateLimitResult_value = map[string]int32{
		"ALLOW":    0,
		"DISALLOW": 1,
	}
)

func (x RateLimitResult) Enum() *RateLimitResult {
	p := new(RateLimitResult)
	*p = x
	return p
}

func (x RateLimitResult) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RateLimitResult) Descriptor() protoreflect.EnumDescriptor {
	return file_ratelimiter_proto_enumTypes[0].Descriptor()
}

func (RateLimitResult) Type() protoreflect.EnumType {
	return &file_ratelimiter_proto_enumTypes[0]
}

func (x RateLimitResult) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RateLimitResult.Descriptor instead.
func (RateLimitResult) EnumDescriptor() ([]byte, []int) {
	return file_ratelimiter_proto_rawDescGZIP(), []int{0}
}

type RateLimitRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NcaId             string `protobuf:"bytes,1,opt,name=ncaId,proto3" json:"ncaId,omitempty"`
	FunctionId        string `protobuf:"bytes,2,opt,name=functionId,proto3" json:"functionId,omitempty"`
	FunctionVersionId string `protobuf:"bytes,3,opt,name=functionVersionId,proto3" json:"functionVersionId,omitempty"`
}

func (x *RateLimitRequest) Reset() {
	*x = RateLimitRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ratelimiter_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RateLimitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateLimitRequest) ProtoMessage() {}

func (x *RateLimitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ratelimiter_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateLimitRequest.ProtoReflect.Descriptor instead.
func (*RateLimitRequest) Descriptor() ([]byte, []int) {
	return file_ratelimiter_proto_rawDescGZIP(), []int{0}
}

func (x *RateLimitRequest) GetNcaId() string {
	if x != nil {
		return x.NcaId
	}
	return ""
}

func (x *RateLimitRequest) GetFunctionId() string {
	if x != nil {
		return x.FunctionId
	}
	return ""
}

func (x *RateLimitRequest) GetFunctionVersionId() string {
	if x != nil {
		return x.FunctionVersionId
	}
	return ""
}

type RateLimitResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result RateLimitResult `protobuf:"varint,1,opt,name=result,proto3,enum=nvcfratelimiter.RateLimitResult" json:"result,omitempty"`
}

func (x *RateLimitResponse) Reset() {
	*x = RateLimitResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ratelimiter_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RateLimitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateLimitResponse) ProtoMessage() {}

func (x *RateLimitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ratelimiter_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateLimitResponse.ProtoReflect.Descriptor instead.
func (*RateLimitResponse) Descriptor() ([]byte, []int) {
	return file_ratelimiter_proto_rawDescGZIP(), []int{1}
}

func (x *RateLimitResponse) GetResult() RateLimitResult {
	if x != nil {
		return x.Result
	}
	return RateLimitResult_ALLOW
}

var File_ratelimiter_proto protoreflect.FileDescriptor

var file_ratelimiter_proto_rawDesc = []byte{
	0x0a, 0x11, 0x72, 0x61, 0x74, 0x65, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x6e, 0x76, 0x63, 0x66, 0x72, 0x61, 0x74, 0x65, 0x6c, 0x69, 0x6d,
	0x69, 0x74, 0x65, 0x72, 0x22, 0x76, 0x0a, 0x10, 0x52, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x6d, 0x69,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6e, 0x63, 0x61, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6e, 0x63, 0x61, 0x49, 0x64, 0x12, 0x1e,
	0x0a, 0x0a, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x2c,
	0x0a, 0x11, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x66, 0x75, 0x6e, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x22, 0x4d, 0x0a, 0x11,
	0x52, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x38, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x20, 0x2e, 0x6e, 0x76, 0x63, 0x66, 0x72, 0x61, 0x74, 0x65, 0x6c, 0x69, 0x6d, 0x69,
	0x74, 0x65, 0x72, 0x2e, 0x52, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x2a, 0x2a, 0x0a, 0x0f, 0x52,
	0x61, 0x74, 0x65, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x09,
	0x0a, 0x05, 0x41, 0x4c, 0x4c, 0x4f, 0x57, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x44, 0x49, 0x53,
	0x41, 0x4c, 0x4c, 0x4f, 0x57, 0x10, 0x01, 0x32, 0x68, 0x0a, 0x10, 0x52, 0x61, 0x74, 0x65, 0x4c,
	0x69, 0x6d, 0x69, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x54, 0x0a, 0x09, 0x52,
	0x61, 0x74, 0x65, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x21, 0x2e, 0x6e, 0x76, 0x63, 0x66, 0x72,
	0x61, 0x74, 0x65, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x65, 0x72, 0x2e, 0x52, 0x61, 0x74, 0x65, 0x4c,
	0x69, 0x6d, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x6e, 0x76,
	0x63, 0x66, 0x72, 0x61, 0x74, 0x65, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x65, 0x72, 0x2e, 0x52, 0x61,
	0x74, 0x65, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ratelimiter_proto_rawDescOnce sync.Once
	file_ratelimiter_proto_rawDescData = file_ratelimiter_proto_rawDesc
)

func file_ratelimiter_proto_rawDescGZIP() []byte {
	file_ratelimiter_proto_rawDescOnce.Do(func() {
		file_ratelimiter_proto_rawDescData = protoimpl.X.CompressGZIP(file_ratelimiter_proto_rawDescData)
	})
	return file_ratelimiter_proto_rawDescData
}

var file_ratelimiter_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_ratelimiter_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ratelimiter_proto_goTypes = []interface{}{
	(RateLimitResult)(0),      // 0: nvcfratelimiter.RateLimitResult
	(*RateLimitRequest)(nil),  // 1: nvcfratelimiter.RateLimitRequest
	(*RateLimitResponse)(nil), // 2: nvcfratelimiter.RateLimitResponse
}
var file_ratelimiter_proto_depIdxs = []int32{
	0, // 0: nvcfratelimiter.RateLimitResponse.result:type_name -> nvcfratelimiter.RateLimitResult
	1, // 1: nvcfratelimiter.RateLimitService.RateLimit:input_type -> nvcfratelimiter.RateLimitRequest
	2, // 2: nvcfratelimiter.RateLimitService.RateLimit:output_type -> nvcfratelimiter.RateLimitResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ratelimiter_proto_init() }
func file_ratelimiter_proto_init() {
	if File_ratelimiter_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ratelimiter_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RateLimitRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ratelimiter_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RateLimitResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ratelimiter_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ratelimiter_proto_goTypes,
		DependencyIndexes: file_ratelimiter_proto_depIdxs,
		EnumInfos:         file_ratelimiter_proto_enumTypes,
		MessageInfos:      file_ratelimiter_proto_msgTypes,
	}.Build()
	File_ratelimiter_proto = out.File
	file_ratelimiter_proto_rawDesc = nil
	file_ratelimiter_proto_goTypes = nil
	file_ratelimiter_proto_depIdxs = nil
}
