/*
SPDX-FileCopyrightText: Copyright (c) NVIDIA CORPORATION & AFFILIATES. All rights reserved.
SPDX-License-Identifier: Apache-2.0

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package cmd

import (
	"bufio"
	"context"
	"fmt"
	"os"
	"strconv"
	"strings"
	"time"

	"nvcf-cli/internal/apikeys"
	"nvcf-cli/internal/client"
	"nvcf-cli/internal/logging"
	"nvcf-cli/internal/state"

	"github.com/spf13/cobra"
	"github.com/spf13/viper"
)

// getConfigValueWithDefault reads configuration value with proper priority order:
// 1. Environment variable (highest priority - explicit user override)
// 2. Config file via Viper (static configuration)
// 3. Default value (lowest priority - fallback)
func getConfigValueWithDefault(key, defaultValue string) string {
	// Priority 1: Environment variable
	if envValue := os.Getenv(key); envValue != "" {
		return envValue
	}
	// Priority 2: Config file (via Viper)
	if viper.IsSet(key) {
		return viper.GetString(key)
	}
	// Priority 3: Default value
	return defaultValue
}

// apikeyCmd represents the api-key command group
var apikeyCmd = &cobra.Command{
	Use:   "api-key",
	Short: "Manage API keys for NVCF operations",
	Long: `Manage API keys for NVIDIA Cloud Functions operations.

API keys are used for function invocation and listing operations, while
admin tokens (from 'nvcf-cli init') are used for function management
operations like create, deploy, and delete.

Commands:
  generate    Generate a new API key with specified scopes and expiration
  list        List all existing API keys for the current owner
  delete      Delete a specific API key by ID
  revoke      Revoke a specific API key by ID (same as delete)
  show        Show the current saved API key from state
  clear       Clear the saved API key from state
  clear-all   Delete all API keys for an owner (bulk operation)`,
}

// apikeyGenerateCmd represents the api-key generate command
var apikeyGenerateCmd = &cobra.Command{
	Use:   "generate",
	Short: "Generate a new API key",
	Long: `Generate a new API key for NVCF operations.

This command creates a new API key with the following scopes by default:
- invoke_function: Invoke functions
- list_functions: List available functions  
- queue_details: Access queue information
- list_functions_details: Get detailed function information

You can specify custom scopes using the --scopes flag. If no scopes are provided,
the default scopes above will be used automatically.

The generated API key is automatically saved to the CLI state and can be
used for subsequent function invocation operations.

Examples:
  # Generate API key with default settings (24h expiration, default scopes)
  nvcf-cli api-key generate

  # Generate API key with custom expiration
  nvcf-cli api-key generate --expires-in 48h

  # Generate API key with custom description
  nvcf-cli api-key generate --description "Development testing key"

  # Generate API key with custom scopes
  nvcf-cli api-key generate --scopes invoke_function,list_functions

  # Generate API key with extended scopes (if you have permissions)
  nvcf-cli api-key generate --scopes invoke_function,list_functions,queue_details,register_function

  # Generate and validate the key
  nvcf-cli api-key generate --validate

  # Generate with all options
  nvcf-cli api-key generate --expires-in 7d --description "Custom API key" --scopes invoke_function,list_functions --validate`,
	RunE: runAPIKeyGenerate,
}

var (
	apikeyExpiresIn   string
	apikeyDescription string
	apikeyValidate    bool
	apikeyScopes      []string
)

func init() {
	rootCmd.AddCommand(apikeyCmd)

	// Add all subcommands
	apikeyCmd.AddCommand(apikeyGenerateCmd)
	apikeyCmd.AddCommand(apikeyListCmd)
	apikeyCmd.AddCommand(apikeyDeleteCmd)
	apikeyCmd.AddCommand(apikeyRevokeCmd)
	apikeyCmd.AddCommand(apikeyShowCmd)
	apikeyCmd.AddCommand(apikeyClearCmd)
	apikeyCmd.AddCommand(apikeyClearAllCmd)

	// Add flags for API key generation
	apikeyGenerateCmd.Flags().StringVar(&apikeyExpiresIn, "expires-in", "24h", "API key expiration duration (e.g., 24h, 7d, 168h)")
	apikeyGenerateCmd.Flags().StringVar(&apikeyDescription, "description", "Generated by nvcf-cli", "API key description")
	apikeyGenerateCmd.Flags().BoolVar(&apikeyValidate, "validate", false, "Validate the generated API key after creation")
	apikeyGenerateCmd.Flags().StringSliceVar(&apikeyScopes, "scopes", nil, "Custom scopes for the API key (comma-separated). If empty, uses default scopes: invoke_function,list_functions,queue_details,list_functions_details,manage_registries")

	// Add flags for API key deletion and revocation
	apikeyDeleteCmd.Flags().BoolVar(&deleteForce, "force", false, "Force delete without confirmation")
	apikeyRevokeCmd.Flags().BoolVar(&deleteForce, "force", false, "Force revoke without confirmation")

	// Add flags for API key clearing
	apikeyClearCmd.Flags().BoolVar(&clearForce, "force", false, "Skip confirmation prompt")
	apikeyClearAllCmd.Flags().BoolVar(&clearForce, "force", false, "Skip confirmation prompt")
}

func runAPIKeyGenerate(cmd *cobra.Command, args []string) error {
	// Load state
	if err := state.Load(); err != nil {
		logging.Warning("Could not load existing state: %v", err)
	}

	// Load configuration
	config, err := client.LoadConfig()
	if err != nil {
		return fmt.Errorf("failed to load configuration: %w", err)
	}

	// Parse expiration duration (with support for days/weeks)
	duration, err := parseExtendedDuration(apikeyExpiresIn)
	if err != nil {
		return fmt.Errorf("invalid expiration duration '%s': %w", apikeyExpiresIn, err)
	}

	expirationTime := time.Now().Add(duration)
	if !IsJSONOutput() {
		logging.Info("Generating API key...")
		logging.Info("Description: %s", apikeyDescription)
		logging.Info("Expires: %s", expirationTime.Format("2006-01-02 15:04:05 MST"))
	}

	// Generate the API key
	apiKey, err := generateAPIKey(config, apikeyDescription, expirationTime, apikeyScopes)
	if err != nil {
		return fmt.Errorf("failed to generate API key: %w", err)
	}

	if apiKey == "" {
		return fmt.Errorf("received empty API key from generation service")
	}

	// Save API key to state
	currentState := state.GetState()
	state.SetTokens(currentState.Token, apiKey, currentState.TokenExpiration, expirationTime)
	if err := state.Save(); err != nil {
		logging.Warning("Failed to save API key to state: %v", err)
	}

	var validationError string
	var validated bool

	// Validate the key if requested
	if apikeyValidate {
		if !IsJSONOutput() {
			logging.Info("Validating generated API key...")
		}
		if err := validateAPIKey(config, apiKey); err != nil {
			validationError = err.Error()
			if !IsJSONOutput() {
				logging.Warning("API key validation failed: %v", err)
			}
		} else {
			validated = true
			if !IsJSONOutput() {
				logging.Success("API key validation passed!")
			}
		}
	}

	if IsJSONOutput() {
		return OutputJSON(map[string]interface{}{
			"apiKey":          apiKey,
			"description":     apikeyDescription,
			"expiresAt":       expirationTime,
			"scopes":          apikeyScopes,
			"validated":       validated,
			"validationError": validationError,
		})
	}

	logging.Success("API key generated successfully!")
	logging.Plain("API Key: %s", apiKey)
	logging.Plain("Expires: %s", expirationTime.Format("2006-01-02 15:04:05 MST"))

	return nil
}

// generateAPIKey generates a new API key via direct API call
func generateAPIKey(config *client.Config, description string, expiresAt time.Time, customScopes []string) (string, error) {
	ctx := context.Background()

	// Create API Keys service client
	apiKeysConfig := &apikeys.Config{
		ServiceURL:    getConfigValueWithDefault("api_keys_service_url", "https://api-keys.nvcf.nvidia.com"),
		ServiceID:     getConfigValueWithDefault("API_KEYS_SERVICE_ID", "nvidia-cloud-functions-ncp-service-id-aketm"),
		IssuerService: getConfigValueWithDefault("API_KEYS_ISSUER_SERVICE", "nvcf-api"),
		OwnerID:       getConfigValueWithDefault("API_KEYS_OWNER_ID", "svc@nvcf-api.local"),
		JWTToken:      config.Token,                                   // Pass the JWT token for authentication
		HostHeader:    getConfigValueWithDefault("api_keys_host", ""), // Host header for self-hosted routing
		Debug:         config.Debug,
	}

	apiKeysClient := apikeys.NewClient(apiKeysConfig)

	// Generate the API key
	return apiKeysClient.GenerateAPIKey(ctx, description, expiresAt, customScopes)
}

// validateAPIKey validates the generated API key using kubectl run to call the API keys service
func validateAPIKey(config *client.Config, apiKey string) error {
	ctx := context.Background()

	// Create API Keys service client
	apiKeysConfig := &apikeys.Config{
		ServiceURL:    getConfigValueWithDefault("api_keys_service_url", "https://api-keys.nvcf.nvidia.com"),
		ServiceID:     getConfigValueWithDefault("API_KEYS_SERVICE_ID", "nvidia-cloud-functions-ncp-service-id-aketm"),
		IssuerService: getConfigValueWithDefault("API_KEYS_ISSUER_SERVICE", "nvcf-api"),
		OwnerID:       getConfigValueWithDefault("API_KEYS_OWNER_ID", "svc@nvcf-api.local"),
		JWTToken:      config.Token,                                   // Pass the JWT token for authentication
		HostHeader:    getConfigValueWithDefault("api_keys_host", ""), // Host header for self-hosted routing
		Debug:         config.Debug,
	}

	apiKeysClient := apikeys.NewClient(apiKeysConfig)

	// Validate the API key
	valid, err := apiKeysClient.ValidateAPIKey(ctx, apiKey)
	if err != nil {
		return fmt.Errorf("API key validation failed: %w", err)
	}

	if !valid {
		return fmt.Errorf("API key validation returned not allowed")
	}

	logging.Success("API key validation passed!")
	return nil
}

// apikeyListCmd represents the api-key list command
var apikeyListCmd = &cobra.Command{
	Use:   "list",
	Short: "List all API keys",
	Long: `List all existing API keys for the current owner.

This command displays all API keys with their IDs, descriptions, 
creation dates, expiration dates, and status.

Examples:
  # List all API keys
  nvcf-cli api-key list`,
	RunE: runListAPIKeys,
}

// apikeyDeleteCmd represents the api-key delete command
var apikeyDeleteCmd = &cobra.Command{
	Use:   "delete <key-id>",
	Short: "Delete an API key",
	Long: `Delete a specific API key by its ID.

Once deleted, the API key will no longer be valid for authentication
and cannot be recovered.

Examples:
  # Delete an API key by ID
  nvcf-cli api-key delete key-abc123def456

  # Force delete without confirmation
  nvcf-cli api-key delete key-abc123def456 --force`,
	Args: cobra.ExactArgs(1),
	RunE: runDeleteAPIKey,
}

// apikeyRevokeCmd represents the api-key revoke command
var apikeyRevokeCmd = &cobra.Command{
	Use:   "revoke <key-id>",
	Short: "Revoke an API key",
	Long: `Revoke a specific API key by its ID.

This is functionally equivalent to the delete command. Once revoked,
the API key will no longer be valid for authentication.

Examples:
  # Revoke an API key by ID (interactive confirmation)
  nvcf-cli api-key revoke key-abc123def456

  # Force revoke without confirmation
  nvcf-cli api-key revoke key-abc123def456 --force`,
	Args: cobra.ExactArgs(1),
	RunE: runRevokeAPIKey,
}

// apikeyShowCmd represents the api-key show command
var apikeyShowCmd = &cobra.Command{
	Use:   "show",
	Short: "Show the current saved API key",
	Long: `Show the API key that is currently saved in the CLI state.

This displays the API key stored in the state file, along with its 
expiration time if available. If no API key is saved, this command
will indicate that no API key is found.

Examples:
  # Show the current saved API key
  nvcf-cli api-key show`,
	RunE: runShowAPIKey,
}

// apikeyClearCmd represents the api-key clear command
var apikeyClearCmd = &cobra.Command{
	Use:   "clear",
	Short: "Clear the saved API key from state",
	Long: `Clear the API key that is currently saved in the CLI state.

This removes the API key from the local state file. The API key itself
remains valid and can still be used if you have it stored elsewhere,
but the CLI will no longer use it automatically for operations.

You will be prompted to confirm unless you use the --force flag.

Examples:
  # Clear the saved API key (with confirmation prompt)
  nvcf-cli api-key clear

  # Clear without confirmation prompt
  nvcf-cli api-key clear --force`,
	RunE: runClearAPIKey,
}

// apikeyClearAllCmd represents the api-key clear-all command
var apikeyClearAllCmd = &cobra.Command{
	Use:   "clear-all [owner-id]",
	Short: "Delete all API keys for an owner",
	Long: `Delete all API keys for a specified owner ID.

If no owner ID is provided, it will delete all API keys for the 
default owner configured in the CLI. This command will list all
keys found and delete them one by one.

WARNING: This action cannot be undone. All API keys for the specified
owner will be permanently deleted and immediately invalidated.

Examples:
  # Delete all API keys for the default owner
  nvcf-cli api-key clear-all

  # Delete all API keys for a specific owner
  nvcf-cli api-key clear-all user@example.com

  # Force delete without confirmation
  nvcf-cli api-key clear-all --force`,
	Args: cobra.MaximumNArgs(1),
	RunE: runClearAllAPIKeys,
}

var (
	deleteForce bool
	clearForce  bool
)

func runListAPIKeys(cmd *cobra.Command, args []string) error {
	// Load configuration
	config, err := client.LoadConfig()
	if err != nil {
		return fmt.Errorf("failed to load configuration: %w", err)
	}

	logging.Info("Listing API keys...")

	ctx := context.Background()

	// Create API Keys service client
	apiKeysConfig := &apikeys.Config{
		ServiceURL:    getConfigValueWithDefault("api_keys_service_url", "https://api-keys.nvcf.nvidia.com"),
		ServiceID:     getConfigValueWithDefault("API_KEYS_SERVICE_ID", "nvidia-cloud-functions-ncp-service-id-aketm"),
		IssuerService: getConfigValueWithDefault("API_KEYS_ISSUER_SERVICE", "nvcf-api"),
		OwnerID:       getConfigValueWithDefault("API_KEYS_OWNER_ID", "svc@nvcf-api.local"),
		JWTToken:      config.Token,                                   // Pass the JWT token for authentication
		HostHeader:    getConfigValueWithDefault("api_keys_host", ""), // Host header for self-hosted routing
		Debug:         config.Debug,
	}

	apiKeysClient := apikeys.NewClient(apiKeysConfig)

	// List API keys
	keys, err := apiKeysClient.ListAPIKeys(ctx)
	if err != nil {
		return fmt.Errorf("failed to list API keys: %w", err)
	}
	if IsJSONOutput() {
		return OutputJSON(map[string]interface{}{
			"keys": keys,
		})
	}

	if len(keys) == 0 {
		logging.Info("No API keys found")
		return nil
	}

	// Display the keys
	logging.Success("Found %d API key(s):", len(keys))
	logging.Plain("")
	logging.Plain("%-20s %-30s %-25s %-25s %-10s", "ID", "Description", "Created", "Expires", "Status")
	logging.Plain("%-20s %-30s %-25s %-25s %-10s", "----", "-----------", "-------", "-------", "------")

	for _, key := range keys {
		created := key.CreatedAt.Format("2006-01-02 15:04:05")
		expires := key.ExpiresAt.Format("2006-01-02 15:04:05")

		// Truncate description if too long
		description := key.Description
		if len(description) > 28 {
			description = description[:25] + "..."
		}

		logging.Plain("%-20s %-30s %-25s %-25s %-10s",
			key.ID, description, created, expires, key.Status)
	}

	return nil
}

func runDeleteAPIKey(cmd *cobra.Command, args []string) error {
	keyID := args[0]

	// Load configuration
	config, err := client.LoadConfig()
	if err != nil {
		return fmt.Errorf("failed to load configuration: %w", err)
	}

	// Interactive confirmation prompt unless --force is used
	if !deleteForce {
		logging.Warning("Are you sure you want to delete API key '%s'?", keyID)
		logging.Plain("This action cannot be undone. The API key will be immediately invalidated.")

		if !promptForConfirmation("Do you want to proceed?") {
			logging.Info("Deletion cancelled by user")
			return nil
		}
	}

	logging.Info("Deleting API key: %s", keyID)

	ctx := context.Background()

	// Create API Keys service client
	apiKeysConfig := &apikeys.Config{
		ServiceURL:    getConfigValueWithDefault("api_keys_service_url", "https://api-keys.nvcf.nvidia.com"),
		ServiceID:     getConfigValueWithDefault("API_KEYS_SERVICE_ID", "nvidia-cloud-functions-ncp-service-id-aketm"),
		IssuerService: getConfigValueWithDefault("API_KEYS_ISSUER_SERVICE", "nvcf-api"),
		OwnerID:       getConfigValueWithDefault("API_KEYS_OWNER_ID", "svc@nvcf-api.local"),
		JWTToken:      config.Token,                                   // Pass the JWT token for authentication
		HostHeader:    getConfigValueWithDefault("api_keys_host", ""), // Host header for self-hosted routing
		Debug:         config.Debug,
	}

	apiKeysClient := apikeys.NewClient(apiKeysConfig)

	// Delete the API key
	err = apiKeysClient.DeleteAPIKey(ctx, keyID)
	if err != nil {
		return fmt.Errorf("failed to delete API key: %w", err)
	}
	if IsJSONOutput() {
		return OutputJSON(map[string]interface{}{
			"status": "deleted",
			"keyId":  keyID,
		})
	}

	logging.Success("API key '%s' deleted successfully", keyID)
	return nil
}

func runRevokeAPIKey(cmd *cobra.Command, args []string) error {
	keyID := args[0]

	// Load configuration
	config, err := client.LoadConfig()
	if err != nil {
		return fmt.Errorf("failed to load configuration: %w", err)
	}

	// Interactive confirmation prompt unless --force is used
	if !deleteForce {
		logging.Warning("Are you sure you want to revoke API key '%s'?", keyID)
		logging.Plain("This action cannot be undone. The API key will be immediately invalidated.")

		if !promptForConfirmation("Do you want to proceed?") {
			logging.Info("Revocation cancelled by user")
			return nil
		}
	}

	logging.Info("Revoking API key: %s", keyID)

	ctx := context.Background()

	// Create API Keys service client
	apiKeysConfig := &apikeys.Config{
		ServiceURL:    getConfigValueWithDefault("api_keys_service_url", "https://api-keys.nvcf.nvidia.com"),
		ServiceID:     getConfigValueWithDefault("API_KEYS_SERVICE_ID", "nvidia-cloud-functions-ncp-service-id-aketm"),
		IssuerService: getConfigValueWithDefault("API_KEYS_ISSUER_SERVICE", "nvcf-api"),
		OwnerID:       getConfigValueWithDefault("API_KEYS_OWNER_ID", "svc@nvcf-api.local"),
		JWTToken:      config.Token,                                   // Pass the JWT token for authentication
		HostHeader:    getConfigValueWithDefault("api_keys_host", ""), // Host header for self-hosted routing
		Debug:         config.Debug,
	}

	apiKeysClient := apikeys.NewClient(apiKeysConfig)

	// Revoke the API key
	err = apiKeysClient.RevokeAPIKey(ctx, keyID)
	if err != nil {
		return fmt.Errorf("failed to revoke API key: %w", err)
	}
	if IsJSONOutput() {
		return OutputJSON(map[string]interface{}{
			"status": "revoked",
			"keyId":  keyID,
		})
	}

	logging.Success("API key '%s' revoked successfully", keyID)
	return nil
}

func runShowAPIKey(cmd *cobra.Command, args []string) error {
	// Load state
	if err := state.Load(); err != nil {
		logging.Warning("Could not load existing state: %v", err)
	}

	currentState := state.GetState()

	if currentState.APIKey == "" {
		if IsJSONOutput() {
			return OutputJSON(map[string]interface{}{
				"hasKey": false,
			})
		}
		logging.Info("No API key found in state")
		logging.Plain("Use 'nvcf-cli api-key generate' to create one")
		return nil
	}

	if IsJSONOutput() {
		return OutputJSON(map[string]interface{}{
			"hasKey":    true,
			"apiKey":    currentState.APIKey,
			"expiresAt": currentState.APIKeyExpiration,
		})
	}

	logging.Success("Current saved API key:")
	logging.Plain("API Key: %s", currentState.APIKey)

	if !currentState.APIKeyExpiration.IsZero() {
		if time.Now().After(currentState.APIKeyExpiration) {
			logging.Warning("Expires: %s (EXPIRED)", currentState.APIKeyExpiration.Format("2006-01-02 15:04:05 MST"))
		} else {
			logging.Plain("Expires: %s", currentState.APIKeyExpiration.Format("2006-01-02 15:04:05 MST"))
		}
	}

	return nil
}

func runClearAPIKey(cmd *cobra.Command, args []string) error {
	// Load state
	if err := state.Load(); err != nil {
		logging.Warning("Could not load existing state: %v", err)
	}

	currentState := state.GetState()

	if currentState.APIKey == "" {
		if IsJSONOutput() {
			return OutputJSON(map[string]interface{}{
				"status": "no_key",
			})
		}
		logging.Info("No API key found in state to clear")
		return nil
	}

	// Confirmation prompt unless --force is used
	if !clearForce {
		logging.Warning("This will remove the API key from local state.")
		logging.Plain("The key itself remains valid but the CLI will no longer use it automatically.")
		logging.Plain("")

		if !promptForConfirmation("Are you sure you want to clear the saved API key?") {
			logging.Info("Clear cancelled.")
			return nil
		}
	}

	// Clear the API key from state
	state.SetTokens(currentState.Token, "", currentState.TokenExpiration, time.Time{})
	if err := state.Save(); err != nil {
		return fmt.Errorf("failed to save cleared state: %w", err)
	}
	if IsJSONOutput() {
		return OutputJSON(map[string]interface{}{
			"status": "cleared",
		})
	}

	logging.Success("API key cleared from state")
	return nil
}

func runClearAllAPIKeys(cmd *cobra.Command, args []string) error {
	// Load configuration
	config, err := client.LoadConfig()
	if err != nil {
		return fmt.Errorf("failed to load configuration: %w", err)
	}

	// Determine owner ID
	ownerID := getConfigValueWithDefault("API_KEYS_OWNER_ID", "svc@nvcf-api.local")
	if len(args) > 0 && args[0] != "" {
		ownerID = args[0]
	}

	logging.Info("Fetching all API keys for owner: %s", ownerID)

	ctx := context.Background()

	// Create API Keys service client
	apiKeysConfig := &apikeys.Config{
		ServiceURL:    getConfigValueWithDefault("api_keys_service_url", "https://api-keys.nvcf.nvidia.com"),
		ServiceID:     getConfigValueWithDefault("API_KEYS_SERVICE_ID", "nvidia-cloud-functions-ncp-service-id-aketm"),
		IssuerService: getConfigValueWithDefault("API_KEYS_ISSUER_SERVICE", "nvcf-api"),
		OwnerID:       ownerID,
		HostHeader:    getConfigValueWithDefault("api_keys_host", ""), // Host header for self-hosted routing
		Debug:         config.Debug,
	}

	apiKeysClient := apikeys.NewClient(apiKeysConfig)

	// List all API keys for this owner
	keys, err := apiKeysClient.ListAPIKeys(ctx)
	if err != nil {
		return fmt.Errorf("failed to list API keys: %w", err)
	}

	if len(keys) == 0 {
		if IsJSONOutput() {
			return OutputJSON(map[string]interface{}{
				"ownerId": ownerID,
				"deleted": 0,
				"total":   0,
			})
		}
		logging.Info("No API keys found for owner: %s", ownerID)
		return nil
	}

	logging.Info("Found %d API key(s) to delete", len(keys))

	// Interactive confirmation prompt unless --force is used
	if !clearForce {
		logging.Warning("Are you sure you want to delete ALL %d API key(s) for owner '%s'?", len(keys), ownerID)
		logging.Plain("This action cannot be undone. All keys will be immediately invalidated.")
		logging.Plain("Keys to be deleted:")
		for _, key := range keys {
			logging.Plain("  - %s (%s)", key.ID, key.Description)
		}

		if !promptForConfirmation("Do you want to proceed?") {
			logging.Info("Bulk deletion cancelled by user")
			return nil
		}
	}

	// Delete all keys
	deletedCount := 0
	for _, key := range keys {
		logging.Info("Deleting key: %s (%s)", key.ID, key.Description)
		err = apiKeysClient.DeleteAPIKey(ctx, key.ID)
		if err != nil {
			logging.Error("Failed to delete key %s: %v", key.ID, err)
		} else {
			logging.Success("Deleted key: %s", key.ID)
			deletedCount++
		}
	}
	if IsJSONOutput() {
		return OutputJSON(map[string]interface{}{
			"ownerId": ownerID,
			"deleted": deletedCount,
			"total":   len(keys),
		})
	}

	logging.Success("Successfully deleted %d out of %d API key(s) for owner: %s", deletedCount, len(keys), ownerID)

	// Clear local API key if we deleted keys for the current configured owner
	currentConfigOwner := getConfigValueWithDefault("API_KEYS_OWNER_ID", "svc@nvcf-api.local")
	if ownerID == currentConfigOwner && deletedCount > 0 {
		// Load and clear state
		if err := state.Load(); err == nil {
			currentState := state.GetState()
			if currentState.APIKey != "" {
				state.SetTokens(currentState.Token, "", currentState.TokenExpiration, time.Time{})
				if err := state.Save(); err != nil {
					logging.Warning("Failed to clear local API key from state: %v", err)
				} else {
					logging.Info("Cleared local API key from state since it may have been deleted")
				}
			}
		}
	}

	return nil
}

// parseExtendedDuration parses duration strings with support for days (d) and weeks (w)
func parseExtendedDuration(s string) (time.Duration, error) {
	// First try Go's standard parser
	if d, err := time.ParseDuration(s); err == nil {
		return d, nil
	}

	// Handle days and weeks manually
	if len(s) < 2 {
		return 0, fmt.Errorf("invalid duration format")
	}

	unit := s[len(s)-1:]
	valueStr := s[:len(s)-1]

	switch unit {
	case "d":
		// Parse days
		days, err := strconv.Atoi(valueStr)
		if err != nil {
			return 0, fmt.Errorf("invalid number of days: %s", valueStr)
		}
		return time.Duration(days) * 24 * time.Hour, nil

	case "w":
		// Parse weeks
		weeks, err := strconv.Atoi(valueStr)
		if err != nil {
			return 0, fmt.Errorf("invalid number of weeks: %s", valueStr)
		}
		return time.Duration(weeks) * 7 * 24 * time.Hour, nil

	default:
		// Try Go's parser one more time and return its error
		return time.ParseDuration(s)
	}
}

// promptForConfirmation asks the user for yes/no confirmation
// Returns true if user confirms (y/yes), false otherwise
func promptForConfirmation(message string) bool {
	reader := bufio.NewReader(os.Stdin)

	fmt.Printf("%s (y/n): ", message)

	response, err := reader.ReadString('\n')
	if err != nil {
		return false
	}

	response = strings.ToLower(strings.TrimSpace(response))
	return response == "y" || response == "yes"
}
