// SPDX-FileCopyrightText: Copyright (c) NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package main

import (
	"bytes"
	"errors"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"text/template"

	"gopkg.in/yaml.v3"
)

const pipelineTemplate = `# Generated by go run ./tools/generate-subproject-ci --config {{ yamlValue .ConfigPath }}.
default:
  tags:
{{- range .DefaultTags }}
    - {{ yamlValue . }}
{{- end }}

stages:
  - validate
{{- range .Jobs }}

{{ .Name }}:
  stage: {{ yamlValue .Stage }}
  image: {{ yamlValue .Image }}
{{- if .Variables }}
  variables:
{{- range .VariablePairs }}
    {{ .Key }}: {{ yamlValue .Value }}
{{- end }}
{{- end }}
  rules:
{{- if .AlwaysRun }}
    - when: always
{{- else }}
    - if: '$PARENT_PIPELINE_SOURCE == "schedule" || $PARENT_PIPELINE_SOURCE == "web"'
    - changes:
{{- range .Changes }}
        - {{ yamlValue . }}
{{- end }}
    - when: never
{{- end }}
  script:
{{- range .Script }}
    - {{ yamlValue . }}
{{- end }}
{{- if .Coverage }}
  coverage: {{ yamlValue .Coverage }}
{{- end }}
{{- if .Artifacts }}
  artifacts:
    when: always
    paths:
{{- range .Artifacts.Paths }}
      - {{ yamlValue . }}
{{- end }}
    expire_in: {{ yamlValue .Artifacts.ExpireIn }}
{{- end }}
{{- end }}
`

const goWorkTemplate = `// Generated by go run -C tools/generate-subproject-ci . --config {{ .ConfigPath }} --go-work-output go.work.
go {{ .GoVersion }}

use (
{{- range .Use }}
	./{{ . }}
{{- end }}
)
`

type args struct {
	ConfigPath       string
	OutputPath       string
	GoWorkOutputPath string
}

type configFile struct {
	Version           int                `yaml:"version"`
	DefaultTags       []string           `yaml:"default_tags"`
	GoWork            *goWorkConfig      `yaml:"go_work"`
	SharedChangePaths []string           `yaml:"shared_change_paths"`
	Profiles          map[string]profile `yaml:"profiles"`
	Subprojects       []subproject       `yaml:"subprojects"`
}

type goWorkConfig struct {
	Go  string   `yaml:"go"`
	Use []string `yaml:"use"`
}

type profile struct {
	Stage     string            `yaml:"stage"`
	Image     string            `yaml:"image"`
	Variables map[string]string `yaml:"variables"`
	Checks    []check           `yaml:"checks"`
}

type subproject struct {
	ID          string   `yaml:"id"`
	Path        string   `yaml:"path"`
	Profile     string   `yaml:"profile"`
	ChangePaths []string `yaml:"change_paths"`
	GoWork      bool     `yaml:"go_work"`
}

type check struct {
	ID         string   `yaml:"id"`
	Type       string   `yaml:"type"`
	Command    string   `yaml:"command"`
	Install    []string `yaml:"install"`
	ResultsDir string   `yaml:"results_dir"`
	Coverage   string   `yaml:"coverage"`
	Artifacts  []string `yaml:"artifacts"`
	ExpireIn   string   `yaml:"expire_in"`
}

type subprojectTemplateData struct {
	ID   string
	Path string
}

type generatedPipeline struct {
	ConfigPath  string
	DefaultTags []string
	Jobs        []generatedJob
}

type generatedJob struct {
	Name      string
	Stage     string
	Image     string
	Variables map[string]string
	Changes   []string
	AlwaysRun bool
	Script    []string
	Coverage  string
	Artifacts *artifacts
}

type artifacts struct {
	Paths    []string
	ExpireIn string
}

type keyValue struct {
	Key   string
	Value string
}

type generatedJobView struct {
	Name          string
	Stage         string
	Image         string
	Variables     map[string]string
	VariablePairs []keyValue
	Changes       []string
	AlwaysRun     bool
	Script        []string
	Coverage      string
	Artifacts     *artifacts
}

func main() {
	if err := run(os.Args[1:], os.Stdout); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func run(argv []string, stdout *os.File) error {
	parsed, err := parseArgs(argv)
	if err != nil {
		return err
	}

	cfg, err := loadConfig(parsed.ConfigPath)
	if err != nil {
		return err
	}

	if parsed.GoWorkOutputPath != "" {
		renderedGoWork, err := renderGoWork(cfg, parsed.ConfigPath)
		if err != nil {
			return err
		}
		if err := os.WriteFile(parsed.GoWorkOutputPath, []byte(renderedGoWork), 0o644); err != nil {
			return err
		}
	}

	if parsed.OutputPath == "" && parsed.GoWorkOutputPath != "" {
		return nil
	}

	rendered, err := renderPipeline(cfg, parsed.ConfigPath)
	if err != nil {
		return err
	}

	if parsed.OutputPath == "" {
		_, err = stdout.WriteString(rendered)
		return err
	}

	return os.WriteFile(parsed.OutputPath, []byte(rendered), 0o644)
}

func parseArgs(argv []string) (args, error) {
	fs := flag.NewFlagSet("generate-subproject-ci", flag.ContinueOnError)
	fs.SetOutput(os.Stderr)

	parsed := args{
		ConfigPath: "tools/ci/subproject-validations.yaml",
	}
	fs.StringVar(&parsed.ConfigPath, "config", parsed.ConfigPath, "path to subproject validation config")
	fs.StringVar(&parsed.OutputPath, "output", "", "path to write generated child pipeline yaml")
	fs.StringVar(&parsed.GoWorkOutputPath, "go-work-output", "", "path to write generated go.work")

	if err := fs.Parse(argv); err != nil {
		return args{}, err
	}
	if fs.NArg() != 0 {
		return args{}, fmt.Errorf("unexpected arguments: %s", strings.Join(fs.Args(), " "))
	}
	return parsed, nil
}

func loadConfig(path string) (configFile, error) {
	raw, err := os.ReadFile(path)
	if err != nil {
		return configFile{}, err
	}

	var cfg configFile
	if err := yaml.Unmarshal(raw, &cfg); err != nil {
		return configFile{}, err
	}
	if err := validateConfig(cfg); err != nil {
		return configFile{}, err
	}
	return cfg, nil
}

func validateConfig(cfg configFile) error {
	if cfg.Version != 1 {
		return fmt.Errorf("unsupported config version %d", cfg.Version)
	}
	if len(cfg.DefaultTags) == 0 {
		return errors.New("default_tags must not be empty")
	}
	if len(cfg.Profiles) == 0 {
		return errors.New("profiles must not be empty")
	}
	if cfg.GoWork != nil {
		if strings.TrimSpace(cfg.GoWork.Go) == "" {
			return errors.New("go_work.go must not be empty")
		}
	}

	seenSubprojects := map[string]struct{}{}
	for _, subproject := range cfg.Subprojects {
		if strings.TrimSpace(subproject.ID) == "" {
			return errors.New("subproject id must not be empty")
		}
		if _, exists := seenSubprojects[subproject.ID]; exists {
			return fmt.Errorf("duplicate subproject id %q", subproject.ID)
		}
		seenSubprojects[subproject.ID] = struct{}{}
		if strings.TrimSpace(subproject.Path) == "" {
			return fmt.Errorf("subproject %q path must not be empty", subproject.ID)
		}
		if subproject.GoWork && cfg.GoWork == nil {
			return fmt.Errorf("subproject %q sets go_work but config does not define top-level go_work settings", subproject.ID)
		}
		profile, ok := cfg.Profiles[subproject.Profile]
		if !ok {
			return fmt.Errorf("subproject %q references unknown profile %q", subproject.ID, subproject.Profile)
		}
		if strings.TrimSpace(profile.Image) == "" {
			return fmt.Errorf("profile %q image must not be empty", subproject.Profile)
		}
		if len(profile.Checks) == 0 {
			return fmt.Errorf("profile %q must define at least one check", subproject.Profile)
		}
		for _, chk := range profile.Checks {
			if err := validateCheck(subproject.Profile, chk); err != nil {
				return err
			}
		}
	}
	return nil
}

func validateCheck(profileName string, chk check) error {
	if strings.TrimSpace(chk.ID) == "" {
		return fmt.Errorf("profile %q has check with empty id", profileName)
	}
	switch chk.Type {
	case "go-vendor":
		return nil
	case "go-codegen":
		if strings.TrimSpace(chk.Command) == "" {
			return fmt.Errorf("profile %q check %q must set command", profileName, chk.ID)
		}
		return nil
	case "go-unit-tests":
		return nil
	case "shell":
		if strings.TrimSpace(chk.Command) == "" {
			return fmt.Errorf("profile %q check %q must set command", profileName, chk.ID)
		}
		return nil
	case "go-workspace-shell":
		if strings.TrimSpace(chk.Command) == "" {
			return fmt.Errorf("profile %q check %q must set command", profileName, chk.ID)
		}
		return nil
	default:
		return fmt.Errorf("profile %q check %q uses unsupported type %q", profileName, chk.ID, chk.Type)
	}
}

func renderPipeline(cfg configFile, configPath string) (string, error) {
	pipeline := generatedPipeline{
		ConfigPath:  configPath,
		DefaultTags: cfg.DefaultTags,
	}

	for _, subproject := range cfg.Subprojects {
		profile := cfg.Profiles[subproject.Profile]
		for _, chk := range profile.Checks {
			job, err := buildJob(cfg.SharedChangePaths, profile, subproject, chk)
			if err != nil {
				return "", err
			}
			pipeline.Jobs = append(pipeline.Jobs, job)
		}
	}

	// GitLab fails a triggered child pipeline that ends up with zero jobs (for
	// example, when a change only touches files not listed in any job's
	// `changes:` rule, like a docs-only MR). Emit an unconditional sentinel so
	// the child pipeline always has at least one job to run.
	pipeline.Jobs = append(pipeline.Jobs, generatedJob{
		Name:      "subproject-validations-sentinel",
		Stage:     "validate",
		Image:     "golang:1.26-bookworm",
		AlwaysRun: true,
		Script:    []string{"echo 'subproject-validations: no path-gated jobs matched this change set.'"},
	})

	tmpl, err := template.New("pipeline").Funcs(template.FuncMap{
		"yamlValue": yamlScalar,
	}).Parse(pipelineTemplate)
	if err != nil {
		return "", err
	}

	view := struct {
		ConfigPath  string
		DefaultTags []string
		Jobs        []generatedJobView
	}{
		ConfigPath:  pipeline.ConfigPath,
		DefaultTags: pipeline.DefaultTags,
		Jobs:        make([]generatedJobView, 0, len(pipeline.Jobs)),
	}
	for _, job := range pipeline.Jobs {
		view.Jobs = append(view.Jobs, generatedJobView{
			Name:          job.Name,
			Stage:         job.Stage,
			Image:         job.Image,
			Variables:     job.Variables,
			VariablePairs: sortMap(job.Variables),
			Changes:       job.Changes,
			AlwaysRun:     job.AlwaysRun,
			Script:        job.Script,
			Coverage:      job.Coverage,
			Artifacts:     job.Artifacts,
		})
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, view); err != nil {
		return "", err
	}
	return buf.String(), nil
}

func renderGoWork(cfg configFile, configPath string) (string, error) {
	if cfg.GoWork == nil {
		return "", errors.New("go_work is not configured")
	}

	useSet := map[string]struct{}{}
	for _, path := range cfg.GoWork.Use {
		trimmed := filepath.ToSlash(strings.TrimSpace(path))
		trimmed = strings.TrimPrefix(trimmed, "./")
		if trimmed == "" {
			continue
		}
		useSet[trimmed] = struct{}{}
	}
	for _, subproject := range cfg.Subprojects {
		if !subproject.GoWork {
			continue
		}
		trimmed := filepath.ToSlash(strings.TrimSpace(subproject.Path))
		trimmed = strings.TrimPrefix(trimmed, "./")
		if trimmed == "" {
			continue
		}
		useSet[trimmed] = struct{}{}
	}

	if len(useSet) == 0 {
		return "", errors.New("go_work has no modules to include")
	}

	usePaths := make([]string, 0, len(useSet))
	for path := range useSet {
		usePaths = append(usePaths, path)
	}
	sort.Strings(usePaths)

	view := struct {
		ConfigPath string
		GoVersion  string
		Use        []string
	}{
		ConfigPath: configPath,
		GoVersion:  cfg.GoWork.Go,
		Use:        usePaths,
	}

	tmpl, err := template.New("goWork").Parse(goWorkTemplate)
	if err != nil {
		return "", err
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, view); err != nil {
		return "", err
	}
	return buf.String(), nil
}

func buildJob(sharedChangePaths []string, profile profile, subproject subproject, chk check) (generatedJob, error) {
	data := subprojectTemplateData{
		ID:   subproject.ID,
		Path: subproject.Path,
	}

	jobName := sanitizeJobName(subproject.ID + "-" + chk.ID)
	stage := profile.Stage
	if strings.TrimSpace(stage) == "" {
		stage = "validate"
	}

	script, err := buildScript(profile, data, chk)
	if err != nil {
		return generatedJob{}, err
	}

	changes := append([]string{}, sharedChangePaths...)
	if len(subproject.ChangePaths) > 0 {
		changes = append(changes, subproject.ChangePaths...)
	} else {
		changes = append(changes, filepath.ToSlash(filepath.Join(subproject.Path, "**/*")))
	}

	job := generatedJob{
		Name:      jobName,
		Stage:     stage,
		Image:     profile.Image,
		Variables: profile.Variables,
		Changes:   changes,
		Script:    script,
	}

	if strings.TrimSpace(chk.Coverage) != "" {
		job.Coverage, err = renderTemplateString(chk.Coverage, data)
		if err != nil {
			return generatedJob{}, fmt.Errorf("job %q coverage: %w", jobName, err)
		}
	}
	if len(chk.Artifacts) > 0 {
		paths := make([]string, 0, len(chk.Artifacts))
		for _, artifactPath := range chk.Artifacts {
			rendered, err := renderTemplateString(artifactPath, data)
			if err != nil {
				return generatedJob{}, fmt.Errorf("job %q artifact path: %w", jobName, err)
			}
			paths = append(paths, rendered)
		}
		expireIn := chk.ExpireIn
		if strings.TrimSpace(expireIn) == "" {
			expireIn = "30 days"
		}
		job.Artifacts = &artifacts{
			Paths:    paths,
			ExpireIn: expireIn,
		}
	}

	return job, nil
}

func buildScript(profile profile, subproject subprojectTemplateData, chk check) ([]string, error) {
	prefix := workspaceSetupScript(profile, chk)

	switch chk.Type {
	case "go-vendor":
		return append(prefix,
			fmt.Sprintf("./tools/ci/check-go-vendor %s", shellQuote(subproject.Path)),
		), nil
	case "go-codegen":
		command, err := renderTemplateString(chk.Command, subproject)
		if err != nil {
			return nil, err
		}
		line := fmt.Sprintf("./tools/ci/check-go-codegen %s --command %s", shellQuote(subproject.Path), shellQuote(command))
		for _, install := range chk.Install {
			expanded, err := renderTemplateString(install, subproject)
			if err != nil {
				return nil, err
			}
			line += " --install " + shellQuote(expanded)
		}
		return append(prefix, line), nil
	case "go-unit-tests":
		resultsDir := chk.ResultsDir
		if strings.TrimSpace(resultsDir) == "" {
			resultsDir = filepath.ToSlash(filepath.Join("public", subproject.ID))
		}
		expandedResults, err := renderTemplateString(resultsDir, subproject)
		if err != nil {
			return nil, err
		}
		return append(prefix,
			fmt.Sprintf("./tools/ci/run-go-unit-tests %s --results-dir %s", shellQuote(subproject.Path), shellQuote(expandedResults)),
		), nil
	case "shell":
		command, err := renderTemplateString(chk.Command, subproject)
		if err != nil {
			return nil, err
		}
		return append(prefix,
			fmt.Sprintf("cd \"$CI_PROJECT_DIR/%s\" && %s", subproject.Path, command),
		), nil
	case "go-workspace-shell":
		command, err := renderTemplateString(chk.Command, subproject)
		if err != nil {
			return nil, err
		}
		return append(prefix,
			fmt.Sprintf("cd \"$CI_PROJECT_DIR/%s\" && GOWORK=\"$CI_PROJECT_DIR/go.work\" %s", subproject.Path, command),
		), nil
	default:
		return nil, fmt.Errorf("unsupported check type %q", chk.Type)
	}
}

func workspaceSetupScript(profile profile, chk check) []string {
	if chk.Type == "go-workspace-shell" {
		return []string{"./tools/scripts/update-go-work"}
	}

	gowork, ok := profile.Variables["GOWORK"]
	if !ok {
		return nil
	}

	trimmed := strings.TrimSpace(gowork)
	if trimmed == "" || trimmed == "off" {
		return nil
	}

	return []string{"./tools/scripts/update-go-work"}
}

func renderTemplateString(input string, data subprojectTemplateData) (string, error) {
	tmpl, err := template.New("value").Option("missingkey=error").Parse(input)
	if err != nil {
		return "", err
	}
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", err
	}
	return buf.String(), nil
}

func sanitizeJobName(value string) string {
	lower := strings.ToLower(value)
	re := regexp.MustCompile(`[^a-z0-9]+`)
	lower = re.ReplaceAllString(lower, "-")
	lower = strings.Trim(lower, "-")
	if lower == "" {
		return "subproject-validation"
	}
	return lower
}

func shellQuote(value string) string {
	if value == "" {
		return "''"
	}
	return "'" + strings.ReplaceAll(value, "'", `'"'"'`) + "'"
}

func yamlScalar(value any) string {
	raw, err := yaml.Marshal(value)
	if err != nil {
		panic(err)
	}
	return strings.TrimSpace(string(raw))
}

func sortMap(values map[string]string) []keyValue {
	if len(values) == 0 {
		return nil
	}
	keys := make([]string, 0, len(values))
	for key := range values {
		keys = append(keys, key)
	}
	sort.Strings(keys)

	out := make([]keyValue, 0, len(keys))
	for _, key := range keys {
		out = append(out, keyValue{Key: key, Value: values[key]})
	}
	return out
}
