// SPDX-FileCopyrightText: Copyright (c) NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package main

import (
	"bytes"
	"errors"
	"flag"
	"fmt"
	"os"
	"path"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"text/template"

	"gopkg.in/yaml.v3"
)

const pipelineTemplate = `# Generated by go run ./tools/generate-subproject-ci --config {{ yamlValue .ConfigPath }}.
default:
  tags:
{{- range .DefaultTags }}
    - {{ yamlValue . }}
{{- end }}

stages:
  - validate
{{- range .Jobs }}

{{ .Name }}:
  stage: {{ yamlValue .Stage }}
  image: {{ yamlValue .Image }}
{{- if .Variables }}
  variables:
{{- range .VariablePairs }}
    {{ .Key }}: {{ yamlValue .Value }}
{{- end }}
{{- end }}
  rules:
{{- if .AlwaysRun }}
    - when: always
{{- else }}
    - if: '$PARENT_PIPELINE_SOURCE == "schedule" || $PARENT_PIPELINE_SOURCE == "web"'
    - changes:
{{- range .Changes }}
        - {{ yamlValue . }}
{{- end }}
    - when: never
{{- end }}
  script:
{{- range .Script }}
    - {{ yamlValue . }}
{{- end }}
{{- if .Coverage }}
  coverage: {{ yamlValue .Coverage }}
{{- end }}
{{- if .Artifacts }}
  artifacts:
    when: always
    paths:
{{- range .Artifacts.Paths }}
      - {{ yamlValue . }}
{{- end }}
    expire_in: {{ yamlValue .Artifacts.ExpireIn }}
{{- end }}
{{- end }}
`

// releasePipelineTemplate is the YAML the umbrella `.gitlab-ci.yml`
// includes via `include: local: tools/ci/generated-release-jobs.yml`.
// One block per opted-in service (release: declared in
// tools/ci/subproject-validations.yaml):
//
//   compute-next-release-version-<id>  semantic-release dry-run; emits
//                                      NEXT_VERSION dotenv (init stage).
//   semantic-release-<id>              real semantic-release run on
//                                      default branch; creates the
//                                      <service_name>-v<version> git
//                                      tag (publish stage).
//   <id>-image-push                    consumes NEXT_VERSION dotenv;
//                                      pushes to each image_push_targets
//                                      entry (Prerequisites stage).
//
// Hidden templates (.compute-next-release-version-service,
// .semantic-release-service) keep the boilerplate centralized so each
// concrete job only restates SUBTREE + SERVICE_NAME + path-gated rules.
const releasePipelineTemplate = `# Generated by go run -C tools/generate-subproject-ci . --config {{ yamlValue .ConfigPath }} --release-output tools/ci/generated-release-jobs.yml.
# DO NOT EDIT BY HAND. To change release behavior for a service, update
# tools/ci/subproject-validations.yaml and re-run the generator. The
# umbrella's check-release-pipeline-generated job verifies the
# committed file matches what the generator would emit on this commit.
{{- /* Pre-emit helm-package + helm-push-ngc cds-component include
       directives for every service that declared release.helm. The
       cds components live at github.com/NVIDIA/cds/cds-components;
       version pinned to 0.16.6 (matches the version dns-cache and
       other helm-publishing services used pre-cutover). */ -}}
{{- $hasHelm := false }}
{{- range .Services }}{{ if .Helm }}{{ $hasHelm = true }}{{ end }}{{ end }}
{{- if $hasHelm }}
include:
{{- range $svc := .Services }}
{{- if $svc.Helm }}
  - component: github.com/NVIDIA/cds/cds-components/helm-package@0.16.6
    inputs:
      job-name: helm-package-{{ $svc.ID }}
      chart-path: {{ yamlValue $svc.Helm.ChartPath }}
      chart-version: ${NEXT_VERSION}
{{- if $svc.Helm.Lint }}
      lint: true
{{- end }}
      extends: [.{{ $svc.ID }}-helm-package-extend]
{{- range $tgt := $svc.Helm.PushTargets }}
  - component: github.com/NVIDIA/cds/cds-components/helm-push-ngc@0.16.6
    inputs:
      job-name: helm-push-{{ $svc.ID }}-{{ $tgt.Name }}
      package-job: helm-package-{{ $svc.ID }}
      ngc-key: ${{ "{" }}{{ $tgt.NGCKeyVar }}{{ "}" }}
      ngc-path: {{ yamlValue $tgt.NGCPath }}
      extends: [.{{ $svc.ID }}-helm-push-extend]
{{- end }}
{{- end }}
{{- end }}
{{- end }}

.compute-next-release-version-service:
  extends:
    - .nv-vault
    - .vault-reader-settings
  stage: init
  image: ${CDS_TOOLS_IMAGE}
  tags: [eks, nvcf-cds, prod]
  variables:
    SECRETS_TO_RETRIEVE_IN_JSON: >
      [
        {
          "path": "kv/gitlab/semantic-release/gl-token",
          "key": "token",
          "env_var": "GL_TOKEN"
        }
      ]
  before_script:
    - !reference [.nv-vault, before_script]
    - !reference [.vault-reader-before-script, before_script]
    - cd "$SUBTREE"
    - |
      cat > package.json <<EOF
      {
        "name": "${SERVICE_NAME}",
        "version": "1.0.0",
        "private": true,
        "devDependencies": {
          "semantic-release": "17.4.4",
          "@semantic-release/gitlab": "^8.0.0",
          "semantic-release-monorepo": "^7.0.0"
        }
      }
      EOF
      cat package.json
    - |
      # semantic-release-monorepo (v7.x) is a SHAREABLE CONFIG, not a
      # CLI. It exposes no bin entry; using it via the extends field
      # is the only supported pattern. semantic-release reads extends
      # and merges the shareable config (which adds path-scoped
      # commit filtering based on package.json directory). The CLI to
      # run is plain semantic-release.
      cat > .releaserc.json <<EOF
      {
        "extends": "semantic-release-monorepo",
        "tagFormat": "${SERVICE_NAME}-v\${version}",
        "branches": ["main"],
        "plugins": [
          ["@semantic-release/commit-analyzer", {
            "releaseRules": [
              {"type": "feat", "release": "minor"},
              {"type": "fix", "release": "patch"},
              {"type": "chore", "release": "patch"},
              {"type": "refactor", "release": "patch"},
              {"type": "style", "release": "patch"},
              {"type": "docs", "release": "patch"},
              {"type": "ci", "release": "patch"},
              {"type": "perf", "release": "patch"}
            ]
          }],
          "@semantic-release/release-notes-generator",
          ["@semantic-release/gitlab", {
            "gitlabUrl": "https://github.com/NVIDIA",
            "assets": []
          }]
        ]
      }
      EOF
      cat .releaserc.json
    - npm install --legacy-peer-deps
  script:
    - |
      echo -e "\e[0Ksection_start:` + "`" + `date +%s` + "`" + `:semantic_release[collapsed=true]\r\e[0KSemantic-release debug output..."
      npx semantic-release --dry-run --no-ci --debug | tee semantic-release-output.log
      echo -e "\e[0Ksection_end:` + "`" + `date +%s` + "`" + `:semantic_release\r\e[0K"
    - npx semantic-release --dry-run --no-ci
    - |
      # Preserve the legacy cds/cicd-pipelines set_image_tag tag
      # shape so MR-preview images keep the mr.<iid>-<sha> format
      # the team consumed pre-Bazel, and default-branch publishes use
      # the bare semver. semantic-release wins when it has a release-
      # worthy commit and we are on the default branch; otherwise we
      # fall back to the legacy shape.
      NEXT_VERSION=$(awk '/next release version is/ {print $NF; exit}' semantic-release-output.log)
      if [ -z "$NEXT_VERSION" ]; then
        if [ -n "${CI_MERGE_REQUEST_IID:-}" ]; then
          NEXT_VERSION="mr.${CI_MERGE_REQUEST_IID}-${CI_COMMIT_SHORT_SHA}"
          SKIP_SEMANTIC_RELEASE=true
        elif [ -n "${CI_COMMIT_TAG:-}" ]; then
          # Tag pipeline. semantic-release's dry-run emits nothing
          # here because the tag already exists, so the awk above
          # produced an empty NEXT_VERSION. Derive it from the tag
          # instead. SKIP_SEMANTIC_RELEASE stays false so downstream
          # publish jobs (image-push, helm-package, helm-push) run
          # and stamp the artifact with the tag's semver, matching
          # what the originating default-branch pipeline pushed.
          NEXT_VERSION="${CI_COMMIT_TAG#${SERVICE_NAME}-v}"
          SKIP_SEMANTIC_RELEASE=false
        elif [ "$CI_COMMIT_BRANCH" = "$CI_DEFAULT_BRANCH" ]; then
          NEXT_VERSION=$(git describe --tags --match="${SERVICE_NAME}-v*" --abbrev=0 2>/dev/null | sed "s/^${SERVICE_NAME}-v//" || echo "0.0.0")
          SKIP_SEMANTIC_RELEASE=true
        else
          NEXT_VERSION="${CI_COMMIT_SHORT_SHA}"
          SKIP_SEMANTIC_RELEASE=true
        fi
      else
        SKIP_SEMANTIC_RELEASE=false
      fi
      echo "NEXT_VERSION=${NEXT_VERSION}  SKIP_SEMANTIC_RELEASE=${SKIP_SEMANTIC_RELEASE}"
    - |
      touch release.env
      echo "NEXT_VERSION=${NEXT_VERSION}" > release.env
      echo "SKIP_SEMANTIC_RELEASE=${SKIP_SEMANTIC_RELEASE}" >> release.env
      mv release.env "${CI_PROJECT_DIR}/release.env"
  artifacts:
    reports:
      dotenv: release.env

.semantic-release-service:
  extends:
    - .nv-vault
    - .vault-reader-settings
  stage: publish
  image: ${CDS_TOOLS_IMAGE}
  tags: [eks, nvcf-cds, prod]
  # Every per-service semantic-release run pushes to the same git ref
  # refs/notes/semantic-release. With multiple services releasing on
  # the same pipeline (5+ services in the cutover wave), parallel
  # pushes race and the second-to-arrive fails with
  # 'cannot lock ref ... but expected <stale-sha>'. semantic-release
  # v17 has no notes-ref override, so serialize via GitLab's
  # resource_group: jobs in the same group are run one at a time
  # (across the whole project, not just this pipeline), at the cost
  # of the parallel speedup on the publish stage only.
  resource_group: semantic-release-notes
  variables:
    SECRETS_TO_RETRIEVE_IN_JSON: >
      [
        {
          "path": "kv/gitlab/semantic-release/gl-token",
          "key": "token",
          "env_var": "GL_TOKEN"
        }
      ]
  before_script:
    - !reference [.nv-vault, before_script]
    - !reference [.vault-reader-before-script, before_script]
    - cd "$SUBTREE"
    - |
      cat > package.json <<EOF
      {
        "name": "${SERVICE_NAME}",
        "version": "1.0.0",
        "private": true,
        "devDependencies": {
          "semantic-release": "17.4.4",
          "@semantic-release/gitlab": "^8.0.0",
          "semantic-release-monorepo": "^7.0.0"
        }
      }
      EOF
    - |
      cat > .releaserc.json <<EOF
      {
        "extends": "semantic-release-monorepo",
        "tagFormat": "${SERVICE_NAME}-v\${version}",
        "branches": ["main"],
        "plugins": [
          ["@semantic-release/commit-analyzer", {
            "releaseRules": [
              {"type": "feat", "release": "minor"},
              {"type": "fix", "release": "patch"},
              {"type": "chore", "release": "patch"},
              {"type": "refactor", "release": "patch"},
              {"type": "style", "release": "patch"},
              {"type": "docs", "release": "patch"},
              {"type": "ci", "release": "patch"},
              {"type": "perf", "release": "patch"}
            ]
          }],
          "@semantic-release/release-notes-generator",
          ["@semantic-release/gitlab", {
            "gitlabUrl": "https://github.com/NVIDIA",
            "assets": []
          }]
        ]
      }
      EOF
    - npm install --legacy-peer-deps
  script:
    - |
      if [ "${SKIP_SEMANTIC_RELEASE}" = "true" ]; then
        echo "compute-next-release-version-${SERVICE_NAME} reported no semantic-release-worthy commit; skipping tag creation."
        exit 0
      fi
    - npx semantic-release --no-ci
{{- range $svc := .Services }}

compute-next-release-version-{{ .ID }}:
  extends: .compute-next-release-version-service
  variables:
    SUBTREE: {{ yamlValue .Path }}
    SERVICE_NAME: {{ yamlValue .ServiceName }}
  rules:
    - if: $CI_MERGE_REQUEST_IID
      changes: &{{ .RulesAnchor }}
{{- range .ChangePaths }}
        - {{ yamlValue . }}
{{- end }}
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes: *{{ .RulesAnchor }}
    # Tag pipelines need NEXT_VERSION too: the helm-package job's
    # chart-version input reads ${NEXT_VERSION}, and the image-push
    # job's NVCF_VERSION shell fallback consumes it when set. The
    # compute job's own script falls back to ${CI_COMMIT_TAG#${SERVICE_NAME}-v}
    # when semantic-release reports no new release, so on a tag
    # pipeline it produces NEXT_VERSION=<tag-semver>.
    - if: $CI_COMMIT_TAG =~ /^{{ .ServiceName }}-v/

semantic-release-{{ .ID }}:
  extends: .semantic-release-service
  variables:
    SUBTREE: {{ yamlValue .Path }}
    SERVICE_NAME: {{ yamlValue .ServiceName }}
  needs:
    - job: compute-next-release-version-{{ .ID }}
      artifacts: true
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes: *{{ .RulesAnchor }}

{{ .ID }}-image-push:
  extends:
    - .nv-vault
    - .vault-reader-settings
    - .bazel-remote-probe
  stage: Prerequisites
  image: $CI_REGISTRY_IMAGE/bazel-ci:$BAZEL_CI_VERSION
  needs:
    - job: bazel-ci-image
      optional: true
      artifacts: false
    - job: {{ .ID }}-bazel
      optional: true
    - job: compute-next-release-version-{{ .ID }}
      artifacts: true
      optional: true
  tags: [eks, nvcf-cds, prod]
  variables:
{{- if .HasVaultTarget }}
    NGC_REGISTRY_VAULT_KEY: {{ yamlValue .VaultKey }}
    SECRETS_TO_RETRIEVE_IN_JSON: >
      [
        {
          "path": "kv/gitlab/ngc-registry-auth/$NGC_REGISTRY_VAULT_KEY",
          "key": "NGC_REGISTRY",
          "env_var": "NGC_REGISTRY"
        },
        {
          "path": "kv/gitlab/ngc-registry-auth/$NGC_REGISTRY_VAULT_KEY",
          "key": "NGC_REGISTRY_TOKEN",
          "env_var": "NGC_REGISTRY_TOKEN"
        }
      ]
{{- end }}
    BAZEL_DISK_CACHE: $CI_PROJECT_DIR/.bazel-cache/disk
    BAZEL_REPO_CACHE: $CI_PROJECT_DIR/.bazel-cache/repo
  cache:
    - key:
        files:
          - {{ .Path }}/MODULE.bazel.lock
          - {{ .Path }}/.bazelversion
        prefix: {{ .ID }}-bazel-repo
      paths:
        - .bazel-cache/repo/
      policy: pull
    - key:
        files:
          - {{ .Path }}/.bazelversion
          - {{ .Path }}/.bazelrc
        prefix: {{ .ID }}-bazel-disk
      paths:
        - .bazel-cache/disk/
      policy: pull
  before_script:
{{- if .HasVaultTarget }}
    - !reference [.nv-vault, before_script]
    - !reference [.vault-reader-before-script, before_script]
{{- end }}
    - !reference [.bazel-remote-probe, before_script]
    - |
      BAZEL_REMOTE_FLAGS="${BAZEL_REMOTE_FLAGS//--config=remote-write /}"
      BAZEL_REMOTE_FLAGS="${BAZEL_REMOTE_FLAGS//--config=remote-write/}"
      export BAZEL_REMOTE_FLAGS
    - |
      if [ "${SKIP_SEMANTIC_RELEASE:-}" = "true" ] && [ -z "${CI_MERGE_REQUEST_IID:-}" ]; then
        echo "[{{ .ID }}-image-push] SKIP_SEMANTIC_RELEASE=true and not an MR pipeline; no new release-worthy commit since the last tag. Skipping image push to avoid overwriting an existing release tag."
        exit 0
      fi
    - |
      if [ -n "${NEXT_VERSION:-}" ]; then
        NVCF_VERSION="${NEXT_VERSION}"
      elif [ -n "${CI_COMMIT_TAG:-}" ]; then
        NVCF_VERSION="${CI_COMMIT_TAG#{{ .ServiceName }}-v}"
      elif [ -n "${CI_MERGE_REQUEST_IID:-}" ]; then
        NVCF_VERSION="mr.${CI_MERGE_REQUEST_IID}-${CI_COMMIT_SHORT_SHA}"
      else
        echo "[{{ .ID }}-image-push] ERROR: no NEXT_VERSION / CI_COMMIT_TAG / CI_MERGE_REQUEST_IID." >&2
        exit 1
      fi
      export NVCF_VERSION
      echo "[{{ .ID }}-image-push] using NVCF_VERSION=${NVCF_VERSION}"
    - |
      mkdir -p ~/.docker
{{- /* One "is var set" guard per unique CI variable used by ci_var
       targets. Multiple targets may share the same variable (e.g.
       dns-cache uses NGC_DEVOPS_API_KEY for both devops and ncp_dev
       pushes); without dedup the script emits the same guard
       back-to-back. */}}
{{- range $civar := .CIVars }}
      if [ -z "${ {{- $civar -}} :-}" ]; then
        echo "[{{ $svc.ID }}-image-push] ERROR: {{ $civar }} is not set; image push will fail." >&2
        exit 1
      fi
{{- end }}
{{- range .Targets }}
{{- if eq .AuthType "vault" }}
      {{ .Name | upper }}_AUTH=$(printf '$oauthtoken:%s' "${NGC_REGISTRY_TOKEN}" | base64 -w0)
{{- else if eq .AuthType "ci_var" }}
      {{ .Name | upper }}_AUTH=$(printf '$oauthtoken:%s' "${ {{- .CIVar -}} }" | base64 -w0)
{{- end }}
{{- end }}
  script:
    - cd {{ .Path }}
    # On MR pipelines do 'bazel build' (analyze + assemble image, no
    # push). That still exercises the full auth setup and base image
    # pull so docker-auth scoping bugs and base-image-availability bugs
    # surface in the MR pipeline instead of post-merge. Default-branch
    # and tag pipelines do 'bazel run' to actually push.
    - |
      if [ -n "${CI_MERGE_REQUEST_IID:-}" ]; then
        BAZEL_PUSH_VERB=build
      else
        BAZEL_PUSH_VERB=run
      fi
      export BAZEL_PUSH_VERB
      echo "[{{ .ID }}-image-push] bazel verb: ${BAZEL_PUSH_VERB}"
{{- range .Targets }}
{{- if eq .AuthType "vault" }}
    - |
      NGC_REGISTRY_HOST="${NGC_REGISTRY#https://}"
      NGC_REGISTRY_HOST="${NGC_REGISTRY_HOST#http://}"
      NGC_REGISTRY_HOST="${NGC_REGISTRY_HOST%%/*}"
{{- if .DockerAuthPath }}
      # Scope the auth key to the push destination so rules_oci does
      # not apply this token when pulling the base image (e.g. the
      # public nvcr.io/nvidia/distroless/cc that Rust services use as
      # their OCI base). rules_oci uses longest-prefix matching: a
      # bare "nvcr.io" key matches every nvcr.io URL including the
      # public distroless image, and the scoped NGC token's
      # permissions 403 the public read.
      DOCKER_AUTH_KEY={{ yamlValue .DockerAuthPath }}
{{- else }}
      DOCKER_AUTH_KEY="${NGC_REGISTRY_HOST}"
{{- end }}
      printf '{"auths":{"%s":{"auth":"%s"}}}\n' "${DOCKER_AUTH_KEY}" "${ {{- .Name | upper -}} _AUTH}" > ~/.docker/config.json
      chmod 600 ~/.docker/config.json
{{- else if eq .AuthType "ci_var" }}
    - |
{{- if .DockerAuthPath }}
      DOCKER_AUTH_KEY={{ yamlValue .DockerAuthPath }}
{{- else }}
      DOCKER_AUTH_KEY=nvcr.io
{{- end }}
      printf '{"auths":{"%s":{"auth":"%s"}}}\n' "${DOCKER_AUTH_KEY}" "${ {{- .Name | upper -}} _AUTH}" > ~/.docker/config.json
      chmod 600 ~/.docker/config.json
{{- end }}
    - bazel ${BAZEL_PUSH_VERB} --stamp ${BAZEL_REMOTE_FLAGS} --disk_cache=$BAZEL_DISK_CACHE --repository_cache=$BAZEL_REPO_CACHE {{ .BazelTarget }}
{{- end }}
  rules:
    # Run on every MR pipeline whose change_paths touch this service.
    # Script runs 'bazel build' (not 'run') in MR context so the build
    # exercises base-image pull and the full auth setup without
    # actually pushing. This catches docker-auth scoping bugs (the
    # NVCF-10337 nvcr.io 403 bug) before merge, instead of post-merge
    # on main.
    - if: $CI_MERGE_REQUEST_IID
      changes: *{{ .RulesAnchor }}
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes: *{{ .RulesAnchor }}
    - if: $CI_COMMIT_TAG =~ /^{{ .ServiceName }}-v/
{{- if .SlackChannel }}

# Slack release notification. Mirrors the legacy upstream's
# slack-notification job from cds/nvcf-cicd-pipeline. Posts to the
# backstage-helper notify_channel endpoint, which is the
# NVIDIA-internal indirection that handles Slack auth -- no token
# required in CI. Fires only on default-branch publishes after the
# real release tag is created.
{{ .ID }}-slack-notify:
  # Snapshot is the only umbrella stage after publish, where
  # semantic-release-<svc> lives. GitLab needs requires the
  # depended job to be in an earlier stage (same-stage needs error
  # with "not defined in current or prior stages"), so slack-notify
  # has to sit later than publish.
  stage: Snapshot
  image: dockerhub.nvidia.com/curlimages/curl:8.10.1
  needs:
    - job: semantic-release-{{ .ID }}
      artifacts: false
      optional: true
    - job: {{ .ID }}-image-push
      artifacts: false
      optional: true
  tags: [eks, nvcf-cds, prod]
  variables:
    SLACK_CHANNEL_ID: {{ yamlValue .SlackChannel }}
  script:
    - |
      # Prefer CI_COMMIT_TAG on tag pipelines so the message carries the
      # real semver (the legacy bug printed "tag: unknown" because git
      # describe runs against a shallow CI clone where the tag is not
      # reachable). Strip the service-name prefix so the message shows
      # just the version (e.g. "1.13.0" not "nvcf-ratelimiter-v1.13.0").
      if [ -n "${CI_COMMIT_TAG:-}" ]; then
        TAG_DISPLAY="${CI_COMMIT_TAG#{{ .ServiceName }}-v}"
      else
        TAG_DISPLAY=$(git describe --tags --match='{{ .ServiceName }}-v*' --abbrev=0 2>/dev/null | sed "s|^{{ .ServiceName }}-v||" || echo unknown)
      fi
      SLACK_MESSAGE=":rocket: ${SERVICE_NAME:-{{ .ServiceName }}} release pipeline complete | tag: ${TAG_DISPLAY} | sha: ${CI_COMMIT_SHORT_SHA} | <${CI_PIPELINE_URL}|pipeline ${CI_PIPELINE_ID}>"
      printf '{"channel_id":"%s","message":"%s"}\n' "${SLACK_CHANNEL_ID}" "${SLACK_MESSAGE}" > /tmp/slack.json
      curl -sSf -X POST 'https://backstage-helper.service.odp.nvidia.com/notify_channel?dry_run=false' \
        -H 'accept: application/json' \
        -H 'Content-Type: application/json' \
        -d @/tmp/slack.json
  rules:
    # Fire only on tag pipelines. The default-branch pipeline that
    # triggered semantic-release will create the tag, which spawns a
    # second (tag-ref) pipeline; this job runs there. Firing on both
    # would post duplicate Slack messages (observed on
    # nvcf-ratelimiter-v1.13.0 release).
    - if: $CI_COMMIT_TAG =~ /^{{ .ServiceName }}-v/
{{- end }}
{{- if .SonarqubeProjectKey }}

# Per-service Sonarqube analysis. Mirrors the legacy upstream's
# SONARQUBE_PROJECT_KEY configuration so each native subtree keeps
# its dedicated Sonar dashboard after archive. Reports findings only
# for the subtree's tree (sonar.sources), against the legacy project
# key. Runs alongside the umbrella's whole-repo sonarqube-analysis;
# the two are complementary.
{{ .ID }}-sonarqube-analysis:
  stage: Prerequisites
  image: sonarsource/sonar-scanner-cli:latest
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
    GIT_DEPTH: "0"
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  tags: [eks, nvcf-cds, prod]
  script:
    - cd {{ .Path }}
    - sonar-scanner
      -Dsonar.qualitygate.wait=true
      -Dsonar.host.url="${SONAR_HOST_URL}"
      -Dsonar.token="${SONAR_TOKEN}"
      -Dsonar.projectKey={{ yamlValue .SonarqubeProjectKey }}
      -Dsonar.sources=.
  allow_failure: true
  rules:
    - if: $SONARQUBE_ENABLED != 'true'
      when: never
    - if: $CI_MERGE_REQUEST_IID
      changes: *{{ .RulesAnchor }}
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes: *{{ .RulesAnchor }}
{{- end }}
{{- if .Helm }}

# Per-service extends consumed by the helm-package-{{ .ID }} and
# helm-push-{{ .ID }}-* jobs (instantiated from the cds-components
# include: block at the top of this file). The cds-component owns the
# concrete script (helm package + helm push to NGC); the extends below
# only add stage placement, needs, and the path-gated rules so the
# jobs run on the right pipeline kinds and pick up NEXT_VERSION from
# compute-next-release-version-{{ .ID }}'s dotenv.

.{{ .ID }}-helm-package-extend:
  stage: publish
  needs:
    - job: compute-next-release-version-{{ .ID }}
      artifacts: true
      # 'optional: true' so the YAML validator does not reject the
      # pipeline on tag refs where the depended job might not be
      # scheduled (matches the image-push pattern). On tag pipelines
      # compute-next-release-version-{{ .ID }} fires (its rules
      # include the {{ .ServiceName }}-v tag prefix) and supplies
      # the NEXT_VERSION dotenv that chart-version reads.
      optional: true
  rules:
    - if: $CI_COMMIT_TAG =~ /^{{ .ServiceName }}-v/
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes: *{{ .RulesAnchor }}

.{{ .ID }}-helm-push-extend:
  stage: publish
  rules:
    - if: $CI_COMMIT_TAG =~ /^{{ .ServiceName }}-v/
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes: *{{ .RulesAnchor }}
{{- end }}
{{- end }}
`

const goWorkTemplate = `// Generated by go run -C tools/generate-subproject-ci . --config {{ .ConfigPath }} --go-work-output go.work.
go {{ .GoVersion }}

use (
{{- range .Use }}
	./{{ . }}
{{- end }}
)
`

type releasePipelineView struct {
	ConfigPath string
	Services   []releaseServiceView
}

type releaseServiceView struct {
	ID                  string
	ServiceName         string
	Path                string
	ChangePaths         []string
	RulesAnchor         string
	Targets             []releaseTargetView
	HasVaultTarget      bool
	VaultKey            string
	// CIVars is the deduplicated set of CI/CD variable names used by
	// `ci_var` image push targets, in first-seen order. The template
	// emits one "is var set" guard per entry rather than one per
	// target, so a service whose targets share a CI variable (e.g.
	// dns-cache uses NGC_DEVOPS_API_KEY for both devops and ncp_dev
	// pushes) gets a single check instead of N redundant ones.
	CIVars              []string
	SlackChannel        string
	SonarqubeProjectKey string
	Helm                *releaseHelmView
}

// releaseHelmView mirrors helmConfig for the template, with the
// chart path pre-joined onto the service's subtree path so the
// generated YAML carries a fully-qualified path (the cds-component
// is invoked from the umbrella repo root, not the service subtree).
type releaseHelmView struct {
	ChartPath   string
	Lint        bool
	PushTargets []releaseHelmTargetView
}

type releaseHelmTargetView struct {
	Name string
	// NGCPath is the literal NGC org/team path the chart gets pushed
	// to (e.g. "0651155215864979/ncp-dev"). Already resolved by the
	// generator: if helmPushTarget.NGCPath was set, the literal value;
	// otherwise the `$VARNAME` reference to the CI variable.
	NGCPath   string
	NGCKeyVar string
}

type releaseTargetView struct {
	Name           string
	BazelTarget    string
	AuthType       string
	CIVar          string
	DockerAuthPath string
}

type args struct {
	ConfigPath        string
	OutputPath        string
	GoWorkOutputPath  string
	ReleaseOutputPath string
}

type configFile struct {
	Version           int                `yaml:"version"`
	DefaultTags       []string           `yaml:"default_tags"`
	GoWork            *goWorkConfig      `yaml:"go_work"`
	SharedChangePaths []string           `yaml:"shared_change_paths"`
	Profiles          map[string]profile `yaml:"profiles"`
	Subprojects       []subproject       `yaml:"subprojects"`
}

type goWorkConfig struct {
	Go  string   `yaml:"go"`
	Use []string `yaml:"use"`
}

type profile struct {
	Stage     string            `yaml:"stage"`
	Image     string            `yaml:"image"`
	Variables map[string]string `yaml:"variables"`
	Checks    []check           `yaml:"checks"`
}

type subproject struct {
	ID          string         `yaml:"id"`
	Path        string         `yaml:"path"`
	Profile     string         `yaml:"profile"`
	ChangePaths []string       `yaml:"change_paths"`
	GoWork      bool           `yaml:"go_work"`
	Release     *releaseConfig `yaml:"release,omitempty"`
}

// releaseConfig is the opt-in declaration for an umbrella-native
// service that wants auto-versioned releases via semantic-release.
// The generator emits compute-next-release-version-<id>,
// semantic-release-<id>, and <id>-image-push jobs into the release
// pipeline YAML the umbrella includes via `include: local: ...`.
//
// Tag format is hard-coded to ${service_name}-v${version} (same shape
// used by semantic-release-monorepo) so per-service tags don't
// collide with other services or with the umbrella's own tags.
type releaseConfig struct {
	ServiceName      string                  `yaml:"service_name"`
	ImagePushTargets []releaseImagePushTarget `yaml:"image_push_targets"`
	// SlackChannel, if non-empty, emits an additional
	// `<svc>-slack-notify` job that posts a release notification to
	// the named Slack channel after `semantic-release-<svc>` creates
	// the tag. Channel ID format is the Slack archives ID, e.g.
	// `C08S6KLCEJH` for `#nv-nvcf-cicd`. Empty disables the job.
	SlackChannel string `yaml:"slack_channel,omitempty"`
	// SonarqubeProjectKey, if non-empty, emits an additional
	// `<svc>-sonarqube-analysis` job that runs sonar-scanner against
	// the service's subtree under the named SonarQube project key.
	// Preserves the per-service Sonar dashboard each native cutover
	// had pre-archive (legacy SONARQUBE_PROJECT_KEY env var). Empty
	// disables the job; the umbrella's whole-tree sonarqube-analysis
	// continues to scan everything regardless.
	SonarqubeProjectKey string `yaml:"sonarqube_project_key,omitempty"`
	// Helm, if non-nil, declares that the service ships a Helm chart
	// the release pipeline should package and publish to NGC. The
	// generator emits `include:` directives at the top of the
	// generated YAML wiring in cds/cds-components/helm-package and
	// helm-push-ngc, parameterized per service. Chart version stamps
	// from semantic-release's NEXT_VERSION (same value as the OCI
	// image tag) so the chart, appVersion, and image tag stay
	// version-coherent. See HelmConfig for field-level docs.
	Helm *helmConfig `yaml:"helm,omitempty"`
}

// helmConfig declares the Helm chart packaging + push pipeline for a
// service. The generator wraps the cds-components helm-package@0.16.6
// + helm-push-ngc@0.16.6 templates, passing chart-version=$NEXT_VERSION
// at component-instantiation time so the packaged chart's version
// (and appVersion) line up with the service's semantic-release tag.
type helmConfig struct {
	// ChartPath is the directory containing Chart.yaml, relative to
	// the service's subtree root. For dns-cache that's `deploy`; for
	// nats-auth-callout it would be `chart`, etc.
	ChartPath string `yaml:"chart_path"`
	// Lint, if true, runs `helm lint` on the chart as part of the
	// package job. Off by default; turn on for new services where the
	// chart is under active development.
	Lint bool `yaml:"lint,omitempty"`
	// PushTargets is the list of NGC orgs the packaged chart gets
	// pushed to. The umbrella convention is that every service
	// includes ncp-dev (shared NGC_DEVOPS_API_KEY) and may also
	// include legacy targets (nv-ngc-devops, nvcf-internal) that
	// pre-Bazel CI used. At least one target is required.
	PushTargets []helmPushTarget `yaml:"push_targets"`
}

// helmPushTarget describes one NGC org the chart gets published to.
// Either NGCPath (hardcoded org/team path, e.g.
// "0651155215864979/ncp-dev") or NGCPathVar (the name of a CI
// variable that resolves to the path, e.g. "NGC_ORG_nv_ngc_devops")
// must be set; the generator validates exactly one is provided. The
// NGC key always comes from a CI variable name (NGCKeyVar) since
// the keys are protected secrets.
type helmPushTarget struct {
	// Name uniquely identifies this target within the service. Becomes
	// the suffix of the generated helm-push-<svc>-<name> job. Choose
	// short keys like "ncp-dev", "nv-ngc-devops", "nvcf-internal".
	Name string `yaml:"name"`
	// NGCPath is a literal org/team path on NGC, e.g.
	// "0651155215864979/ncp-dev". Mutually exclusive with NGCPathVar.
	NGCPath string `yaml:"ngc_path,omitempty"`
	// NGCPathVar is the name of a CI variable holding the NGC path
	// (e.g. "NGC_ORG_nv_ngc_devops"). The generator emits a `$VAR`
	// reference into the component input; resolution happens at
	// pipeline runtime. Mutually exclusive with NGCPath.
	NGCPathVar string `yaml:"ngc_path_var,omitempty"`
	// NGCKeyVar is the name of a CI variable holding the NGC API key
	// (e.g. "NGC_DEVOPS_API_KEY"). The generator emits a `$VAR`
	// reference into the component input. Required.
	NGCKeyVar string `yaml:"ngc_key_var"`
}

// releaseImagePushTarget describes one registry the image gets pushed
// to. Each target has its own Bazel push target (declared in the
// service's nvidia-internal/destinations.bzl) and its own auth source.
type releaseImagePushTarget struct {
	Name        string                 `yaml:"name"`
	BazelTarget string                 `yaml:"bazel_target"`
	Auth        releaseImagePushAuth   `yaml:"auth"`
	// DockerAuthPath, if set, is written as the key in
	// ~/.docker/config.json instead of the bare registry host. Use
	// when the service's base image lives on the same registry as the
	// push target (e.g. Rust services that pull `nvcr.io/nvidia/
	// distroless/cc` while pushing to `nvcr.io/<org>/<image>`).
	// rules_oci does longest-prefix matching on the auth keys; if the
	// scoped token's key is just "nvcr.io" it gets applied to every
	// nvcr.io pull including the public distroless base, and the
	// token's scoped permissions 403 the public read.
	//
	// Format: full path without scheme, e.g.
	//   `nvcr.io/ema5hzr4ziav/nvcf_autoscaling`
	//   `nvcr.io/0651155215864979/ncp-dev/nvcf-function-autoscaler`
	//
	// Optional. Empty falls back to the host-only key (works for
	// services whose base image isn't on the same registry).
	DockerAuthPath string `yaml:"docker_auth_path,omitempty"`
}

// releaseImagePushAuth holds the credential source for one push
// target. `type: vault` fetches NGC_REGISTRY + NGC_REGISTRY_TOKEN
// from kv/gitlab/ngc-registry-auth/<vault_key>. `type: ci_var`
// uses the named GitLab CI/CD variable directly (typically set at
// the nvcf group level so every project inherits it).
type releaseImagePushAuth struct {
	Type     string `yaml:"type"`
	VaultKey string `yaml:"vault_key,omitempty"`
	CIVar    string `yaml:"ci_var,omitempty"`
}

type check struct {
	ID         string   `yaml:"id"`
	Type       string   `yaml:"type"`
	Command    string   `yaml:"command"`
	Install    []string `yaml:"install"`
	ResultsDir string   `yaml:"results_dir"`
	Coverage   string   `yaml:"coverage"`
	Artifacts  []string `yaml:"artifacts"`
	ExpireIn   string   `yaml:"expire_in"`
	// Image overrides the profile's container image for this one
	// check. Useful when a single check needs a tool image (for
	// example a pre-built golangci-lint binary) instead of the
	// language toolchain image the rest of the profile shares.
	Image string `yaml:"image"`
	// SkipWorkspaceSetup opts out of the `./tools/scripts/update-go-work`
	// prefix that the profile's GOWORK variable would normally apply.
	// Useful when a check runs in an image without the project Go
	// toolchain (for example a pre-built lint image) and the check
	// command does not consult `go.work` itself.
	SkipWorkspaceSetup bool `yaml:"skip_workspace_setup"`
}

type subprojectTemplateData struct {
	ID   string
	Path string
}

type generatedPipeline struct {
	ConfigPath  string
	DefaultTags []string
	Jobs        []generatedJob
}

type generatedJob struct {
	Name      string
	Stage     string
	Image     string
	Variables map[string]string
	Changes   []string
	AlwaysRun bool
	Script    []string
	Coverage  string
	Artifacts *artifacts
}

type artifacts struct {
	Paths    []string
	ExpireIn string
}

type keyValue struct {
	Key   string
	Value string
}

type generatedJobView struct {
	Name          string
	Stage         string
	Image         string
	Variables     map[string]string
	VariablePairs []keyValue
	Changes       []string
	AlwaysRun     bool
	Script        []string
	Coverage      string
	Artifacts     *artifacts
}

func main() {
	if err := run(os.Args[1:], os.Stdout); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func run(argv []string, stdout *os.File) error {
	parsed, err := parseArgs(argv)
	if err != nil {
		return err
	}

	cfg, err := loadConfig(parsed.ConfigPath)
	if err != nil {
		return err
	}

	if parsed.GoWorkOutputPath != "" {
		renderedGoWork, err := renderGoWork(cfg, parsed.ConfigPath)
		if err != nil {
			return err
		}
		if err := os.WriteFile(parsed.GoWorkOutputPath, []byte(renderedGoWork), 0o644); err != nil {
			return err
		}
	}

	if parsed.ReleaseOutputPath != "" {
		renderedRelease, err := renderReleasePipeline(cfg, parsed.ConfigPath)
		if err != nil {
			return err
		}
		if err := os.WriteFile(parsed.ReleaseOutputPath, []byte(renderedRelease), 0o644); err != nil {
			return err
		}
	}

	if parsed.OutputPath == "" {
		// Only a non-default output path was requested (go-work
		// and/or release-output); skip the default child-pipeline
		// stdout dump.
		if parsed.GoWorkOutputPath != "" || parsed.ReleaseOutputPath != "" {
			return nil
		}
	}

	rendered, err := renderPipeline(cfg, parsed.ConfigPath)
	if err != nil {
		return err
	}

	if parsed.OutputPath == "" {
		_, err = stdout.WriteString(rendered)
		return err
	}

	return os.WriteFile(parsed.OutputPath, []byte(rendered), 0o644)
}

func parseArgs(argv []string) (args, error) {
	fs := flag.NewFlagSet("generate-subproject-ci", flag.ContinueOnError)
	fs.SetOutput(os.Stderr)

	parsed := args{
		ConfigPath: "tools/ci/subproject-validations.yaml",
	}
	fs.StringVar(&parsed.ConfigPath, "config", parsed.ConfigPath, "path to subproject validation config")
	fs.StringVar(&parsed.OutputPath, "output", "", "path to write generated child pipeline yaml")
	fs.StringVar(&parsed.GoWorkOutputPath, "go-work-output", "", "path to write generated go.work")
	fs.StringVar(&parsed.ReleaseOutputPath, "release-output", "", "path to write generated release-pipeline yaml")

	if err := fs.Parse(argv); err != nil {
		return args{}, err
	}
	if fs.NArg() != 0 {
		return args{}, fmt.Errorf("unexpected arguments: %s", strings.Join(fs.Args(), " "))
	}
	return parsed, nil
}

func loadConfig(path string) (configFile, error) {
	raw, err := os.ReadFile(path)
	if err != nil {
		return configFile{}, err
	}

	var cfg configFile
	if err := yaml.Unmarshal(raw, &cfg); err != nil {
		return configFile{}, err
	}
	if err := validateConfig(cfg); err != nil {
		return configFile{}, err
	}
	return cfg, nil
}

func validateConfig(cfg configFile) error {
	if cfg.Version != 1 {
		return fmt.Errorf("unsupported config version %d", cfg.Version)
	}
	if len(cfg.DefaultTags) == 0 {
		return errors.New("default_tags must not be empty")
	}
	// `profiles` may be empty when every subproject is release-only
	// (no validation jobs). Per-subproject validation below catches
	// references to undeclared profile names.
	if cfg.GoWork != nil {
		if strings.TrimSpace(cfg.GoWork.Go) == "" {
			return errors.New("go_work.go must not be empty")
		}
	}

	seenSubprojects := map[string]struct{}{}
	for _, subproject := range cfg.Subprojects {
		if strings.TrimSpace(subproject.ID) == "" {
			return errors.New("subproject id must not be empty")
		}
		if _, exists := seenSubprojects[subproject.ID]; exists {
			return fmt.Errorf("duplicate subproject id %q", subproject.ID)
		}
		seenSubprojects[subproject.ID] = struct{}{}
		if strings.TrimSpace(subproject.Path) == "" {
			return fmt.Errorf("subproject %q path must not be empty", subproject.ID)
		}
		if subproject.GoWork && cfg.GoWork == nil {
			return fmt.Errorf("subproject %q sets go_work but config does not define top-level go_work settings", subproject.ID)
		}
		// A subproject must declare at least one of `profile` (for the
		// child-pipeline validation jobs) or `release` (for the
		// release-pipeline auto-version + image-push jobs). The two
		// are orthogonal: a service can validate via the profile and
		// also opt into auto-released images.
		hasProfile := strings.TrimSpace(subproject.Profile) != ""
		hasRelease := subproject.Release != nil
		if !hasProfile && !hasRelease {
			return fmt.Errorf("subproject %q must set profile or release (or both)", subproject.ID)
		}
		if hasProfile {
			profile, ok := cfg.Profiles[subproject.Profile]
			if !ok {
				return fmt.Errorf("subproject %q references unknown profile %q", subproject.ID, subproject.Profile)
			}
			if strings.TrimSpace(profile.Image) == "" {
				return fmt.Errorf("profile %q image must not be empty", subproject.Profile)
			}
			if len(profile.Checks) == 0 {
				return fmt.Errorf("profile %q must define at least one check", subproject.Profile)
			}
			for _, chk := range profile.Checks {
				if err := validateCheck(subproject.Profile, chk); err != nil {
					return err
				}
			}
		}
		if hasRelease {
			if err := validateRelease(subproject.ID, subproject.Release); err != nil {
				return err
			}
		}
	}
	return nil
}

func validateRelease(id string, rel *releaseConfig) error {
	if strings.TrimSpace(rel.ServiceName) == "" {
		return fmt.Errorf("subproject %q release.service_name must not be empty", id)
	}
	if len(rel.ImagePushTargets) == 0 {
		return fmt.Errorf("subproject %q release.image_push_targets must not be empty", id)
	}
	seenTargets := map[string]struct{}{}
	for _, t := range rel.ImagePushTargets {
		if strings.TrimSpace(t.Name) == "" {
			return fmt.Errorf("subproject %q has release.image_push_targets entry with empty name", id)
		}
		if _, dup := seenTargets[t.Name]; dup {
			return fmt.Errorf("subproject %q has duplicate release.image_push_targets entry %q", id, t.Name)
		}
		seenTargets[t.Name] = struct{}{}
		if strings.TrimSpace(t.BazelTarget) == "" {
			return fmt.Errorf("subproject %q release target %q bazel_target must not be empty", id, t.Name)
		}
		switch t.Auth.Type {
		case "vault":
			if strings.TrimSpace(t.Auth.VaultKey) == "" {
				return fmt.Errorf("subproject %q release target %q vault auth requires vault_key", id, t.Name)
			}
		case "ci_var":
			if strings.TrimSpace(t.Auth.CIVar) == "" {
				return fmt.Errorf("subproject %q release target %q ci_var auth requires ci_var", id, t.Name)
			}
		default:
			return fmt.Errorf("subproject %q release target %q has unsupported auth type %q (want \"vault\" or \"ci_var\")", id, t.Name, t.Auth.Type)
		}
	}
	if rel.Helm != nil {
		if strings.TrimSpace(rel.Helm.ChartPath) == "" {
			return fmt.Errorf("subproject %q release.helm.chart_path must not be empty", id)
		}
		if len(rel.Helm.PushTargets) == 0 {
			return fmt.Errorf("subproject %q release.helm.push_targets must not be empty", id)
		}
		seenHelm := map[string]struct{}{}
		for _, t := range rel.Helm.PushTargets {
			if strings.TrimSpace(t.Name) == "" {
				return fmt.Errorf("subproject %q has release.helm.push_targets entry with empty name", id)
			}
			if _, dup := seenHelm[t.Name]; dup {
				return fmt.Errorf("subproject %q has duplicate release.helm.push_targets entry %q", id, t.Name)
			}
			seenHelm[t.Name] = struct{}{}
			hasLiteral := strings.TrimSpace(t.NGCPath) != ""
			hasVar := strings.TrimSpace(t.NGCPathVar) != ""
			if hasLiteral == hasVar {
				return fmt.Errorf("subproject %q helm push_target %q must set exactly one of ngc_path or ngc_path_var", id, t.Name)
			}
			if strings.TrimSpace(t.NGCKeyVar) == "" {
				return fmt.Errorf("subproject %q helm push_target %q ngc_key_var must not be empty", id, t.Name)
			}
		}
	}
	return nil
}

func validateCheck(profileName string, chk check) error {
	if strings.TrimSpace(chk.ID) == "" {
		return fmt.Errorf("profile %q has check with empty id", profileName)
	}
	switch chk.Type {
	case "go-vendor":
		return nil
	case "go-codegen":
		if strings.TrimSpace(chk.Command) == "" {
			return fmt.Errorf("profile %q check %q must set command", profileName, chk.ID)
		}
		return nil
	case "go-unit-tests":
		return nil
	case "shell":
		if strings.TrimSpace(chk.Command) == "" {
			return fmt.Errorf("profile %q check %q must set command", profileName, chk.ID)
		}
		return nil
	case "go-workspace-shell":
		if strings.TrimSpace(chk.Command) == "" {
			return fmt.Errorf("profile %q check %q must set command", profileName, chk.ID)
		}
		return nil
	default:
		return fmt.Errorf("profile %q check %q uses unsupported type %q", profileName, chk.ID, chk.Type)
	}
}

func renderPipeline(cfg configFile, configPath string) (string, error) {
	pipeline := generatedPipeline{
		ConfigPath:  configPath,
		DefaultTags: cfg.DefaultTags,
	}

	for _, subproject := range cfg.Subprojects {
		// Subprojects can declare only `release:` (no profile) when
		// they ship via the umbrella's per-service Bazel job plus the
		// generator-emitted release pipeline. They contribute nothing
		// to the validation child pipeline.
		if strings.TrimSpace(subproject.Profile) == "" {
			continue
		}
		profile := cfg.Profiles[subproject.Profile]
		for _, chk := range profile.Checks {
			job, err := buildJob(cfg.SharedChangePaths, profile, subproject, chk)
			if err != nil {
				return "", err
			}
			pipeline.Jobs = append(pipeline.Jobs, job)
		}
	}

	// GitLab fails a triggered child pipeline that ends up with zero jobs (for
	// example, when a change only touches files not listed in any job's
	// `changes:` rule, like a docs-only MR). Emit an unconditional sentinel so
	// the child pipeline always has at least one job to run.
	pipeline.Jobs = append(pipeline.Jobs, generatedJob{
		Name:      "subproject-validations-sentinel",
		Stage:     "validate",
		Image:     "golang:1.26-bookworm",
		AlwaysRun: true,
		Script:    []string{"echo 'subproject-validations: no path-gated jobs matched this change set.'"},
	})

	tmpl, err := template.New("pipeline").Funcs(template.FuncMap{
		"yamlValue": yamlScalar,
	}).Parse(pipelineTemplate)
	if err != nil {
		return "", err
	}

	view := struct {
		ConfigPath  string
		DefaultTags []string
		Jobs        []generatedJobView
	}{
		ConfigPath:  pipeline.ConfigPath,
		DefaultTags: pipeline.DefaultTags,
		Jobs:        make([]generatedJobView, 0, len(pipeline.Jobs)),
	}
	for _, job := range pipeline.Jobs {
		view.Jobs = append(view.Jobs, generatedJobView{
			Name:          job.Name,
			Stage:         job.Stage,
			Image:         job.Image,
			Variables:     job.Variables,
			VariablePairs: sortMap(job.Variables),
			Changes:       job.Changes,
			AlwaysRun:     job.AlwaysRun,
			Script:        job.Script,
			Coverage:      job.Coverage,
			Artifacts:     job.Artifacts,
		})
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, view); err != nil {
		return "", err
	}
	return buf.String(), nil
}

// renderReleasePipeline returns the YAML body of the release-jobs
// file (typically tools/ci/generated-release-jobs.yml). The umbrella
// .gitlab-ci.yml `include: local: ...`s this file. One block per
// subproject that declared `release:` in subproject-validations.yaml.
func renderReleasePipeline(cfg configFile, configPath string) (string, error) {
	view := releasePipelineView{ConfigPath: configPath}

	for _, sp := range cfg.Subprojects {
		if sp.Release == nil {
			continue
		}

		// YAML anchor names allow a-zA-Z0-9-_ but not all chars; use
		// a sanitized form to stay portable.
		anchor := strings.ReplaceAll(sp.ID, "-", "_") + "_release_paths"

		svc := releaseServiceView{
			ID:                  sp.ID,
			ServiceName:         sp.Release.ServiceName,
			Path:                sp.Path,
			ChangePaths:         sp.ChangePaths,
			RulesAnchor:         anchor,
			SlackChannel:        sp.Release.SlackChannel,
			SonarqubeProjectKey: sp.Release.SonarqubeProjectKey,
		}

		for _, t := range sp.Release.ImagePushTargets {
			svc.Targets = append(svc.Targets, releaseTargetView{
				Name:           t.Name,
				BazelTarget:    t.BazelTarget,
				AuthType:       t.Auth.Type,
				CIVar:          t.Auth.CIVar,
				DockerAuthPath: t.DockerAuthPath,
			})
			if t.Auth.Type == "vault" && !svc.HasVaultTarget {
				svc.HasVaultTarget = true
				svc.VaultKey = t.Auth.VaultKey
			}
		}

		// Dedupe ci_var names across targets so the template emits one
		// "is var set" guard per unique variable. Order preserved by
		// first-seen across image_push_targets.
		seenCIVar := map[string]struct{}{}
		for _, t := range sp.Release.ImagePushTargets {
			if t.Auth.Type != "ci_var" {
				continue
			}
			if _, ok := seenCIVar[t.Auth.CIVar]; ok {
				continue
			}
			seenCIVar[t.Auth.CIVar] = struct{}{}
			svc.CIVars = append(svc.CIVars, t.Auth.CIVar)
		}

		if sp.Release.Helm != nil {
			helmView := &releaseHelmView{
				ChartPath: path.Join(sp.Path, sp.Release.Helm.ChartPath),
				Lint:      sp.Release.Helm.Lint,
			}
			for _, t := range sp.Release.Helm.PushTargets {
				// One of NGCPath / NGCPathVar is set (enforced by
				// validateRelease). NGCPathVar takes a `$VARNAME` shape
				// so the cds-component expands it via its `expand_vars`
				// input filter at pipeline runtime.
				ngcPath := t.NGCPath
				if ngcPath == "" {
					ngcPath = "$" + t.NGCPathVar
				}
				helmView.PushTargets = append(helmView.PushTargets, releaseHelmTargetView{
					Name:      t.Name,
					NGCPath:   ngcPath,
					NGCKeyVar: t.NGCKeyVar,
				})
			}
			svc.Helm = helmView
		}

		view.Services = append(view.Services, svc)
	}

	tmpl, err := template.New("release-pipeline").Funcs(template.FuncMap{
		"yamlValue": yamlScalar,
		"upper":     strings.ToUpper,
	}).Parse(releasePipelineTemplate)
	if err != nil {
		return "", err
	}

	var buf strings.Builder
	if err := tmpl.Execute(&buf, view); err != nil {
		return "", err
	}
	return buf.String(), nil
}

func renderGoWork(cfg configFile, configPath string) (string, error) {
	if cfg.GoWork == nil {
		return "", errors.New("go_work is not configured")
	}

	useSet := map[string]struct{}{}
	for _, path := range cfg.GoWork.Use {
		trimmed := filepath.ToSlash(strings.TrimSpace(path))
		trimmed = strings.TrimPrefix(trimmed, "./")
		if trimmed == "" {
			continue
		}
		useSet[trimmed] = struct{}{}
	}
	for _, subproject := range cfg.Subprojects {
		if !subproject.GoWork {
			continue
		}
		trimmed := filepath.ToSlash(strings.TrimSpace(subproject.Path))
		trimmed = strings.TrimPrefix(trimmed, "./")
		if trimmed == "" {
			continue
		}
		useSet[trimmed] = struct{}{}
	}

	if len(useSet) == 0 {
		return "", errors.New("go_work has no modules to include")
	}

	usePaths := make([]string, 0, len(useSet))
	for path := range useSet {
		usePaths = append(usePaths, path)
	}
	sort.Strings(usePaths)

	view := struct {
		ConfigPath string
		GoVersion  string
		Use        []string
	}{
		ConfigPath: configPath,
		GoVersion:  cfg.GoWork.Go,
		Use:        usePaths,
	}

	tmpl, err := template.New("goWork").Parse(goWorkTemplate)
	if err != nil {
		return "", err
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, view); err != nil {
		return "", err
	}
	return buf.String(), nil
}

func buildJob(sharedChangePaths []string, profile profile, subproject subproject, chk check) (generatedJob, error) {
	data := subprojectTemplateData{
		ID:   subproject.ID,
		Path: subproject.Path,
	}

	jobName := sanitizeJobName(subproject.ID + "-" + chk.ID)
	stage := profile.Stage
	if strings.TrimSpace(stage) == "" {
		stage = "validate"
	}

	script, err := buildScript(profile, data, chk)
	if err != nil {
		return generatedJob{}, err
	}

	changes := append([]string{}, sharedChangePaths...)
	if len(subproject.ChangePaths) > 0 {
		changes = append(changes, subproject.ChangePaths...)
	} else {
		changes = append(changes, filepath.ToSlash(filepath.Join(subproject.Path, "**/*")))
	}

	image := profile.Image
	if strings.TrimSpace(chk.Image) != "" {
		image = chk.Image
	}

	job := generatedJob{
		Name:      jobName,
		Stage:     stage,
		Image:     image,
		Variables: profile.Variables,
		Changes:   changes,
		Script:    script,
	}

	if strings.TrimSpace(chk.Coverage) != "" {
		job.Coverage, err = renderTemplateString(chk.Coverage, data)
		if err != nil {
			return generatedJob{}, fmt.Errorf("job %q coverage: %w", jobName, err)
		}
	}
	if len(chk.Artifacts) > 0 {
		paths := make([]string, 0, len(chk.Artifacts))
		for _, artifactPath := range chk.Artifacts {
			rendered, err := renderTemplateString(artifactPath, data)
			if err != nil {
				return generatedJob{}, fmt.Errorf("job %q artifact path: %w", jobName, err)
			}
			paths = append(paths, rendered)
		}
		expireIn := chk.ExpireIn
		if strings.TrimSpace(expireIn) == "" {
			expireIn = "30 days"
		}
		job.Artifacts = &artifacts{
			Paths:    paths,
			ExpireIn: expireIn,
		}
	}

	return job, nil
}

func buildScript(profile profile, subproject subprojectTemplateData, chk check) ([]string, error) {
	prefix := workspaceSetupScript(profile, chk)

	switch chk.Type {
	case "go-vendor":
		return append(prefix,
			fmt.Sprintf("./tools/ci/check-go-vendor %s", shellQuote(subproject.Path)),
		), nil
	case "go-codegen":
		command, err := renderTemplateString(chk.Command, subproject)
		if err != nil {
			return nil, err
		}
		line := fmt.Sprintf("./tools/ci/check-go-codegen %s --command %s", shellQuote(subproject.Path), shellQuote(command))
		for _, install := range chk.Install {
			expanded, err := renderTemplateString(install, subproject)
			if err != nil {
				return nil, err
			}
			line += " --install " + shellQuote(expanded)
		}
		return append(prefix, line), nil
	case "go-unit-tests":
		resultsDir := chk.ResultsDir
		if strings.TrimSpace(resultsDir) == "" {
			resultsDir = filepath.ToSlash(filepath.Join("public", subproject.ID))
		}
		expandedResults, err := renderTemplateString(resultsDir, subproject)
		if err != nil {
			return nil, err
		}
		return append(prefix,
			fmt.Sprintf("./tools/ci/run-go-unit-tests %s --results-dir %s", shellQuote(subproject.Path), shellQuote(expandedResults)),
		), nil
	case "shell":
		command, err := renderTemplateString(chk.Command, subproject)
		if err != nil {
			return nil, err
		}
		return append(prefix,
			fmt.Sprintf("cd \"$CI_PROJECT_DIR/%s\" && %s", subproject.Path, command),
		), nil
	case "go-workspace-shell":
		command, err := renderTemplateString(chk.Command, subproject)
		if err != nil {
			return nil, err
		}
		return append(prefix,
			fmt.Sprintf("cd \"$CI_PROJECT_DIR/%s\" && GOWORK=\"$CI_PROJECT_DIR/go.work\" %s", subproject.Path, command),
		), nil
	default:
		return nil, fmt.Errorf("unsupported check type %q", chk.Type)
	}
}

func workspaceSetupScript(profile profile, chk check) []string {
	if chk.SkipWorkspaceSetup {
		return nil
	}

	if chk.Type == "go-workspace-shell" {
		return []string{"./tools/scripts/update-go-work"}
	}

	gowork, ok := profile.Variables["GOWORK"]
	if !ok {
		return nil
	}

	trimmed := strings.TrimSpace(gowork)
	if trimmed == "" || trimmed == "off" {
		return nil
	}

	return []string{"./tools/scripts/update-go-work"}
}

func renderTemplateString(input string, data subprojectTemplateData) (string, error) {
	tmpl, err := template.New("value").Option("missingkey=error").Parse(input)
	if err != nil {
		return "", err
	}
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", err
	}
	return buf.String(), nil
}

func sanitizeJobName(value string) string {
	lower := strings.ToLower(value)
	re := regexp.MustCompile(`[^a-z0-9]+`)
	lower = re.ReplaceAllString(lower, "-")
	lower = strings.Trim(lower, "-")
	if lower == "" {
		return "subproject-validation"
	}
	return lower
}

func shellQuote(value string) string {
	if value == "" {
		return "''"
	}
	return "'" + strings.ReplaceAll(value, "'", `'"'"'`) + "'"
}

func yamlScalar(value any) string {
	raw, err := yaml.Marshal(value)
	if err != nil {
		panic(err)
	}
	return strings.TrimSpace(string(raw))
}

func sortMap(values map[string]string) []keyValue {
	if len(values) == 0 {
		return nil
	}
	keys := make([]string, 0, len(values))
	for key := range values {
		keys = append(keys, key)
	}
	sort.Strings(keys)

	out := make([]keyValue, 0, len(keys))
	for _, key := range keys {
		out = append(out, keyValue{Key: key, Value: values[key]})
	}
	return out
}
