// SPDX-FileCopyrightText: Copyright (c) NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package main

import (
	"bytes"
	"errors"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"text/template"

	"gopkg.in/yaml.v3"
)

const pipelineTemplate = `# Generated by go run ./tools/generate-subproject-ci --config {{ yamlValue .ConfigPath }}.
default:
  tags:
{{- range .DefaultTags }}
    - {{ yamlValue . }}
{{- end }}

stages:
  - validate
{{- range .Jobs }}

{{ .Name }}:
  stage: {{ yamlValue .Stage }}
  image: {{ yamlValue .Image }}
{{- if .Variables }}
  variables:
{{- range .VariablePairs }}
    {{ .Key }}: {{ yamlValue .Value }}
{{- end }}
{{- end }}
  rules:
{{- if .AlwaysRun }}
    - when: always
{{- else }}
    - if: '$PARENT_PIPELINE_SOURCE == "schedule" || $PARENT_PIPELINE_SOURCE == "web"'
    - changes:
{{- range .Changes }}
        - {{ yamlValue . }}
{{- end }}
    - when: never
{{- end }}
  script:
{{- range .Script }}
    - {{ yamlValue . }}
{{- end }}
{{- if .Coverage }}
  coverage: {{ yamlValue .Coverage }}
{{- end }}
{{- if .Artifacts }}
  artifacts:
    when: always
    paths:
{{- range .Artifacts.Paths }}
      - {{ yamlValue . }}
{{- end }}
    expire_in: {{ yamlValue .Artifacts.ExpireIn }}
{{- end }}
{{- end }}
`

// releasePipelineTemplate is the YAML the umbrella `.gitlab-ci.yml`
// includes via `include: local: tools/ci/generated-release-jobs.yml`.
// One block per opted-in service (release: declared in
// tools/ci/subproject-validations.yaml):
//
//   compute-next-release-version-<id>  semantic-release dry-run; emits
//                                      NEXT_VERSION dotenv (init stage).
//   semantic-release-<id>              real semantic-release run on
//                                      default branch; creates the
//                                      <service_name>-v<version> git
//                                      tag (publish stage).
//   <id>-image-push                    consumes NEXT_VERSION dotenv;
//                                      pushes to each image_push_targets
//                                      entry (Prerequisites stage).
//
// Hidden templates (.compute-next-release-version-service,
// .semantic-release-service) keep the boilerplate centralized so each
// concrete job only restates SUBTREE + SERVICE_NAME + path-gated rules.
const releasePipelineTemplate = `# Generated by go run -C tools/generate-subproject-ci . --config {{ yamlValue .ConfigPath }} --release-output tools/ci/generated-release-jobs.yml.
# DO NOT EDIT BY HAND. To change release behavior for a service, update
# tools/ci/subproject-validations.yaml and re-run the generator. The
# umbrella's check-release-pipeline-generated job verifies the
# committed file matches what the generator would emit on this commit.
.compute-next-release-version-service:
  extends:
    - .nv-vault
    - .vault-reader-settings
  stage: init
  image: ${CDS_TOOLS_IMAGE}
  tags: [eks, nvcf-cds, prod]
  variables:
    SECRETS_TO_RETRIEVE_IN_JSON: >
      [
        {
          "path": "kv/gitlab/semantic-release/gl-token",
          "key": "token",
          "env_var": "GL_TOKEN"
        }
      ]
  before_script:
    - !reference [.nv-vault, before_script]
    - !reference [.vault-reader-before-script, before_script]
    - cd "$SUBTREE"
    - |
      cat > package.json <<EOF
      {
        "name": "${SERVICE_NAME}",
        "version": "1.0.0",
        "private": true,
        "devDependencies": {
          "semantic-release": "17.4.4",
          "@semantic-release/gitlab": "^8.0.0",
          "semantic-release-monorepo": "^7.0.0"
        }
      }
      EOF
      cat package.json
    - |
      cat > .releaserc.json <<EOF
      {
        "tagFormat": "${SERVICE_NAME}-v\${version}",
        "branches": ["main"],
        "plugins": [
          ["@semantic-release/commit-analyzer", {
            "releaseRules": [
              {"type": "feat", "release": "minor"},
              {"type": "fix", "release": "patch"},
              {"type": "chore", "release": "patch"},
              {"type": "refactor", "release": "patch"},
              {"type": "style", "release": "patch"},
              {"type": "docs", "release": "patch"},
              {"type": "ci", "release": "patch"},
              {"type": "perf", "release": "patch"}
            ]
          }],
          "@semantic-release/release-notes-generator",
          ["@semantic-release/gitlab", {
            "gitlabUrl": "https://github.com/NVIDIA",
            "assets": []
          }]
        ]
      }
      EOF
      cat .releaserc.json
    - npm install --legacy-peer-deps --silent
  script:
    - |
      echo -e "\e[0Ksection_start:` + "`" + `date +%s` + "`" + `:semantic_release[collapsed=true]\r\e[0KSemantic-release debug output..."
      npx semantic-release-monorepo --dry-run --no-ci --debug | tee semantic-release-output.log
      echo -e "\e[0Ksection_end:` + "`" + `date +%s` + "`" + `:semantic_release\r\e[0K"
    - npx semantic-release-monorepo --dry-run --no-ci
    - |
      NEXT_VERSION=$(awk '/next release version is/ {print $NF; exit}' semantic-release-output.log)
      if [ -z "$NEXT_VERSION" ]; then
        if [ "$CI_COMMIT_BRANCH" = "$CI_DEFAULT_BRANCH" ]; then
          NEXT_VERSION=$(git describe --tags --match="${SERVICE_NAME}-v*" --abbrev=0 2>/dev/null | sed "s/^${SERVICE_NAME}-v//" || echo "0.0.0")
        else
          NEXT_VERSION="${CI_COMMIT_SHORT_SHA}"
        fi
        SKIP_SEMANTIC_RELEASE=true
      else
        SKIP_SEMANTIC_RELEASE=false
      fi
      echo "NEXT_VERSION=${NEXT_VERSION}  SKIP_SEMANTIC_RELEASE=${SKIP_SEMANTIC_RELEASE}"
    - |
      touch release.env
      echo "NEXT_VERSION=${NEXT_VERSION}" > release.env
      echo "SKIP_SEMANTIC_RELEASE=${SKIP_SEMANTIC_RELEASE}" >> release.env
      mv release.env "${CI_PROJECT_DIR}/release.env"
  artifacts:
    reports:
      dotenv: release.env

.semantic-release-service:
  extends:
    - .nv-vault
    - .vault-reader-settings
  stage: publish
  image: ${CDS_TOOLS_IMAGE}
  tags: [eks, nvcf-cds, prod]
  variables:
    SECRETS_TO_RETRIEVE_IN_JSON: >
      [
        {
          "path": "kv/gitlab/semantic-release/gl-token",
          "key": "token",
          "env_var": "GL_TOKEN"
        }
      ]
  before_script:
    - !reference [.nv-vault, before_script]
    - !reference [.vault-reader-before-script, before_script]
    - cd "$SUBTREE"
    - |
      cat > package.json <<EOF
      {
        "name": "${SERVICE_NAME}",
        "version": "1.0.0",
        "private": true,
        "devDependencies": {
          "semantic-release": "17.4.4",
          "@semantic-release/gitlab": "^8.0.0",
          "semantic-release-monorepo": "^7.0.0"
        }
      }
      EOF
    - |
      cat > .releaserc.json <<EOF
      {
        "tagFormat": "${SERVICE_NAME}-v\${version}",
        "branches": ["main"],
        "plugins": [
          ["@semantic-release/commit-analyzer", {
            "releaseRules": [
              {"type": "feat", "release": "minor"},
              {"type": "fix", "release": "patch"},
              {"type": "chore", "release": "patch"},
              {"type": "refactor", "release": "patch"},
              {"type": "style", "release": "patch"},
              {"type": "docs", "release": "patch"},
              {"type": "ci", "release": "patch"},
              {"type": "perf", "release": "patch"}
            ]
          }],
          "@semantic-release/release-notes-generator",
          ["@semantic-release/gitlab", {
            "gitlabUrl": "https://github.com/NVIDIA",
            "assets": []
          }]
        ]
      }
      EOF
    - npm install --legacy-peer-deps --silent
  script:
    - |
      if [ "${SKIP_SEMANTIC_RELEASE}" = "true" ]; then
        echo "compute-next-release-version-${SERVICE_NAME} reported no semantic-release-worthy commit; skipping tag creation."
        exit 0
      fi
    - npx semantic-release-monorepo --no-ci
{{- range $svc := .Services }}

compute-next-release-version-{{ .ID }}:
  extends: .compute-next-release-version-service
  variables:
    SUBTREE: {{ yamlValue .Path }}
    SERVICE_NAME: {{ yamlValue .ServiceName }}
  rules:
    - if: $CI_MERGE_REQUEST_IID
      changes: &{{ .RulesAnchor }}
{{- range .ChangePaths }}
        - {{ yamlValue . }}
{{- end }}
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes: *{{ .RulesAnchor }}

semantic-release-{{ .ID }}:
  extends: .semantic-release-service
  variables:
    SUBTREE: {{ yamlValue .Path }}
    SERVICE_NAME: {{ yamlValue .ServiceName }}
  needs:
    - job: compute-next-release-version-{{ .ID }}
      artifacts: true
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes: *{{ .RulesAnchor }}

{{ .ID }}-image-push:
  extends:
    - .nv-vault
    - .vault-reader-settings
    - .bazel-remote-probe
  stage: Prerequisites
  image: $CI_REGISTRY_IMAGE/bazel-ci:$BAZEL_CI_VERSION
  needs:
    - job: bazel-ci-image
      optional: true
      artifacts: false
    - job: {{ .ID }}-bazel
      optional: true
    - job: compute-next-release-version-{{ .ID }}
      artifacts: true
      optional: true
  tags: [eks, nvcf-cds, prod]
  variables:
{{- if .HasVaultTarget }}
    NGC_REGISTRY_VAULT_KEY: {{ yamlValue .VaultKey }}
    SECRETS_TO_RETRIEVE_IN_JSON: >
      [
        {
          "path": "kv/gitlab/ngc-registry-auth/$NGC_REGISTRY_VAULT_KEY",
          "key": "NGC_REGISTRY",
          "env_var": "NGC_REGISTRY"
        },
        {
          "path": "kv/gitlab/ngc-registry-auth/$NGC_REGISTRY_VAULT_KEY",
          "key": "NGC_REGISTRY_TOKEN",
          "env_var": "NGC_REGISTRY_TOKEN"
        }
      ]
{{- end }}
    BAZEL_DISK_CACHE: $CI_PROJECT_DIR/.bazel-cache/disk
    BAZEL_REPO_CACHE: $CI_PROJECT_DIR/.bazel-cache/repo
  cache:
    - key:
        files:
          - {{ .Path }}/MODULE.bazel.lock
          - {{ .Path }}/.bazelversion
        prefix: {{ .ID }}-bazel-repo
      paths:
        - .bazel-cache/repo/
      policy: pull
    - key:
        files:
          - {{ .Path }}/.bazelversion
          - {{ .Path }}/.bazelrc
        prefix: {{ .ID }}-bazel-disk
      paths:
        - .bazel-cache/disk/
      policy: pull
  before_script:
{{- if .HasVaultTarget }}
    - !reference [.nv-vault, before_script]
    - !reference [.vault-reader-before-script, before_script]
{{- end }}
    - !reference [.bazel-remote-probe, before_script]
    - |
      BAZEL_REMOTE_FLAGS="${BAZEL_REMOTE_FLAGS//--config=remote-write /}"
      BAZEL_REMOTE_FLAGS="${BAZEL_REMOTE_FLAGS//--config=remote-write/}"
      export BAZEL_REMOTE_FLAGS
    - |
      if [ "${SKIP_SEMANTIC_RELEASE:-}" = "true" ] && [ -z "${CI_MERGE_REQUEST_IID:-}" ]; then
        echo "[{{ .ID }}-image-push] SKIP_SEMANTIC_RELEASE=true and not an MR pipeline; no new release-worthy commit since the last tag. Skipping image push to avoid overwriting an existing release tag."
        exit 0
      fi
    - |
      if [ -n "${NEXT_VERSION:-}" ]; then
        NVCF_VERSION="${NEXT_VERSION}"
      elif [ -n "${CI_COMMIT_TAG:-}" ]; then
        NVCF_VERSION="${CI_COMMIT_TAG#{{ .ServiceName }}-v}"
      elif [ -n "${CI_MERGE_REQUEST_IID:-}" ]; then
        NVCF_VERSION="mr.${CI_MERGE_REQUEST_IID}-${CI_COMMIT_SHORT_SHA}"
      else
        echo "[{{ .ID }}-image-push] ERROR: no NEXT_VERSION / CI_COMMIT_TAG / CI_MERGE_REQUEST_IID." >&2
        exit 1
      fi
      export NVCF_VERSION
      echo "[{{ .ID }}-image-push] using NVCF_VERSION=${NVCF_VERSION}"
    - |
      mkdir -p ~/.docker
{{- range .Targets }}
{{- if eq .AuthType "vault" }}
      {{ .Name | upper }}_AUTH=$(printf '$oauthtoken:%s' "${NGC_REGISTRY_TOKEN}" | base64 -w0)
{{- else if eq .AuthType "ci_var" }}
      if [ -z "${ {{- .CIVar -}} :-}" ]; then
        echo "[{{ $svc.ID }}-image-push] ERROR: {{ .CIVar }} is not set; {{ .Name }} push will fail." >&2
        exit 1
      fi
      {{ .Name | upper }}_AUTH=$(printf '$oauthtoken:%s' "${ {{- .CIVar -}} }" | base64 -w0)
{{- end }}
{{- end }}
  script:
    - cd {{ .Path }}
{{- range .Targets }}
{{- if eq .AuthType "vault" }}
    - |
      NGC_REGISTRY_HOST="${NGC_REGISTRY#https://}"
      NGC_REGISTRY_HOST="${NGC_REGISTRY_HOST#http://}"
      NGC_REGISTRY_HOST="${NGC_REGISTRY_HOST%%/*}"
      printf '{"auths":{"%s":{"auth":"%s"}}}\n' "${NGC_REGISTRY_HOST}" "${ {{- .Name | upper -}} _AUTH}" > ~/.docker/config.json
      chmod 600 ~/.docker/config.json
{{- else if eq .AuthType "ci_var" }}
    - |
      printf '{"auths":{"nvcr.io":{"auth":"%s"}}}\n' "${ {{- .Name | upper -}} _AUTH}" > ~/.docker/config.json
      chmod 600 ~/.docker/config.json
{{- end }}
    - bazel run --stamp ${BAZEL_REMOTE_FLAGS} --disk_cache=$BAZEL_DISK_CACHE --repository_cache=$BAZEL_REPO_CACHE {{ .BazelTarget }}
{{- end }}
  rules:
    - if: $CI_MERGE_REQUEST_IID
      changes: *{{ .RulesAnchor }}
      when: manual
      allow_failure: true
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes: *{{ .RulesAnchor }}
    - if: $CI_COMMIT_TAG =~ /^{{ .ServiceName }}-v/
{{- end }}
`

const goWorkTemplate = `// Generated by go run -C tools/generate-subproject-ci . --config {{ .ConfigPath }} --go-work-output go.work.
go {{ .GoVersion }}

use (
{{- range .Use }}
	./{{ . }}
{{- end }}
)
`

type releasePipelineView struct {
	ConfigPath string
	Services   []releaseServiceView
}

type releaseServiceView struct {
	ID             string
	ServiceName    string
	Path           string
	ChangePaths    []string
	RulesAnchor    string
	Targets        []releaseTargetView
	HasVaultTarget bool
	VaultKey       string
}

type releaseTargetView struct {
	Name        string
	BazelTarget string
	AuthType    string
	CIVar       string
}

type args struct {
	ConfigPath        string
	OutputPath        string
	GoWorkOutputPath  string
	ReleaseOutputPath string
}

type configFile struct {
	Version           int                `yaml:"version"`
	DefaultTags       []string           `yaml:"default_tags"`
	GoWork            *goWorkConfig      `yaml:"go_work"`
	SharedChangePaths []string           `yaml:"shared_change_paths"`
	Profiles          map[string]profile `yaml:"profiles"`
	Subprojects       []subproject       `yaml:"subprojects"`
}

type goWorkConfig struct {
	Go  string   `yaml:"go"`
	Use []string `yaml:"use"`
}

type profile struct {
	Stage     string            `yaml:"stage"`
	Image     string            `yaml:"image"`
	Variables map[string]string `yaml:"variables"`
	Checks    []check           `yaml:"checks"`
}

type subproject struct {
	ID          string         `yaml:"id"`
	Path        string         `yaml:"path"`
	Profile     string         `yaml:"profile"`
	ChangePaths []string       `yaml:"change_paths"`
	GoWork      bool           `yaml:"go_work"`
	Release     *releaseConfig `yaml:"release,omitempty"`
}

// releaseConfig is the opt-in declaration for an umbrella-native
// service that wants auto-versioned releases via semantic-release.
// The generator emits compute-next-release-version-<id>,
// semantic-release-<id>, and <id>-image-push jobs into the release
// pipeline YAML the umbrella includes via `include: local: ...`.
//
// Tag format is hard-coded to ${service_name}-v${version} (same shape
// used by semantic-release-monorepo) so per-service tags don't
// collide with other services or with the umbrella's own tags.
type releaseConfig struct {
	ServiceName      string                  `yaml:"service_name"`
	ImagePushTargets []releaseImagePushTarget `yaml:"image_push_targets"`
}

// releaseImagePushTarget describes one registry the image gets pushed
// to. Each target has its own Bazel push target (declared in the
// service's nvidia-internal/destinations.bzl) and its own auth source.
type releaseImagePushTarget struct {
	Name        string                 `yaml:"name"`
	BazelTarget string                 `yaml:"bazel_target"`
	Auth        releaseImagePushAuth   `yaml:"auth"`
}

// releaseImagePushAuth holds the credential source for one push
// target. `type: vault` fetches NGC_REGISTRY + NGC_REGISTRY_TOKEN
// from kv/gitlab/ngc-registry-auth/<vault_key>. `type: ci_var`
// uses the named GitLab CI/CD variable directly (typically set at
// the nvcf group level so every project inherits it).
type releaseImagePushAuth struct {
	Type     string `yaml:"type"`
	VaultKey string `yaml:"vault_key,omitempty"`
	CIVar    string `yaml:"ci_var,omitempty"`
}

type check struct {
	ID         string   `yaml:"id"`
	Type       string   `yaml:"type"`
	Command    string   `yaml:"command"`
	Install    []string `yaml:"install"`
	ResultsDir string   `yaml:"results_dir"`
	Coverage   string   `yaml:"coverage"`
	Artifacts  []string `yaml:"artifacts"`
	ExpireIn   string   `yaml:"expire_in"`
}

type subprojectTemplateData struct {
	ID   string
	Path string
}

type generatedPipeline struct {
	ConfigPath  string
	DefaultTags []string
	Jobs        []generatedJob
}

type generatedJob struct {
	Name      string
	Stage     string
	Image     string
	Variables map[string]string
	Changes   []string
	AlwaysRun bool
	Script    []string
	Coverage  string
	Artifacts *artifacts
}

type artifacts struct {
	Paths    []string
	ExpireIn string
}

type keyValue struct {
	Key   string
	Value string
}

type generatedJobView struct {
	Name          string
	Stage         string
	Image         string
	Variables     map[string]string
	VariablePairs []keyValue
	Changes       []string
	AlwaysRun     bool
	Script        []string
	Coverage      string
	Artifacts     *artifacts
}

func main() {
	if err := run(os.Args[1:], os.Stdout); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func run(argv []string, stdout *os.File) error {
	parsed, err := parseArgs(argv)
	if err != nil {
		return err
	}

	cfg, err := loadConfig(parsed.ConfigPath)
	if err != nil {
		return err
	}

	if parsed.GoWorkOutputPath != "" {
		renderedGoWork, err := renderGoWork(cfg, parsed.ConfigPath)
		if err != nil {
			return err
		}
		if err := os.WriteFile(parsed.GoWorkOutputPath, []byte(renderedGoWork), 0o644); err != nil {
			return err
		}
	}

	if parsed.ReleaseOutputPath != "" {
		renderedRelease, err := renderReleasePipeline(cfg, parsed.ConfigPath)
		if err != nil {
			return err
		}
		if err := os.WriteFile(parsed.ReleaseOutputPath, []byte(renderedRelease), 0o644); err != nil {
			return err
		}
	}

	if parsed.OutputPath == "" {
		// Only a non-default output path was requested (go-work
		// and/or release-output); skip the default child-pipeline
		// stdout dump.
		if parsed.GoWorkOutputPath != "" || parsed.ReleaseOutputPath != "" {
			return nil
		}
	}

	rendered, err := renderPipeline(cfg, parsed.ConfigPath)
	if err != nil {
		return err
	}

	if parsed.OutputPath == "" {
		_, err = stdout.WriteString(rendered)
		return err
	}

	return os.WriteFile(parsed.OutputPath, []byte(rendered), 0o644)
}

func parseArgs(argv []string) (args, error) {
	fs := flag.NewFlagSet("generate-subproject-ci", flag.ContinueOnError)
	fs.SetOutput(os.Stderr)

	parsed := args{
		ConfigPath: "tools/ci/subproject-validations.yaml",
	}
	fs.StringVar(&parsed.ConfigPath, "config", parsed.ConfigPath, "path to subproject validation config")
	fs.StringVar(&parsed.OutputPath, "output", "", "path to write generated child pipeline yaml")
	fs.StringVar(&parsed.GoWorkOutputPath, "go-work-output", "", "path to write generated go.work")
	fs.StringVar(&parsed.ReleaseOutputPath, "release-output", "", "path to write generated release-pipeline yaml")

	if err := fs.Parse(argv); err != nil {
		return args{}, err
	}
	if fs.NArg() != 0 {
		return args{}, fmt.Errorf("unexpected arguments: %s", strings.Join(fs.Args(), " "))
	}
	return parsed, nil
}

func loadConfig(path string) (configFile, error) {
	raw, err := os.ReadFile(path)
	if err != nil {
		return configFile{}, err
	}

	var cfg configFile
	if err := yaml.Unmarshal(raw, &cfg); err != nil {
		return configFile{}, err
	}
	if err := validateConfig(cfg); err != nil {
		return configFile{}, err
	}
	return cfg, nil
}

func validateConfig(cfg configFile) error {
	if cfg.Version != 1 {
		return fmt.Errorf("unsupported config version %d", cfg.Version)
	}
	if len(cfg.DefaultTags) == 0 {
		return errors.New("default_tags must not be empty")
	}
	// `profiles` may be empty when every subproject is release-only
	// (no validation jobs). Per-subproject validation below catches
	// references to undeclared profile names.
	if cfg.GoWork != nil {
		if strings.TrimSpace(cfg.GoWork.Go) == "" {
			return errors.New("go_work.go must not be empty")
		}
	}

	seenSubprojects := map[string]struct{}{}
	for _, subproject := range cfg.Subprojects {
		if strings.TrimSpace(subproject.ID) == "" {
			return errors.New("subproject id must not be empty")
		}
		if _, exists := seenSubprojects[subproject.ID]; exists {
			return fmt.Errorf("duplicate subproject id %q", subproject.ID)
		}
		seenSubprojects[subproject.ID] = struct{}{}
		if strings.TrimSpace(subproject.Path) == "" {
			return fmt.Errorf("subproject %q path must not be empty", subproject.ID)
		}
		if subproject.GoWork && cfg.GoWork == nil {
			return fmt.Errorf("subproject %q sets go_work but config does not define top-level go_work settings", subproject.ID)
		}
		// A subproject must declare at least one of `profile` (for the
		// child-pipeline validation jobs) or `release` (for the
		// release-pipeline auto-version + image-push jobs). The two
		// are orthogonal: a service can validate via the profile and
		// also opt into auto-released images.
		hasProfile := strings.TrimSpace(subproject.Profile) != ""
		hasRelease := subproject.Release != nil
		if !hasProfile && !hasRelease {
			return fmt.Errorf("subproject %q must set profile or release (or both)", subproject.ID)
		}
		if hasProfile {
			profile, ok := cfg.Profiles[subproject.Profile]
			if !ok {
				return fmt.Errorf("subproject %q references unknown profile %q", subproject.ID, subproject.Profile)
			}
			if strings.TrimSpace(profile.Image) == "" {
				return fmt.Errorf("profile %q image must not be empty", subproject.Profile)
			}
			if len(profile.Checks) == 0 {
				return fmt.Errorf("profile %q must define at least one check", subproject.Profile)
			}
			for _, chk := range profile.Checks {
				if err := validateCheck(subproject.Profile, chk); err != nil {
					return err
				}
			}
		}
		if hasRelease {
			if err := validateRelease(subproject.ID, subproject.Release); err != nil {
				return err
			}
		}
	}
	return nil
}

func validateRelease(id string, rel *releaseConfig) error {
	if strings.TrimSpace(rel.ServiceName) == "" {
		return fmt.Errorf("subproject %q release.service_name must not be empty", id)
	}
	if len(rel.ImagePushTargets) == 0 {
		return fmt.Errorf("subproject %q release.image_push_targets must not be empty", id)
	}
	seenTargets := map[string]struct{}{}
	for _, t := range rel.ImagePushTargets {
		if strings.TrimSpace(t.Name) == "" {
			return fmt.Errorf("subproject %q has release.image_push_targets entry with empty name", id)
		}
		if _, dup := seenTargets[t.Name]; dup {
			return fmt.Errorf("subproject %q has duplicate release.image_push_targets entry %q", id, t.Name)
		}
		seenTargets[t.Name] = struct{}{}
		if strings.TrimSpace(t.BazelTarget) == "" {
			return fmt.Errorf("subproject %q release target %q bazel_target must not be empty", id, t.Name)
		}
		switch t.Auth.Type {
		case "vault":
			if strings.TrimSpace(t.Auth.VaultKey) == "" {
				return fmt.Errorf("subproject %q release target %q vault auth requires vault_key", id, t.Name)
			}
		case "ci_var":
			if strings.TrimSpace(t.Auth.CIVar) == "" {
				return fmt.Errorf("subproject %q release target %q ci_var auth requires ci_var", id, t.Name)
			}
		default:
			return fmt.Errorf("subproject %q release target %q has unsupported auth type %q (want \"vault\" or \"ci_var\")", id, t.Name, t.Auth.Type)
		}
	}
	return nil
}

func validateCheck(profileName string, chk check) error {
	if strings.TrimSpace(chk.ID) == "" {
		return fmt.Errorf("profile %q has check with empty id", profileName)
	}
	switch chk.Type {
	case "go-vendor":
		return nil
	case "go-codegen":
		if strings.TrimSpace(chk.Command) == "" {
			return fmt.Errorf("profile %q check %q must set command", profileName, chk.ID)
		}
		return nil
	case "go-unit-tests":
		return nil
	case "shell":
		if strings.TrimSpace(chk.Command) == "" {
			return fmt.Errorf("profile %q check %q must set command", profileName, chk.ID)
		}
		return nil
	case "go-workspace-shell":
		if strings.TrimSpace(chk.Command) == "" {
			return fmt.Errorf("profile %q check %q must set command", profileName, chk.ID)
		}
		return nil
	default:
		return fmt.Errorf("profile %q check %q uses unsupported type %q", profileName, chk.ID, chk.Type)
	}
}

func renderPipeline(cfg configFile, configPath string) (string, error) {
	pipeline := generatedPipeline{
		ConfigPath:  configPath,
		DefaultTags: cfg.DefaultTags,
	}

	for _, subproject := range cfg.Subprojects {
		// Subprojects can declare only `release:` (no profile) when
		// they ship via the umbrella's per-service Bazel job plus the
		// generator-emitted release pipeline. They contribute nothing
		// to the validation child pipeline.
		if strings.TrimSpace(subproject.Profile) == "" {
			continue
		}
		profile := cfg.Profiles[subproject.Profile]
		for _, chk := range profile.Checks {
			job, err := buildJob(cfg.SharedChangePaths, profile, subproject, chk)
			if err != nil {
				return "", err
			}
			pipeline.Jobs = append(pipeline.Jobs, job)
		}
	}

	// GitLab fails a triggered child pipeline that ends up with zero jobs (for
	// example, when a change only touches files not listed in any job's
	// `changes:` rule, like a docs-only MR). Emit an unconditional sentinel so
	// the child pipeline always has at least one job to run.
	pipeline.Jobs = append(pipeline.Jobs, generatedJob{
		Name:      "subproject-validations-sentinel",
		Stage:     "validate",
		Image:     "golang:1.26-bookworm",
		AlwaysRun: true,
		Script:    []string{"echo 'subproject-validations: no path-gated jobs matched this change set.'"},
	})

	tmpl, err := template.New("pipeline").Funcs(template.FuncMap{
		"yamlValue": yamlScalar,
	}).Parse(pipelineTemplate)
	if err != nil {
		return "", err
	}

	view := struct {
		ConfigPath  string
		DefaultTags []string
		Jobs        []generatedJobView
	}{
		ConfigPath:  pipeline.ConfigPath,
		DefaultTags: pipeline.DefaultTags,
		Jobs:        make([]generatedJobView, 0, len(pipeline.Jobs)),
	}
	for _, job := range pipeline.Jobs {
		view.Jobs = append(view.Jobs, generatedJobView{
			Name:          job.Name,
			Stage:         job.Stage,
			Image:         job.Image,
			Variables:     job.Variables,
			VariablePairs: sortMap(job.Variables),
			Changes:       job.Changes,
			AlwaysRun:     job.AlwaysRun,
			Script:        job.Script,
			Coverage:      job.Coverage,
			Artifacts:     job.Artifacts,
		})
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, view); err != nil {
		return "", err
	}
	return buf.String(), nil
}

// renderReleasePipeline returns the YAML body of the release-jobs
// file (typically tools/ci/generated-release-jobs.yml). The umbrella
// .gitlab-ci.yml `include: local: ...`s this file. One block per
// subproject that declared `release:` in subproject-validations.yaml.
func renderReleasePipeline(cfg configFile, configPath string) (string, error) {
	view := releasePipelineView{ConfigPath: configPath}

	for _, sp := range cfg.Subprojects {
		if sp.Release == nil {
			continue
		}

		// YAML anchor names allow a-zA-Z0-9-_ but not all chars; use
		// a sanitized form to stay portable.
		anchor := strings.ReplaceAll(sp.ID, "-", "_") + "_release_paths"

		svc := releaseServiceView{
			ID:          sp.ID,
			ServiceName: sp.Release.ServiceName,
			Path:        sp.Path,
			ChangePaths: sp.ChangePaths,
			RulesAnchor: anchor,
		}

		for _, t := range sp.Release.ImagePushTargets {
			svc.Targets = append(svc.Targets, releaseTargetView{
				Name:        t.Name,
				BazelTarget: t.BazelTarget,
				AuthType:    t.Auth.Type,
				CIVar:       t.Auth.CIVar,
			})
			if t.Auth.Type == "vault" && !svc.HasVaultTarget {
				svc.HasVaultTarget = true
				svc.VaultKey = t.Auth.VaultKey
			}
		}

		view.Services = append(view.Services, svc)
	}

	tmpl, err := template.New("release-pipeline").Funcs(template.FuncMap{
		"yamlValue": yamlScalar,
		"upper":     strings.ToUpper,
	}).Parse(releasePipelineTemplate)
	if err != nil {
		return "", err
	}

	var buf strings.Builder
	if err := tmpl.Execute(&buf, view); err != nil {
		return "", err
	}
	return buf.String(), nil
}

func renderGoWork(cfg configFile, configPath string) (string, error) {
	if cfg.GoWork == nil {
		return "", errors.New("go_work is not configured")
	}

	useSet := map[string]struct{}{}
	for _, path := range cfg.GoWork.Use {
		trimmed := filepath.ToSlash(strings.TrimSpace(path))
		trimmed = strings.TrimPrefix(trimmed, "./")
		if trimmed == "" {
			continue
		}
		useSet[trimmed] = struct{}{}
	}
	for _, subproject := range cfg.Subprojects {
		if !subproject.GoWork {
			continue
		}
		trimmed := filepath.ToSlash(strings.TrimSpace(subproject.Path))
		trimmed = strings.TrimPrefix(trimmed, "./")
		if trimmed == "" {
			continue
		}
		useSet[trimmed] = struct{}{}
	}

	if len(useSet) == 0 {
		return "", errors.New("go_work has no modules to include")
	}

	usePaths := make([]string, 0, len(useSet))
	for path := range useSet {
		usePaths = append(usePaths, path)
	}
	sort.Strings(usePaths)

	view := struct {
		ConfigPath string
		GoVersion  string
		Use        []string
	}{
		ConfigPath: configPath,
		GoVersion:  cfg.GoWork.Go,
		Use:        usePaths,
	}

	tmpl, err := template.New("goWork").Parse(goWorkTemplate)
	if err != nil {
		return "", err
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, view); err != nil {
		return "", err
	}
	return buf.String(), nil
}

func buildJob(sharedChangePaths []string, profile profile, subproject subproject, chk check) (generatedJob, error) {
	data := subprojectTemplateData{
		ID:   subproject.ID,
		Path: subproject.Path,
	}

	jobName := sanitizeJobName(subproject.ID + "-" + chk.ID)
	stage := profile.Stage
	if strings.TrimSpace(stage) == "" {
		stage = "validate"
	}

	script, err := buildScript(profile, data, chk)
	if err != nil {
		return generatedJob{}, err
	}

	changes := append([]string{}, sharedChangePaths...)
	if len(subproject.ChangePaths) > 0 {
		changes = append(changes, subproject.ChangePaths...)
	} else {
		changes = append(changes, filepath.ToSlash(filepath.Join(subproject.Path, "**/*")))
	}

	job := generatedJob{
		Name:      jobName,
		Stage:     stage,
		Image:     profile.Image,
		Variables: profile.Variables,
		Changes:   changes,
		Script:    script,
	}

	if strings.TrimSpace(chk.Coverage) != "" {
		job.Coverage, err = renderTemplateString(chk.Coverage, data)
		if err != nil {
			return generatedJob{}, fmt.Errorf("job %q coverage: %w", jobName, err)
		}
	}
	if len(chk.Artifacts) > 0 {
		paths := make([]string, 0, len(chk.Artifacts))
		for _, artifactPath := range chk.Artifacts {
			rendered, err := renderTemplateString(artifactPath, data)
			if err != nil {
				return generatedJob{}, fmt.Errorf("job %q artifact path: %w", jobName, err)
			}
			paths = append(paths, rendered)
		}
		expireIn := chk.ExpireIn
		if strings.TrimSpace(expireIn) == "" {
			expireIn = "30 days"
		}
		job.Artifacts = &artifacts{
			Paths:    paths,
			ExpireIn: expireIn,
		}
	}

	return job, nil
}

func buildScript(profile profile, subproject subprojectTemplateData, chk check) ([]string, error) {
	prefix := workspaceSetupScript(profile, chk)

	switch chk.Type {
	case "go-vendor":
		return append(prefix,
			fmt.Sprintf("./tools/ci/check-go-vendor %s", shellQuote(subproject.Path)),
		), nil
	case "go-codegen":
		command, err := renderTemplateString(chk.Command, subproject)
		if err != nil {
			return nil, err
		}
		line := fmt.Sprintf("./tools/ci/check-go-codegen %s --command %s", shellQuote(subproject.Path), shellQuote(command))
		for _, install := range chk.Install {
			expanded, err := renderTemplateString(install, subproject)
			if err != nil {
				return nil, err
			}
			line += " --install " + shellQuote(expanded)
		}
		return append(prefix, line), nil
	case "go-unit-tests":
		resultsDir := chk.ResultsDir
		if strings.TrimSpace(resultsDir) == "" {
			resultsDir = filepath.ToSlash(filepath.Join("public", subproject.ID))
		}
		expandedResults, err := renderTemplateString(resultsDir, subproject)
		if err != nil {
			return nil, err
		}
		return append(prefix,
			fmt.Sprintf("./tools/ci/run-go-unit-tests %s --results-dir %s", shellQuote(subproject.Path), shellQuote(expandedResults)),
		), nil
	case "shell":
		command, err := renderTemplateString(chk.Command, subproject)
		if err != nil {
			return nil, err
		}
		return append(prefix,
			fmt.Sprintf("cd \"$CI_PROJECT_DIR/%s\" && %s", subproject.Path, command),
		), nil
	case "go-workspace-shell":
		command, err := renderTemplateString(chk.Command, subproject)
		if err != nil {
			return nil, err
		}
		return append(prefix,
			fmt.Sprintf("cd \"$CI_PROJECT_DIR/%s\" && GOWORK=\"$CI_PROJECT_DIR/go.work\" %s", subproject.Path, command),
		), nil
	default:
		return nil, fmt.Errorf("unsupported check type %q", chk.Type)
	}
}

func workspaceSetupScript(profile profile, chk check) []string {
	if chk.Type == "go-workspace-shell" {
		return []string{"./tools/scripts/update-go-work"}
	}

	gowork, ok := profile.Variables["GOWORK"]
	if !ok {
		return nil
	}

	trimmed := strings.TrimSpace(gowork)
	if trimmed == "" || trimmed == "off" {
		return nil
	}

	return []string{"./tools/scripts/update-go-work"}
}

func renderTemplateString(input string, data subprojectTemplateData) (string, error) {
	tmpl, err := template.New("value").Option("missingkey=error").Parse(input)
	if err != nil {
		return "", err
	}
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", err
	}
	return buf.String(), nil
}

func sanitizeJobName(value string) string {
	lower := strings.ToLower(value)
	re := regexp.MustCompile(`[^a-z0-9]+`)
	lower = re.ReplaceAllString(lower, "-")
	lower = strings.Trim(lower, "-")
	if lower == "" {
		return "subproject-validation"
	}
	return lower
}

func shellQuote(value string) string {
	if value == "" {
		return "''"
	}
	return "'" + strings.ReplaceAll(value, "'", `'"'"'`) + "'"
}

func yamlScalar(value any) string {
	raw, err := yaml.Marshal(value)
	if err != nil {
		panic(err)
	}
	return strings.TrimSpace(string(raw))
}

func sortMap(values map[string]string) []keyValue {
	if len(values) == 0 {
		return nil
	}
	keys := make([]string, 0, len(values))
	for key := range values {
		keys = append(keys, key)
	}
	sort.Strings(keys)

	out := make([]keyValue, 0, len(keys))
	for _, key := range keys {
		out = append(out, keyValue{Key: key, Value: values[key]})
	}
	return out
}
