// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: llm_gateway.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthLlmInvokeRequest struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	ClientAuthorizationToken string                 `protobuf:"bytes,1,opt,name=clientAuthorizationToken,proto3" json:"clientAuthorizationToken,omitempty"`
	RoutingKey               string                 `protobuf:"bytes,2,opt,name=routingKey,proto3" json:"routingKey,omitempty"` // This is just functionId
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *AuthLlmInvokeRequest) Reset() {
	*x = AuthLlmInvokeRequest{}
	mi := &file_llm_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthLlmInvokeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthLlmInvokeRequest) ProtoMessage() {}

func (x *AuthLlmInvokeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_llm_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthLlmInvokeRequest.ProtoReflect.Descriptor instead.
func (*AuthLlmInvokeRequest) Descriptor() ([]byte, []int) {
	return file_llm_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *AuthLlmInvokeRequest) GetClientAuthorizationToken() string {
	if x != nil {
		return x.ClientAuthorizationToken
	}
	return ""
}

func (x *AuthLlmInvokeRequest) GetRoutingKey() string {
	if x != nil {
		return x.RoutingKey
	}
	return ""
}

type AuthLlmInvokeResponse struct {
	state             protoimpl.MessageState                      `protogen:"open.v1"`
	RoutingKey        string                                      `protobuf:"bytes,1,opt,name=routingKey,proto3" json:"routingKey,omitempty"`
	ClientAuthSubject string                                      `protobuf:"bytes,2,opt,name=clientAuthSubject,proto3" json:"clientAuthSubject,omitempty"`
	AuthContext       map[string]string                           `protobuf:"bytes,3,rep,name=authContext,proto3" json:"authContext,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ModelSpecs        map[string]*AuthLlmInvokeResponse_ModelSpec `protobuf:"bytes,4,rep,name=modelSpecs,proto3" json:"modelSpecs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AuthLlmInvokeResponse) Reset() {
	*x = AuthLlmInvokeResponse{}
	mi := &file_llm_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthLlmInvokeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthLlmInvokeResponse) ProtoMessage() {}

func (x *AuthLlmInvokeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_llm_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthLlmInvokeResponse.ProtoReflect.Descriptor instead.
func (*AuthLlmInvokeResponse) Descriptor() ([]byte, []int) {
	return file_llm_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *AuthLlmInvokeResponse) GetRoutingKey() string {
	if x != nil {
		return x.RoutingKey
	}
	return ""
}

func (x *AuthLlmInvokeResponse) GetClientAuthSubject() string {
	if x != nil {
		return x.ClientAuthSubject
	}
	return ""
}

func (x *AuthLlmInvokeResponse) GetAuthContext() map[string]string {
	if x != nil {
		return x.AuthContext
	}
	return nil
}

func (x *AuthLlmInvokeResponse) GetModelSpecs() map[string]*AuthLlmInvokeResponse_ModelSpec {
	if x != nil {
		return x.ModelSpecs
	}
	return nil
}

type AuthLlmWorkerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerToken   string                 `protobuf:"bytes,1,opt,name=workerToken,proto3" json:"workerToken,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthLlmWorkerRequest) Reset() {
	*x = AuthLlmWorkerRequest{}
	mi := &file_llm_gateway_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthLlmWorkerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthLlmWorkerRequest) ProtoMessage() {}

func (x *AuthLlmWorkerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_llm_gateway_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthLlmWorkerRequest.ProtoReflect.Descriptor instead.
func (*AuthLlmWorkerRequest) Descriptor() ([]byte, []int) {
	return file_llm_gateway_proto_rawDescGZIP(), []int{2}
}

func (x *AuthLlmWorkerRequest) GetWorkerToken() string {
	if x != nil {
		return x.WorkerToken
	}
	return ""
}

type AuthLlmWorkerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoutingKey    string                 `protobuf:"bytes,1,opt,name=routingKey,proto3" json:"routingKey,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthLlmWorkerResponse) Reset() {
	*x = AuthLlmWorkerResponse{}
	mi := &file_llm_gateway_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthLlmWorkerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthLlmWorkerResponse) ProtoMessage() {}

func (x *AuthLlmWorkerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_llm_gateway_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthLlmWorkerResponse.ProtoReflect.Descriptor instead.
func (*AuthLlmWorkerResponse) Descriptor() ([]byte, []int) {
	return file_llm_gateway_proto_rawDescGZIP(), []int{3}
}

func (x *AuthLlmWorkerResponse) GetRoutingKey() string {
	if x != nil {
		return x.RoutingKey
	}
	return ""
}

type AuthLlmInvokeResponse_ModelSpec struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Uris           []string               `protobuf:"bytes,1,rep,name=uris,proto3" json:"uris,omitempty"`
	TokenRateLimit *string                `protobuf:"bytes,2,opt,name=tokenRateLimit,proto3,oneof" json:"tokenRateLimit,omitempty"`
	Tokenizer      *string                `protobuf:"bytes,3,opt,name=tokenizer,proto3,oneof" json:"tokenizer,omitempty"`
	RoutingMethod  *string                `protobuf:"bytes,4,opt,name=routingMethod,proto3,oneof" json:"routingMethod,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AuthLlmInvokeResponse_ModelSpec) Reset() {
	*x = AuthLlmInvokeResponse_ModelSpec{}
	mi := &file_llm_gateway_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthLlmInvokeResponse_ModelSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthLlmInvokeResponse_ModelSpec) ProtoMessage() {}

func (x *AuthLlmInvokeResponse_ModelSpec) ProtoReflect() protoreflect.Message {
	mi := &file_llm_gateway_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthLlmInvokeResponse_ModelSpec.ProtoReflect.Descriptor instead.
func (*AuthLlmInvokeResponse_ModelSpec) Descriptor() ([]byte, []int) {
	return file_llm_gateway_proto_rawDescGZIP(), []int{1, 2}
}

func (x *AuthLlmInvokeResponse_ModelSpec) GetUris() []string {
	if x != nil {
		return x.Uris
	}
	return nil
}

func (x *AuthLlmInvokeResponse_ModelSpec) GetTokenRateLimit() string {
	if x != nil && x.TokenRateLimit != nil {
		return *x.TokenRateLimit
	}
	return ""
}

func (x *AuthLlmInvokeResponse_ModelSpec) GetTokenizer() string {
	if x != nil && x.Tokenizer != nil {
		return *x.Tokenizer
	}
	return ""
}

func (x *AuthLlmInvokeResponse_ModelSpec) GetRoutingMethod() string {
	if x != nil && x.RoutingMethod != nil {
		return *x.RoutingMethod
	}
	return ""
}

var File_llm_gateway_proto protoreflect.FileDescriptor

const file_llm_gateway_proto_rawDesc = "" +
	"\n" +
	"\x11llm_gateway.proto\x12\vllm_gateway\"r\n" +
	"\x14AuthLlmInvokeRequest\x12:\n" +
	"\x18clientAuthorizationToken\x18\x01 \x01(\tR\x18clientAuthorizationToken\x12\x1e\n" +
	"\n" +
	"routingKey\x18\x02 \x01(\tR\n" +
	"routingKey\"\x8d\x05\n" +
	"\x15AuthLlmInvokeResponse\x12\x1e\n" +
	"\n" +
	"routingKey\x18\x01 \x01(\tR\n" +
	"routingKey\x12,\n" +
	"\x11clientAuthSubject\x18\x02 \x01(\tR\x11clientAuthSubject\x12U\n" +
	"\vauthContext\x18\x03 \x03(\v23.llm_gateway.AuthLlmInvokeResponse.AuthContextEntryR\vauthContext\x12R\n" +
	"\n" +
	"modelSpecs\x18\x04 \x03(\v22.llm_gateway.AuthLlmInvokeResponse.ModelSpecsEntryR\n" +
	"modelSpecs\x1a>\n" +
	"\x10AuthContextEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1ak\n" +
	"\x0fModelSpecsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12B\n" +
	"\x05value\x18\x02 \x01(\v2,.llm_gateway.AuthLlmInvokeResponse.ModelSpecR\x05value:\x028\x01\x1a\xcd\x01\n" +
	"\tModelSpec\x12\x12\n" +
	"\x04uris\x18\x01 \x03(\tR\x04uris\x12+\n" +
	"\x0etokenRateLimit\x18\x02 \x01(\tH\x00R\x0etokenRateLimit\x88\x01\x01\x12!\n" +
	"\ttokenizer\x18\x03 \x01(\tH\x01R\ttokenizer\x88\x01\x01\x12)\n" +
	"\rroutingMethod\x18\x04 \x01(\tH\x02R\rroutingMethod\x88\x01\x01B\x11\n" +
	"\x0f_tokenRateLimitB\f\n" +
	"\n" +
	"_tokenizerB\x10\n" +
	"\x0e_routingMethod\"8\n" +
	"\x14AuthLlmWorkerRequest\x12 \n" +
	"\vworkerToken\x18\x01 \x01(\tR\vworkerToken\"7\n" +
	"\x15AuthLlmWorkerResponse\x12\x1e\n" +
	"\n" +
	"routingKey\x18\x01 \x01(\tR\n" +
	"routingKey2\xc0\x01\n" +
	"\n" +
	"LlmGateway\x12Z\n" +
	"\x11AuthLlmInvocation\x12!.llm_gateway.AuthLlmInvokeRequest\x1a\".llm_gateway.AuthLlmInvokeResponse\x12V\n" +
	"\rAuthLlmWorker\x12!.llm_gateway.AuthLlmWorkerRequest\x1a\".llm_gateway.AuthLlmWorkerResponseB%\n" +
	"!com.nvidia.nvcf.proto.llm_gatewayP\x01b\x06proto3"

var (
	file_llm_gateway_proto_rawDescOnce sync.Once
	file_llm_gateway_proto_rawDescData []byte
)

func file_llm_gateway_proto_rawDescGZIP() []byte {
	file_llm_gateway_proto_rawDescOnce.Do(func() {
		file_llm_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_llm_gateway_proto_rawDesc), len(file_llm_gateway_proto_rawDesc)))
	})
	return file_llm_gateway_proto_rawDescData
}

var file_llm_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_llm_gateway_proto_goTypes = []any{
	(*AuthLlmInvokeRequest)(nil),            // 0: llm_gateway.AuthLlmInvokeRequest
	(*AuthLlmInvokeResponse)(nil),           // 1: llm_gateway.AuthLlmInvokeResponse
	(*AuthLlmWorkerRequest)(nil),            // 2: llm_gateway.AuthLlmWorkerRequest
	(*AuthLlmWorkerResponse)(nil),           // 3: llm_gateway.AuthLlmWorkerResponse
	nil,                                     // 4: llm_gateway.AuthLlmInvokeResponse.AuthContextEntry
	nil,                                     // 5: llm_gateway.AuthLlmInvokeResponse.ModelSpecsEntry
	(*AuthLlmInvokeResponse_ModelSpec)(nil), // 6: llm_gateway.AuthLlmInvokeResponse.ModelSpec
}
var file_llm_gateway_proto_depIdxs = []int32{
	4, // 0: llm_gateway.AuthLlmInvokeResponse.authContext:type_name -> llm_gateway.AuthLlmInvokeResponse.AuthContextEntry
	5, // 1: llm_gateway.AuthLlmInvokeResponse.modelSpecs:type_name -> llm_gateway.AuthLlmInvokeResponse.ModelSpecsEntry
	6, // 2: llm_gateway.AuthLlmInvokeResponse.ModelSpecsEntry.value:type_name -> llm_gateway.AuthLlmInvokeResponse.ModelSpec
	0, // 3: llm_gateway.LlmGateway.AuthLlmInvocation:input_type -> llm_gateway.AuthLlmInvokeRequest
	2, // 4: llm_gateway.LlmGateway.AuthLlmWorker:input_type -> llm_gateway.AuthLlmWorkerRequest
	1, // 5: llm_gateway.LlmGateway.AuthLlmInvocation:output_type -> llm_gateway.AuthLlmInvokeResponse
	3, // 6: llm_gateway.LlmGateway.AuthLlmWorker:output_type -> llm_gateway.AuthLlmWorkerResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_llm_gateway_proto_init() }
func file_llm_gateway_proto_init() {
	if File_llm_gateway_proto != nil {
		return
	}
	file_llm_gateway_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_llm_gateway_proto_rawDesc), len(file_llm_gateway_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_llm_gateway_proto_goTypes,
		DependencyIndexes: file_llm_gateway_proto_depIdxs,
		MessageInfos:      file_llm_gateway_proto_msgTypes,
	}.Build()
	File_llm_gateway_proto = out.File
	file_llm_gateway_proto_goTypes = nil
	file_llm_gateway_proto_depIdxs = nil
}
