// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.3
// source: llm_gateway.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LlmGateway_AuthLlmInvocation_FullMethodName = "/llm_gateway.LlmGateway/AuthLlmInvocation"
	LlmGateway_AuthLlmWorker_FullMethodName     = "/llm_gateway.LlmGateway/AuthLlmWorker"
)

// LlmGatewayClient is the client API for LlmGateway service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LlmGatewayClient interface {
	AuthLlmInvocation(ctx context.Context, in *AuthLlmInvokeRequest, opts ...grpc.CallOption) (*AuthLlmInvokeResponse, error)
	AuthLlmWorker(ctx context.Context, in *AuthLlmWorkerRequest, opts ...grpc.CallOption) (*AuthLlmWorkerResponse, error)
}

type llmGatewayClient struct {
	cc grpc.ClientConnInterface
}

func NewLlmGatewayClient(cc grpc.ClientConnInterface) LlmGatewayClient {
	return &llmGatewayClient{cc}
}

func (c *llmGatewayClient) AuthLlmInvocation(ctx context.Context, in *AuthLlmInvokeRequest, opts ...grpc.CallOption) (*AuthLlmInvokeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthLlmInvokeResponse)
	err := c.cc.Invoke(ctx, LlmGateway_AuthLlmInvocation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *llmGatewayClient) AuthLlmWorker(ctx context.Context, in *AuthLlmWorkerRequest, opts ...grpc.CallOption) (*AuthLlmWorkerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthLlmWorkerResponse)
	err := c.cc.Invoke(ctx, LlmGateway_AuthLlmWorker_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LlmGatewayServer is the server API for LlmGateway service.
// All implementations must embed UnimplementedLlmGatewayServer
// for forward compatibility.
type LlmGatewayServer interface {
	AuthLlmInvocation(context.Context, *AuthLlmInvokeRequest) (*AuthLlmInvokeResponse, error)
	AuthLlmWorker(context.Context, *AuthLlmWorkerRequest) (*AuthLlmWorkerResponse, error)
	mustEmbedUnimplementedLlmGatewayServer()
}

// UnimplementedLlmGatewayServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLlmGatewayServer struct{}

func (UnimplementedLlmGatewayServer) AuthLlmInvocation(context.Context, *AuthLlmInvokeRequest) (*AuthLlmInvokeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AuthLlmInvocation not implemented")
}
func (UnimplementedLlmGatewayServer) AuthLlmWorker(context.Context, *AuthLlmWorkerRequest) (*AuthLlmWorkerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AuthLlmWorker not implemented")
}
func (UnimplementedLlmGatewayServer) mustEmbedUnimplementedLlmGatewayServer() {}
func (UnimplementedLlmGatewayServer) testEmbeddedByValue()                    {}

// UnsafeLlmGatewayServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LlmGatewayServer will
// result in compilation errors.
type UnsafeLlmGatewayServer interface {
	mustEmbedUnimplementedLlmGatewayServer()
}

func RegisterLlmGatewayServer(s grpc.ServiceRegistrar, srv LlmGatewayServer) {
	// If the following call panics, it indicates UnimplementedLlmGatewayServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LlmGateway_ServiceDesc, srv)
}

func _LlmGateway_AuthLlmInvocation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthLlmInvokeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LlmGatewayServer).AuthLlmInvocation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LlmGateway_AuthLlmInvocation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LlmGatewayServer).AuthLlmInvocation(ctx, req.(*AuthLlmInvokeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LlmGateway_AuthLlmWorker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthLlmWorkerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LlmGatewayServer).AuthLlmWorker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LlmGateway_AuthLlmWorker_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LlmGatewayServer).AuthLlmWorker(ctx, req.(*AuthLlmWorkerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LlmGateway_ServiceDesc is the grpc.ServiceDesc for LlmGateway service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LlmGateway_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "llm_gateway.LlmGateway",
	HandlerType: (*LlmGatewayServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AuthLlmInvocation",
			Handler:    _LlmGateway_AuthLlmInvocation_Handler,
		},
		{
			MethodName: "AuthLlmWorker",
			Handler:    _LlmGateway_AuthLlmWorker_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "llm_gateway.proto",
}
