// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: ratelimiter.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RateLimitResult int32

const (
	RateLimitResult_ALLOW    RateLimitResult = 0
	RateLimitResult_DISALLOW RateLimitResult = 1
)

// Enum value maps for RateLimitResult.
var (
	RateLimitResult_name = map[int32]string{
		0: "ALLOW",
		1: "DISALLOW",
	}
	RateLimitResult_value = map[string]int32{
		"ALLOW":    0,
		"DISALLOW": 1,
	}
)

func (x RateLimitResult) Enum() *RateLimitResult {
	p := new(RateLimitResult)
	*p = x
	return p
}

func (x RateLimitResult) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RateLimitResult) Descriptor() protoreflect.EnumDescriptor {
	return file_ratelimiter_proto_enumTypes[0].Descriptor()
}

func (RateLimitResult) Type() protoreflect.EnumType {
	return &file_ratelimiter_proto_enumTypes[0]
}

func (x RateLimitResult) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RateLimitResult.Descriptor instead.
func (RateLimitResult) EnumDescriptor() ([]byte, []int) {
	return file_ratelimiter_proto_rawDescGZIP(), []int{0}
}

type RateLimitRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	NcaId             string                 `protobuf:"bytes,1,opt,name=ncaId,proto3" json:"ncaId,omitempty"`
	FunctionId        string                 `protobuf:"bytes,2,opt,name=functionId,proto3" json:"functionId,omitempty"`
	FunctionVersionId string                 `protobuf:"bytes,3,opt,name=functionVersionId,proto3" json:"functionVersionId,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RateLimitRequest) Reset() {
	*x = RateLimitRequest{}
	mi := &file_ratelimiter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RateLimitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateLimitRequest) ProtoMessage() {}

func (x *RateLimitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ratelimiter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateLimitRequest.ProtoReflect.Descriptor instead.
func (*RateLimitRequest) Descriptor() ([]byte, []int) {
	return file_ratelimiter_proto_rawDescGZIP(), []int{0}
}

func (x *RateLimitRequest) GetNcaId() string {
	if x != nil {
		return x.NcaId
	}
	return ""
}

func (x *RateLimitRequest) GetFunctionId() string {
	if x != nil {
		return x.FunctionId
	}
	return ""
}

func (x *RateLimitRequest) GetFunctionVersionId() string {
	if x != nil {
		return x.FunctionVersionId
	}
	return ""
}

type RateLimitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        RateLimitResult        `protobuf:"varint,1,opt,name=result,proto3,enum=nvcfratelimiter.RateLimitResult" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RateLimitResponse) Reset() {
	*x = RateLimitResponse{}
	mi := &file_ratelimiter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RateLimitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateLimitResponse) ProtoMessage() {}

func (x *RateLimitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ratelimiter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateLimitResponse.ProtoReflect.Descriptor instead.
func (*RateLimitResponse) Descriptor() ([]byte, []int) {
	return file_ratelimiter_proto_rawDescGZIP(), []int{1}
}

func (x *RateLimitResponse) GetResult() RateLimitResult {
	if x != nil {
		return x.Result
	}
	return RateLimitResult_ALLOW
}

var File_ratelimiter_proto protoreflect.FileDescriptor

const file_ratelimiter_proto_rawDesc = "" +
	"\n" +
	"\x11ratelimiter.proto\x12\x0fnvcfratelimiter\"v\n" +
	"\x10RateLimitRequest\x12\x14\n" +
	"\x05ncaId\x18\x01 \x01(\tR\x05ncaId\x12\x1e\n" +
	"\n" +
	"functionId\x18\x02 \x01(\tR\n" +
	"functionId\x12,\n" +
	"\x11functionVersionId\x18\x03 \x01(\tR\x11functionVersionId\"M\n" +
	"\x11RateLimitResponse\x128\n" +
	"\x06result\x18\x01 \x01(\x0e2 .nvcfratelimiter.RateLimitResultR\x06result**\n" +
	"\x0fRateLimitResult\x12\t\n" +
	"\x05ALLOW\x10\x00\x12\f\n" +
	"\bDISALLOW\x10\x012h\n" +
	"\x10RateLimitService\x12T\n" +
	"\tRateLimit\x12!.nvcfratelimiter.RateLimitRequest\x1a\".nvcfratelimiter.RateLimitResponse\"\x00b\x06proto3"

var (
	file_ratelimiter_proto_rawDescOnce sync.Once
	file_ratelimiter_proto_rawDescData []byte
)

func file_ratelimiter_proto_rawDescGZIP() []byte {
	file_ratelimiter_proto_rawDescOnce.Do(func() {
		file_ratelimiter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ratelimiter_proto_rawDesc), len(file_ratelimiter_proto_rawDesc)))
	})
	return file_ratelimiter_proto_rawDescData
}

var file_ratelimiter_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_ratelimiter_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ratelimiter_proto_goTypes = []any{
	(RateLimitResult)(0),      // 0: nvcfratelimiter.RateLimitResult
	(*RateLimitRequest)(nil),  // 1: nvcfratelimiter.RateLimitRequest
	(*RateLimitResponse)(nil), // 2: nvcfratelimiter.RateLimitResponse
}
var file_ratelimiter_proto_depIdxs = []int32{
	0, // 0: nvcfratelimiter.RateLimitResponse.result:type_name -> nvcfratelimiter.RateLimitResult
	1, // 1: nvcfratelimiter.RateLimitService.RateLimit:input_type -> nvcfratelimiter.RateLimitRequest
	2, // 2: nvcfratelimiter.RateLimitService.RateLimit:output_type -> nvcfratelimiter.RateLimitResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ratelimiter_proto_init() }
func file_ratelimiter_proto_init() {
	if File_ratelimiter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ratelimiter_proto_rawDesc), len(file_ratelimiter_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ratelimiter_proto_goTypes,
		DependencyIndexes: file_ratelimiter_proto_depIdxs,
		EnumInfos:         file_ratelimiter_proto_enumTypes,
		MessageInfos:      file_ratelimiter_proto_msgTypes,
	}.Build()
	File_ratelimiter_proto = out.File
	file_ratelimiter_proto_goTypes = nil
	file_ratelimiter_proto_depIdxs = nil
}
