# SPDX-FileCopyrightText: Copyright (c) NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

ARG TAG=v4.0.1
ARG IMG=urm.nvidia.com/sw-gpu-ucs-hardened-docker/distroless/go
FROM --platform=$TARGETPLATFORM dockerhub.nvidia.com/golang:1.25.6-bookworm AS builder
ARG TARGETOS
ARG TARGETARCH

WORKDIR /openssl

# COPY your dependencies
COPY docker/deps.json deps.json

# /ess-agent/logs is made available to use as a location to store audit logs, if
# desired; /ess-agent/file is made available to use as a location with the file
# storage backend, if desired.
RUN mkdir -p /ess-agent/logs && \
    mkdir -p /ess-agent/file

# Install openssl and it's required dependencies
# fetch the builder script
RUN wget -q https://urm.nvidia.com/artifactory/sw-gpu-ucs-hardened-debian/tools/generate_metadata_v0.3.sh -O generate_metadata.sh &&\
     chmod +x generate_metadata.sh &&\
     ./generate_metadata.sh deps.json

FROM --platform=$TARGETPLATFORM $IMG:$TAG
LABEL authors="NVIDIA Vault Team <vault-support@exchange.nvidia.com>"
ARG TARGETOS
ARG TARGETARCH

# Copy binary from host
COPY builds/${TARGETOS}_${TARGETARCH}/ess-agent /bin/ess-agent

# Copy the status.d for scanning
COPY --from=builder /var/lib/dpkg/status.d/ /var/lib/dpkg/status.d/
# No need to copy the .so files from /lib/distroless as golang binaries are self contained

COPY --from=builder /ess-agent /ess-agent

# Expose the logs directory as a volume since there's potentially long-running
# state in there
VOLUME /ess-agent/logs

# Expose the file directory as a volume since there's potentially long-running
# state in there
VOLUME /ess-agent/file

# Expose default metrics port
EXPOSE 9103

ENTRYPOINT ["/bin/ess-agent"]
