# SPDX-FileCopyrightText: Copyright (c) NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# CI test image: extends the Go build image with HashiCorp binaries
# needed for integration tests (vault, consul, nomad dev servers).
#
# Build:
#   docker build -f nv_releases/docker/Dockerfile.ci -t ess-agent-ci:golang-1.25.6 .
#
# Push (example):
#   docker tag ess-agent-ci:golang-1.25.6 urm.nvidia.com/sw-nvcf-docker/ess-agent-ci:golang-1.25.6
#   docker push urm.nvidia.com/sw-nvcf-docker/ess-agent-ci:golang-1.25.6

FROM golang:1.25.6-bookworm

ARG VAULT_VERSION=1.17.2
ARG CONSUL_VERSION=1.20.0
ARG NOMAD_VERSION=1.9.7

RUN apt-get update -qq && apt-get install -y -qq unzip > /dev/null \
    && curl -fsSL "https://releases.hashicorp.com/vault/${VAULT_VERSION}/vault_${VAULT_VERSION}_linux_amd64.zip" -o /tmp/vault.zip \
    && curl -fsSL "https://releases.hashicorp.com/consul/${CONSUL_VERSION}/consul_${CONSUL_VERSION}_linux_amd64.zip" -o /tmp/consul.zip \
    && curl -fsSL "https://releases.hashicorp.com/nomad/${NOMAD_VERSION}/nomad_${NOMAD_VERSION}_linux_amd64.zip" -o /tmp/nomad.zip \
    && unzip -oq /tmp/vault.zip -d /usr/local/bin \
    && unzip -oq /tmp/consul.zip -d /usr/local/bin \
    && unzip -oq /tmp/nomad.zip -d /usr/local/bin \
    && rm /tmp/*.zip \
    && apt-get remove -y unzip && apt-get autoremove -y && rm -rf /var/lib/apt/lists/*

RUN vault version && consul version && nomad version
